-- Seed de conteúdo: Tecnologia, nível Fácil (50 perguntas)
-- Fonte: lote de perguntas fornecido pelo proprietário do projeto.
--
-- CORREÇÃO DE QUALIDADE APLICADA (não é decisão de negócio, é higiene de
-- dado): no lote original, as 50 respostas corretas eram TODAS a alternativa
-- "A". Isso tornaria o quiz trivialmente decorável ("sempre marque a primeira")
-- sem nenhum conhecimento real, quebrando o propósito educativo e o valor do
-- Trust Score. A posição da alternativa correta foi redistribuída por pergunta
-- com seed fixa (42) e distribuição controlada (~13/13/12/12 entre A/B/C/D),
-- reprodutível — o conteúdo pedagógico (perguntas, alternativas) permanece
-- exatamente como enviado, só a ORDEM de exibição de cada alternativa mudou.
--
-- Idempotente: usa a coluna `source` (migration 022) como marcador — rodar
-- este arquivo mais de uma vez não duplica as perguntas.

BEGIN;

DO $$
DECLARE
  v_category_id UUID;
BEGIN
  SELECT id INTO v_category_id FROM categories WHERE slug = 'tecnologia';
  IF v_category_id IS NULL THEN
    RAISE EXCEPTION 'Categoria "tecnologia" não encontrada — rode a migration 021 primeiro.';
  END IF;

  IF EXISTS (SELECT 1 FROM questions WHERE source = 'seed_tecnologia_facil_v1') THEN
    RAISE NOTICE 'Perguntas de Tecnologia (fácil) já foram inseridas anteriormente — nada a fazer.';
  ELSE

    CREATE TEMP TABLE tmp_new_questions_tec_facil AS
    WITH inserted AS (
    INSERT INTO questions (category_id, difficulty, statement, time_limit_seconds, xp_reward, source)
    SELECT v_category_id, 'easy', v.statement, 15, 10, 'seed_tecnologia_facil_v1'
    FROM (VALUES
      ('O que é um computador?'),
      ('Qual componente é considerado o "cérebro" do computador?'),
      ('Qual é a função principal do teclado?'),
      ('Qual dispositivo apresenta informações visuais ao usuário?'),
      ('O que é um smartphone?'),
      ('Qual sistema operacional é muito utilizado em smartphones?'),
      ('O que é um aplicativo?'),
      ('Onde normalmente são instalados aplicativos em um smartphone?'),
      ('O que é a internet?'),
      ('Qual destes é um navegador de internet?'),
      ('Para que serve um navegador?'),
      ('O que é um site?'),
      ('O que é um endereço de site?'),
      ('O que significa Wi-Fi?'),
      ('Para que serve um roteador?'),
      ('O que é uma senha?'),
      ('Por que devemos evitar compartilhar senhas?'),
      ('O que é um arquivo?'),
      ('Qual destes é um exemplo de arquivo?'),
      ('O que é uma pasta no computador?'),
      ('O que é memória de armazenamento?'),
      ('Qual destes é um dispositivo de armazenamento?'),
      ('Para que serve um pen drive?'),
      ('O que é uma fotografia digital?'),
      ('O que é vídeo digital?'),
      ('O que é email?'),
      ('Qual destes é um serviço de email?'),
      ('O que é uma mensagem instantânea?'),
      ('Qual aplicativo é conhecido por mensagens instantâneas?'),
      ('O que é uma chamada de vídeo?'),
      ('O que é inteligência artificial?'),
      ('Qual é um exemplo de inteligência artificial?'),
      ('O que é uma atualização de aplicativo?'),
      ('Por que atualizar aplicativos?'),
      ('O que é um vírus de computador?'),
      ('O que é antivírus?'),
      ('O que é backup?'),
      ('Por que fazer backup?'),
      ('O que é nuvem (cloud)?'),
      ('Qual é um exemplo de armazenamento em nuvem?'),
      ('O que é Bluetooth?'),
      ('O que é GPS?'),
      ('O que é QR Code?'),
      ('O que é uma rede social?'),
      ('Qual destes é uma rede social?'),
      ('O que é download?'),
      ('O que é upload?'),
      ('O que é segurança digital?'),
      ('Qual atitude aumenta a segurança online?'),
      ('Por que a tecnologia é importante atualmente?')
    ) AS v(statement)
    RETURNING id, statement
    )
    SELECT * FROM inserted;

    INSERT INTO question_alternatives (question_id, label, is_correct, display_order)
    SELECT q.id, a.label, a.is_correct, a.display_order
    FROM tmp_new_questions_tec_facil q
    JOIN (VALUES
      ('O que é um computador?', 'Um tipo de internet', FALSE, 0),
      ('O que é um computador?', 'Dispositivo eletrônico capaz de processar, armazenar e transmitir informações', TRUE, 1),
      ('O que é um computador?', 'Apenas uma tela para assistir vídeos', FALSE, 2),
      ('O que é um computador?', 'Um programa de edição', FALSE, 3),
      ('Qual componente é considerado o "cérebro" do computador?', 'Impressora', FALSE, 0),
      ('Qual componente é considerado o "cérebro" do computador?', 'Processador (CPU)', TRUE, 1),
      ('Qual componente é considerado o "cérebro" do computador?', 'Teclado', FALSE, 2),
      ('Qual componente é considerado o "cérebro" do computador?', 'Monitor', FALSE, 3),
      ('Qual é a função principal do teclado?', 'Exibir imagens', FALSE, 0),
      ('Qual é a função principal do teclado?', 'Permitir entrada de textos e comandos no computador', TRUE, 1),
      ('Qual é a função principal do teclado?', 'Guardar arquivos', FALSE, 2),
      ('Qual é a função principal do teclado?', 'Aumentar a velocidade da internet', FALSE, 3),
      ('Qual dispositivo apresenta informações visuais ao usuário?', 'Monitor', TRUE, 0),
      ('Qual dispositivo apresenta informações visuais ao usuário?', 'Mouse', FALSE, 1),
      ('Qual dispositivo apresenta informações visuais ao usuário?', 'Microfone', FALSE, 2),
      ('Qual dispositivo apresenta informações visuais ao usuário?', 'Scanner', FALSE, 3),
      ('O que é um smartphone?', 'Telefone inteligente com capacidade de executar aplicativos e acessar internet', TRUE, 0),
      ('O que é um smartphone?', 'Um computador sem tela', FALSE, 1),
      ('O que é um smartphone?', 'Apenas um telefone para chamadas', FALSE, 2),
      ('O que é um smartphone?', 'Um tipo de impressora', FALSE, 3),
      ('Qual sistema operacional é muito utilizado em smartphones?', 'Bluetooth', FALSE, 0),
      ('Qual sistema operacional é muito utilizado em smartphones?', 'HDMI', FALSE, 1),
      ('Qual sistema operacional é muito utilizado em smartphones?', 'USB', FALSE, 2),
      ('Qual sistema operacional é muito utilizado em smartphones?', 'Android', TRUE, 3),
      ('O que é um aplicativo?', 'Cabo de internet', FALSE, 0),
      ('O que é um aplicativo?', 'Tipo de bateria', FALSE, 1),
      ('O que é um aplicativo?', 'Programa criado para realizar uma determinada função em um dispositivo', TRUE, 2),
      ('O que é um aplicativo?', 'Peça física do computador', FALSE, 3),
      ('Onde normalmente são instalados aplicativos em um smartphone?', 'Loja de aplicativos', TRUE, 0),
      ('Onde normalmente são instalados aplicativos em um smartphone?', 'Processador', FALSE, 1),
      ('Onde normalmente são instalados aplicativos em um smartphone?', 'Teclado', FALSE, 2),
      ('Onde normalmente são instalados aplicativos em um smartphone?', 'Monitor', FALSE, 3),
      ('O que é a internet?', 'Uma peça do computador', FALSE, 0),
      ('O que é a internet?', 'Um tipo de memória', FALSE, 1),
      ('O que é a internet?', 'Rede mundial que permite comunicação e acesso a informações', TRUE, 2),
      ('O que é a internet?', 'Apenas um aplicativo', FALSE, 3),
      ('Qual destes é um navegador de internet?', 'Android', FALSE, 0),
      ('Qual destes é um navegador de internet?', 'Google Chrome', TRUE, 1),
      ('Qual destes é um navegador de internet?', 'WhatsApp', FALSE, 2),
      ('Qual destes é um navegador de internet?', 'Windows', FALSE, 3),
      ('Para que serve um navegador?', 'Aumentar a bateria', FALSE, 0),
      ('Para que serve um navegador?', 'Guardar arquivos automaticamente', FALSE, 1),
      ('Para que serve um navegador?', 'Acessar sites e serviços disponíveis na internet', TRUE, 2),
      ('Para que serve um navegador?', 'Criar componentes físicos', FALSE, 3),
      ('O que é um site?', 'Um processador', FALSE, 0),
      ('O que é um site?', 'Conjunto de páginas disponíveis na internet', TRUE, 1),
      ('O que é um site?', 'Um aplicativo físico', FALSE, 2),
      ('O que é um site?', 'Um cabo de computador', FALSE, 3),
      ('O que é um endereço de site?', 'Nome ou endereço utilizado para encontrar uma página na internet', TRUE, 0),
      ('O que é um endereço de site?', 'Modelo do teclado', FALSE, 1),
      ('O que é um endereço de site?', 'Senha do computador', FALSE, 2),
      ('O que é um endereço de site?', 'Número da bateria', FALSE, 3),
      ('O que significa Wi-Fi?', 'Tecnologia de conexão sem fio a uma rede', TRUE, 0),
      ('O que significa Wi-Fi?', 'Tipo de computador', FALSE, 1),
      ('O que significa Wi-Fi?', 'Aplicativo de mensagens', FALSE, 2),
      ('O que significa Wi-Fi?', 'Sistema operacional', FALSE, 3),
      ('Para que serve um roteador?', 'Guardar documentos', FALSE, 0),
      ('Para que serve um roteador?', 'Aumentar o tamanho da tela', FALSE, 1),
      ('Para que serve um roteador?', 'Criar aplicativos', FALSE, 2),
      ('Para que serve um roteador?', 'Distribuir conexão de rede para dispositivos', TRUE, 3),
      ('O que é uma senha?', 'Tipo de arquivo', FALSE, 0),
      ('O que é uma senha?', 'Nome do usuário', FALSE, 1),
      ('O que é uma senha?', 'Modelo do computador', FALSE, 2),
      ('O que é uma senha?', 'Código usado para proteger e acessar uma conta ou dispositivo', TRUE, 3),
      ('Por que devemos evitar compartilhar senhas?', 'Para proteger contas e informações pessoais', TRUE, 0),
      ('Por que devemos evitar compartilhar senhas?', 'Para melhorar a câmera', FALSE, 1),
      ('Por que devemos evitar compartilhar senhas?', 'Para aumentar a velocidade da internet', FALSE, 2),
      ('Por que devemos evitar compartilhar senhas?', 'Para instalar aplicativos', FALSE, 3),
      ('O que é um arquivo?', 'Um aplicativo obrigatório', FALSE, 0),
      ('O que é um arquivo?', 'Unidade digital onde informações são armazenadas', TRUE, 1),
      ('O que é um arquivo?', 'Um cabo', FALSE, 2),
      ('O que é um arquivo?', 'Uma peça física do computador', FALSE, 3),
      ('Qual destes é um exemplo de arquivo?', 'Teclado', FALSE, 0),
      ('Qual destes é um exemplo de arquivo?', 'Processador', FALSE, 1),
      ('Qual destes é um exemplo de arquivo?', 'Fotografia digital', TRUE, 2),
      ('Qual destes é um exemplo de arquivo?', 'Monitor', FALSE, 3),
      ('O que é uma pasta no computador?', 'Local usado para organizar arquivos', TRUE, 0),
      ('O que é uma pasta no computador?', 'Uma rede social', FALSE, 1),
      ('O que é uma pasta no computador?', 'Um vírus', FALSE, 2),
      ('O que é uma pasta no computador?', 'Um navegador', FALSE, 3),
      ('O que é memória de armazenamento?', 'Velocidade do teclado', FALSE, 0),
      ('O que é memória de armazenamento?', 'Qualidade da câmera', FALSE, 1),
      ('O que é memória de armazenamento?', 'Tamanho do monitor', FALSE, 2),
      ('O que é memória de armazenamento?', 'Espaço usado para guardar dados e arquivos', TRUE, 3),
      ('Qual destes é um dispositivo de armazenamento?', 'Microfone', FALSE, 0),
      ('Qual destes é um dispositivo de armazenamento?', 'Pen drive', TRUE, 1),
      ('Qual destes é um dispositivo de armazenamento?', 'Coluna', FALSE, 2),
      ('Qual destes é um dispositivo de armazenamento?', 'Mouse', FALSE, 3),
      ('Para que serve um pen drive?', 'Criar internet', FALSE, 0),
      ('Para que serve um pen drive?', 'Aumentar o brilho da tela', FALSE, 1),
      ('Para que serve um pen drive?', 'Guardar e transportar arquivos digitais', TRUE, 2),
      ('Para que serve um pen drive?', 'Fazer chamadas telefônicas', FALSE, 3),
      ('O que é uma fotografia digital?', 'Imagem somente impressa', FALSE, 0),
      ('O que é uma fotografia digital?', 'Um cabo', FALSE, 1),
      ('O que é uma fotografia digital?', 'Tipo de aplicativo', FALSE, 2),
      ('O que é uma fotografia digital?', 'Imagem armazenada em formato eletrônico', TRUE, 3),
      ('O que é vídeo digital?', 'Um documento de texto', FALSE, 0),
      ('O que é vídeo digital?', 'Um programa antivírus', FALSE, 1),
      ('O que é vídeo digital?', 'Apenas uma fotografia', FALSE, 2),
      ('O que é vídeo digital?', 'Sequência de imagens armazenadas em formato eletrônico', TRUE, 3),
      ('O que é email?', 'Tipo de memória', FALSE, 0),
      ('O que é email?', 'Cabo de rede', FALSE, 1),
      ('O que é email?', 'Serviço utilizado para enviar e receber mensagens eletrônicas', TRUE, 2),
      ('O que é email?', 'Sistema operacional', FALSE, 3),
      ('Qual destes é um serviço de email?', 'HDMI', FALSE, 0),
      ('Qual destes é um serviço de email?', 'Windows', FALSE, 1),
      ('Qual destes é um serviço de email?', 'Gmail', TRUE, 2),
      ('Qual destes é um serviço de email?', 'Bluetooth', FALSE, 3),
      ('O que é uma mensagem instantânea?', 'Documento físico', FALSE, 0),
      ('O que é uma mensagem instantânea?', 'Comunicação enviada e recebida rapidamente através de aplicativos', TRUE, 1),
      ('O que é uma mensagem instantânea?', 'Arquivo de sistema', FALSE, 2),
      ('O que é uma mensagem instantânea?', 'Tipo de computador', FALSE, 3),
      ('Qual aplicativo é conhecido por mensagens instantâneas?', 'BIOS', FALSE, 0),
      ('Qual aplicativo é conhecido por mensagens instantâneas?', 'WhatsApp', TRUE, 1),
      ('Qual aplicativo é conhecido por mensagens instantâneas?', 'Photoshop', FALSE, 2),
      ('Qual aplicativo é conhecido por mensagens instantâneas?', 'Excel', FALSE, 3),
      ('O que é uma chamada de vídeo?', 'Tipo de memória', FALSE, 0),
      ('O que é uma chamada de vídeo?', 'Programa antivírus', FALSE, 1),
      ('O que é uma chamada de vídeo?', 'Arquivo de texto', FALSE, 2),
      ('O que é uma chamada de vídeo?', 'Conversa que transmite áudio e imagem pela internet', TRUE, 3),
      ('O que é inteligência artificial?', 'Um cabo de computador', FALSE, 0),
      ('O que é inteligência artificial?', 'Um tipo de bateria', FALSE, 1),
      ('O que é inteligência artificial?', 'Uma impressora', FALSE, 2),
      ('O que é inteligência artificial?', 'Tecnologia que permite sistemas realizarem tarefas que simulam capacidades humanas', TRUE, 3),
      ('Qual é um exemplo de inteligência artificial?', 'Teclado físico', FALSE, 0),
      ('Qual é um exemplo de inteligência artificial?', 'Cabo USB', FALSE, 1),
      ('Qual é um exemplo de inteligência artificial?', 'Assistentes virtuais e sistemas de recomendação', TRUE, 2),
      ('Qual é um exemplo de inteligência artificial?', 'Monitor desligado', FALSE, 3),
      ('O que é uma atualização de aplicativo?', 'Apagar todos os dados', FALSE, 0),
      ('O que é uma atualização de aplicativo?', 'Desligar o telefone', FALSE, 1),
      ('O que é uma atualização de aplicativo?', 'Nova versão criada para melhorar ou corrigir um aplicativo', TRUE, 2),
      ('O que é uma atualização de aplicativo?', 'Remover a internet', FALSE, 3),
      ('Por que atualizar aplicativos?', 'Para reduzir funcionalidades sempre', FALSE, 0),
      ('Por que atualizar aplicativos?', 'Para danificar o dispositivo', FALSE, 1),
      ('Por que atualizar aplicativos?', 'Para apagar arquivos', FALSE, 2),
      ('Por que atualizar aplicativos?', 'Para receber melhorias e correções de segurança', TRUE, 3),
      ('O que é um vírus de computador?', 'Uma atualização', FALSE, 0),
      ('O que é um vírus de computador?', 'Programa malicioso que pode causar danos ou roubar informações', TRUE, 1),
      ('O que é um vírus de computador?', 'Um navegador', FALSE, 2),
      ('O que é um vírus de computador?', 'Um aplicativo comum', FALSE, 3),
      ('O que é antivírus?', 'Tipo de teclado', FALSE, 0),
      ('O que é antivírus?', 'Sistema operacional', FALSE, 1),
      ('O que é antivírus?', 'Programa para criar vírus', FALSE, 2),
      ('O que é antivírus?', 'Programa usado para ajudar a detectar e remover ameaças digitais', TRUE, 3),
      ('O que é backup?', 'Bloqueio da internet', FALSE, 0),
      ('O que é backup?', 'Formatação do computador', FALSE, 1),
      ('O que é backup?', 'Exclusão de arquivos', FALSE, 2),
      ('O que é backup?', 'Cópia de segurança de informações importantes', TRUE, 3),
      ('Por que fazer backup?', 'Para recuperar dados em caso de perda ou problema', TRUE, 0),
      ('Por que fazer backup?', 'Para criar vírus', FALSE, 1),
      ('Por que fazer backup?', 'Para aumentar o tamanho da tela', FALSE, 2),
      ('Por que fazer backup?', 'Para desligar o computador', FALSE, 3),
      ('O que é nuvem (cloud)?', 'Um cabo de energia', FALSE, 0),
      ('O que é nuvem (cloud)?', 'Um teclado', FALSE, 1),
      ('O que é nuvem (cloud)?', 'Serviço que permite armazenar e acessar dados pela internet', TRUE, 2),
      ('O que é nuvem (cloud)?', 'Um antivírus físico', FALSE, 3),
      ('Qual é um exemplo de armazenamento em nuvem?', 'Monitor', FALSE, 0),
      ('Qual é um exemplo de armazenamento em nuvem?', 'Mouse', FALSE, 1),
      ('Qual é um exemplo de armazenamento em nuvem?', 'Google Drive', TRUE, 2),
      ('Qual é um exemplo de armazenamento em nuvem?', 'Processador', FALSE, 3),
      ('O que é Bluetooth?', 'Tecnologia para comunicação sem fio entre dispositivos próximos', TRUE, 0),
      ('O que é Bluetooth?', 'Sistema operacional', FALSE, 1),
      ('O que é Bluetooth?', 'Navegador', FALSE, 2),
      ('O que é Bluetooth?', 'Memória interna', FALSE, 3),
      ('O que é GPS?', 'Programa antivírus', FALSE, 0),
      ('O que é GPS?', 'Tipo de arquivo', FALSE, 1),
      ('O que é GPS?', 'Sistema usado para localização e navegação', TRUE, 2),
      ('O que é GPS?', 'Sistema de armazenamento', FALSE, 3),
      ('O que é QR Code?', 'Código que pode ser lido por dispositivos para acessar informações', TRUE, 0),
      ('O que é QR Code?', 'Um vírus', FALSE, 1),
      ('O que é QR Code?', 'Uma senha', FALSE, 2),
      ('O que é QR Code?', 'Um processador', FALSE, 3),
      ('O que é uma rede social?', 'Plataforma onde pessoas compartilham conteúdos e interagem', TRUE, 0),
      ('O que é uma rede social?', 'Um cabo', FALSE, 1),
      ('O que é uma rede social?', 'Um componente do computador', FALSE, 2),
      ('O que é uma rede social?', 'Um sistema operacional', FALSE, 3),
      ('Qual destes é uma rede social?', 'Excel', FALSE, 0),
      ('Qual destes é uma rede social?', 'Instagram', TRUE, 1),
      ('Qual destes é uma rede social?', 'Windows', FALSE, 2),
      ('Qual destes é uma rede social?', 'Android', FALSE, 3),
      ('O que é download?', 'Apagar arquivos', FALSE, 0),
      ('O que é download?', 'Baixar arquivos da internet para um dispositivo', TRUE, 1),
      ('O que é download?', 'Enviar arquivos', FALSE, 2),
      ('O que é download?', 'Desligar internet', FALSE, 3),
      ('O que é upload?', 'Apagar arquivos', FALSE, 0),
      ('O que é upload?', 'Enviar arquivos de um dispositivo para um serviço online', TRUE, 1),
      ('O que é upload?', 'Desligar o computador', FALSE, 2),
      ('O que é upload?', 'Criar uma senha', FALSE, 3),
      ('O que é segurança digital?', 'Proteção de dispositivos, dados e informações contra ameaças', TRUE, 0),
      ('O que é segurança digital?', 'Melhorar imagens', FALSE, 1),
      ('O que é segurança digital?', 'Aumentar volume do computador', FALSE, 2),
      ('O que é segurança digital?', 'Apenas criar aplicativos', FALSE, 3),
      ('Qual atitude aumenta a segurança online?', 'Usar senhas fortes e evitar links suspeitos', TRUE, 0),
      ('Qual atitude aumenta a segurança online?', 'Instalar qualquer programa', FALSE, 1),
      ('Qual atitude aumenta a segurança online?', 'Compartilhar senhas', FALSE, 2),
      ('Qual atitude aumenta a segurança online?', 'Abrir qualquer mensagem', FALSE, 3),
      ('Por que a tecnologia é importante atualmente?', 'Porque funciona sem energia', FALSE, 0),
      ('Por que a tecnologia é importante atualmente?', 'Porque elimina todas as atividades humanas', FALSE, 1),
      ('Por que a tecnologia é importante atualmente?', 'Porque substitui todas as pessoas', FALSE, 2),
      ('Por que a tecnologia é importante atualmente?', 'Porque facilita comunicação, trabalho, aprendizagem e acesso à informação', TRUE, 3)
    ) AS a(statement, label, is_correct, display_order)
    ON q.statement = a.statement;

    DROP TABLE tmp_new_questions_tec_facil;

    RAISE NOTICE '50 perguntas de Tecnologia (fácil) inseridas com sucesso.';
  END IF;
END $$;

COMMIT;
