-- Migration/seed: conteúdo Produtividade, nível Difícil — lote 2 (75 perguntas)
-- Fonte: novo lote de 76 perguntas de Produtividade/Difícil fornecido pelo
-- proprietário do projeto. A pergunta 76 (última) veio cortada no documento
-- (a alternativa B termina em "propor m") e NÃO foi inserida, para evitar
-- conteúdo incompleto. As 75 perguntas 1-75, completas, foram inseridas
-- aqui.
--
-- Verificado: nenhuma das 75 perguntas colide (mesmo enunciado) com as 1073
-- perguntas já existentes no banco.
--
-- CORREÇÃO DE QUALIDADE APLICADA (mesma higiene de dado dos lotes
-- anteriores): este lote já vem com respostas variadas entre A/B/C (42% A,
-- 41% B, 2 C). Para manter consistência com o resto do banco, a posição da
-- alternativa correta (preservando o texto correto do documento original)
-- foi redistribuída por pergunta com seed fixa (86 — distinta das seeds 42
-- a 85 já usadas) e distribuição controlada entre A/B/C/D. Conteúdo
-- pedagógico inalterado, só a ORDEM de exibição mudou.
--
-- Idempotente: usa a coluna `source` (migration 022) como marcador — rodar
-- este arquivo mais de uma vez não duplica as perguntas.

BEGIN;

DO $$
DECLARE
  v_category_id UUID;
BEGIN
  SELECT id INTO v_category_id FROM categories WHERE slug = 'produtividade';
  IF v_category_id IS NULL THEN
    RAISE EXCEPTION 'Categoria "produtividade" não encontrada — rode a migration 021 primeiro.';
  END IF;

  IF EXISTS (SELECT 1 FROM questions WHERE source = 'seed_produtividade_dificil_v2') THEN
    RAISE NOTICE 'Perguntas já foram inseridas anteriormente (source=seed_produtividade_dificil_v2) — nada a fazer.';
  ELSE

    CREATE TEMP TABLE tmp_new_questions_prod_dificil_v2 AS
    WITH inserted AS (
    INSERT INTO questions (category_id, difficulty, statement, time_limit_seconds, xp_reward, source)
    SELECT v_category_id, 'hard', v.statement, 15, 10, 'seed_produtividade_dificil_v2'
    FROM (VALUES
      ('Uma equipa possui 20 tarefas, mas apenas cinco contribuem diretamente para o objetivo principal do projeto. Qual abordagem é mais adequada?'),
      ('Um profissional planeia 8 horas de trabalho com tarefas que somam exatamente 8 horas, sem considerar interrupções ou imprevistos. Qual é o principal problema?'),
      ('Uma tarefa importante tem prazo para amanhã, enquanto várias tarefas menores não possuem prazo definido. Qual princípio deve orientar a decisão?'),
      ('Um gestor percebe que a equipa passa grande parte do dia respondendo mensagens, enquanto atividades estratégicas ficam atrasadas. Qual intervenção tende a ser mais eficiente?'),
      ('Uma pessoa trabalha oito horas, mas passa frequentemente de uma aplicação para outra. Qual indicador seria mais útil para diagnosticar o problema?'),
      ('Um projeto está atrasado porque uma única pessoa precisa aprovar todas as etapas. Qual conceito descreve melhor essa situação?'),
      ('Para eliminar um gargalo, uma equipa simplesmente adiciona mais tarefas à etapa já sobrecarregada. Qual é o problema dessa estratégia?'),
      ('Uma empresa quer descobrir por que um processo demora muito. Qual abordagem é mais adequada?'),
      ('Um funcionário termina 30 tarefas de baixa importância enquanto deixa duas tarefas críticas pendentes. O que isso demonstra?'),
      ('Qual combinação representa melhor produtividade sustentável?'),
      ('Uma tarefa apresenta grande impacto, mas não é urgente. Outra é urgente, mas possui pouco impacto. Qual abordagem evita uma decisão simplista?'),
      ('Um profissional possui energia elevada pela manhã e baixa concentração no final do dia. Como pode adaptar o planejamento?'),
      ('O que significa alinhar tarefas com níveis de energia?'),
      ('Uma equipa mede produtividade apenas pelo número de tarefas concluídas. Qual limitação existe?'),
      ('Qual indicador seria mais completo para avaliar a execução de um projeto?'),
      ('Um projeto possui prazo fixo e várias atividades dependentes umas das outras. Qual ferramenta pode ajudar a visualizar a sequência temporal?'),
      ('Se a tarefa B só pode começar depois que A termina, existe uma:'),
      ('Uma tarefa crítica depende de outra que frequentemente atrasa. Qual é o primeiro passo mais adequado?'),
      ('Uma equipa possui muitas tarefas classificadas como "urgentes". Qual problema isso pode indicar?'),
      ('Se tudo é considerado prioridade, qual é a consequência mais provável?'),
      ('Uma pessoa estabelece uma meta de "trabalhar mais". Por que essa meta é fraca?'),
      ('Qual característica torna uma meta mais mensurável?'),
      ('Um profissional quer reduzir o tempo gasto numa atividade repetitiva. Qual sequência é mais racional?'),
      ('Por que automatizar um processo mal estruturado pode ser problemático?'),
      ('Uma equipa automatizou uma tarefa, mas agora erros são replicados em grande escala. Qual princípio foi negligenciado?'),
      ('Qual situação representa melhor uma melhoria de processo?'),
      ('Uma equipa realiza uma reunião semanal de duas horas, mas grande parte dos participantes não precisa participar de todos os assuntos. Qual melhoria é mais adequada?'),
      ('Uma reunião termina sem decisões, responsáveis ou prazos. Qual é uma das principais falhas?'),
      ('Qual elemento transforma uma decisão de reunião em uma ação acompanhável?'),
      ('Uma pessoa recebe uma tarefa vaga: "Melhorar o relatório". Qual pergunta ajudaria a transformar a tarefa em algo executável?'),
      ('O que é ambiguidade de tarefa?'),
      ('Uma tarefa continua sendo refeita porque o responsável recebe instruções diferentes de várias pessoas. Qual problema existe?'),
      ('Qual é uma vantagem de definir um "responsável final" por uma atividade?'),
      ('Uma equipa começa novos projetos continuamente sem terminar os anteriores. Qual problema de gestão pode estar presente?'),
      ('Reduzir o número de tarefas iniciadas simultaneamente pode melhorar o fluxo porque:'),
      ('Um funcionário inicia cinco tarefas e termina nenhuma. Qual métrica pode ajudar a identificar esse padrão?'),
      ('O que significa limitar o trabalho em andamento?'),
      ('Uma equipa mantém dez tarefas abertas porque "talvez sejam necessárias", embora apenas três sejam relevantes. Qual ação é mais produtiva?'),
      ('Um profissional planeia uma tarefa para duas horas, mas ela geralmente leva quatro. O que deve fazer antes de alterar todo o calendário?'),
      ('Por que registar o tempo real de execução pode melhorar o planejamento futuro?'),
      ('Uma pessoa sempre subestima pequenas tarefas que, somadas, ocupam várias horas. Qual conceito explica melhor o problema?'),
      ('Qual estratégia ajuda a revelar atividades que consomem tempo sem contribuir muito para os objetivos?'),
      ('Uma pessoa passa duas horas por dia em atividades administrativas que poderiam ser automatizadas. Qual análise deve ser feita primeiro?'),
      ('Qual é o risco de otimizar uma tarefa isoladamente sem analisar o processo completo?'),
      ('Uma equipa reduz o tempo de produção de um produto, mas aumenta o tempo de espera antes da entrega. Qual conclusão é mais adequada?'),
      ('O que caracteriza uma otimização local?'),
      ('Uma equipa utiliza uma ferramenta sofisticada, mas ninguém sabe claramente quais são as prioridades. Qual conclusão é mais razoável?'),
      ('Qual princípio deve orientar a escolha de uma ferramenta de produtividade?'),
      ('Uma equipa utiliza três aplicações diferentes para armazenar a mesma informação. Qual risco aumenta?'),
      ('O que significa centralizar informações relevantes?'),
      ('Uma pessoa tem um objetivo para seis meses, mas nunca verifica seu progresso. Qual problema existe?'),
      ('Qual frequência de revisão é mais adequada para uma meta de longo prazo?'),
      ('Uma meta está atrasada porque as condições externas mudaram significativamente. Qual comportamento demonstra boa gestão?'),
      ('O que é uma premissa de planejamento?'),
      ('Por que rever premissas pode ser importante?'),
      ('Uma equipa estabelece um prazo sem considerar a duração das dependências anteriores. Qual falha ocorreu?'),
      ('O que significa identificar o caminho crítico de um projeto?'),
      ('Se uma atividade do caminho crítico atrasar e não houver margem, o que pode acontecer?'),
      ('Qual é a finalidade de uma retrospectiva de projeto?'),
      ('Uma retrospectiva identifica que reuniões longas foram responsáveis por atrasos recorrentes. Qual seria uma resposta baseada em evidências?'),
      ('Por que testar uma melhoria antes de aplicá-la em toda a organização pode ser útil?'),
      ('Uma equipa implementa uma nova rotina e, após um mês, verifica que o desempenho piorou. Qual atitude é mais adequada?'),
      ('O que caracteriza uma cultura de melhoria contínua?'),
      ('Uma pessoa trabalha melhor quando possui um objetivo claramente definido, mas recebe tarefas inesperadas constantemente. Qual solução pode equilibrar flexibilidade e foco?'),
      ('Qual é a principal função de uma margem de capacidade no planejamento?'),
      ('Uma equipa está sempre ocupada, mas os resultados estratégicos não melhoram. Qual diagnóstico deve ser considerado primeiro?'),
      ('Qual pergunta melhor ajuda a identificar atividades de baixo valor?'),
      ('Uma pessoa continua executando manualmente uma tarefa porque "sempre foi assim". Qual princípio de produtividade deve ser aplicado?'),
      ('Qual situação representa desperdício de capacidade?'),
      ('Uma organização possui excelentes planos, mas baixa execução. Qual fator pode explicar essa diferença?'),
      ('O que transforma um plano em um sistema de execução mais robusto?'),
      ('Uma pessoa termina uma tarefa e imediatamente começa outra sem verificar se o resultado atende aos critérios definidos. Qual risco aumenta?'),
      ('Qual etapa deve ocorrer antes de considerar uma entrega concluída em um processo que exige qualidade?'),
      ('Um projeto apresenta muitas revisões porque os requisitos mudam constantemente. Qual medida pode reduzir retrabalho?'),
      ('Qual é uma consequência direta de requisitos pouco claros?')
    ) AS v(statement)
    RETURNING id, statement
    )
    SELECT * FROM inserted;

    INSERT INTO question_alternatives (question_id, label, is_correct, display_order)
    SELECT q.id, a.label, a.is_correct, a.display_order
    FROM tmp_new_questions_prod_dificil_v2 q
    JOIN (VALUES
      ('Uma equipa possui 20 tarefas, mas apenas cinco contribuem diretamente para o objetivo principal do projeto. Qual abordagem é mais adequada?', 'Delegar todas as tarefas simultaneamente', FALSE, 0),
      ('Uma equipa possui 20 tarefas, mas apenas cinco contribuem diretamente para o objetivo principal do projeto. Qual abordagem é mais adequada?', 'Distribuir o tempo igualmente pelas 20 tarefas', FALSE, 1),
      ('Uma equipa possui 20 tarefas, mas apenas cinco contribuem diretamente para o objetivo principal do projeto. Qual abordagem é mais adequada?', 'Executar primeiro as cinco de maior contribuição', TRUE, 2),
      ('Uma equipa possui 20 tarefas, mas apenas cinco contribuem diretamente para o objetivo principal do projeto. Qual abordagem é mais adequada?', 'Começar pelas tarefas mais rápidas', FALSE, 3),
      ('Um profissional planeia 8 horas de trabalho com tarefas que somam exatamente 8 horas, sem considerar interrupções ou imprevistos. Qual é o principal problema?', 'O plano não possui margem de segurança', TRUE, 0),
      ('Um profissional planeia 8 horas de trabalho com tarefas que somam exatamente 8 horas, sem considerar interrupções ou imprevistos. Qual é o principal problema?', 'O profissional possui demasiado tempo livre', FALSE, 1),
      ('Um profissional planeia 8 horas de trabalho com tarefas que somam exatamente 8 horas, sem considerar interrupções ou imprevistos. Qual é o principal problema?', 'O plano possui demasiadas prioridades', FALSE, 2),
      ('Um profissional planeia 8 horas de trabalho com tarefas que somam exatamente 8 horas, sem considerar interrupções ou imprevistos. Qual é o principal problema?', 'As tarefas são necessariamente pequenas', FALSE, 3),
      ('Uma tarefa importante tem prazo para amanhã, enquanto várias tarefas menores não possuem prazo definido. Qual princípio deve orientar a decisão?', 'Priorizar sempre a tarefa mais curta', FALSE, 0),
      ('Uma tarefa importante tem prazo para amanhã, enquanto várias tarefas menores não possuem prazo definido. Qual princípio deve orientar a decisão?', 'Considerar urgência e importância', TRUE, 1),
      ('Uma tarefa importante tem prazo para amanhã, enquanto várias tarefas menores não possuem prazo definido. Qual princípio deve orientar a decisão?', 'Escolher a tarefa mais agradável', FALSE, 2),
      ('Uma tarefa importante tem prazo para amanhã, enquanto várias tarefas menores não possuem prazo definido. Qual princípio deve orientar a decisão?', 'Trabalhar exclusivamente nas tarefas menores', FALSE, 3),
      ('Um gestor percebe que a equipa passa grande parte do dia respondendo mensagens, enquanto atividades estratégicas ficam atrasadas. Qual intervenção tende a ser mais eficiente?', 'Criar períodos específicos para comunicação', TRUE, 0),
      ('Um gestor percebe que a equipa passa grande parte do dia respondendo mensagens, enquanto atividades estratégicas ficam atrasadas. Qual intervenção tende a ser mais eficiente?', 'Adicionar mais reuniões', FALSE, 1),
      ('Um gestor percebe que a equipa passa grande parte do dia respondendo mensagens, enquanto atividades estratégicas ficam atrasadas. Qual intervenção tende a ser mais eficiente?', 'Eliminar todas as mensagens', FALSE, 2),
      ('Um gestor percebe que a equipa passa grande parte do dia respondendo mensagens, enquanto atividades estratégicas ficam atrasadas. Qual intervenção tende a ser mais eficiente?', 'Aumentar a frequência de verificação das mensagens', FALSE, 3),
      ('Uma pessoa trabalha oito horas, mas passa frequentemente de uma aplicação para outra. Qual indicador seria mais útil para diagnosticar o problema?', 'Número de aplicações instaladas', FALSE, 0),
      ('Uma pessoa trabalha oito horas, mas passa frequentemente de uma aplicação para outra. Qual indicador seria mais útil para diagnosticar o problema?', 'Tamanho do monitor', FALSE, 1),
      ('Uma pessoa trabalha oito horas, mas passa frequentemente de uma aplicação para outra. Qual indicador seria mais útil para diagnosticar o problema?', 'Frequência das mudanças de contexto', TRUE, 2),
      ('Uma pessoa trabalha oito horas, mas passa frequentemente de uma aplicação para outra. Qual indicador seria mais útil para diagnosticar o problema?', 'Número de ficheiros armazenados', FALSE, 3),
      ('Um projeto está atrasado porque uma única pessoa precisa aprovar todas as etapas. Qual conceito descreve melhor essa situação?', 'Planeamento reverso', FALSE, 0),
      ('Um projeto está atrasado porque uma única pessoa precisa aprovar todas as etapas. Qual conceito descreve melhor essa situação?', 'Gargalo', TRUE, 1),
      ('Um projeto está atrasado porque uma única pessoa precisa aprovar todas as etapas. Qual conceito descreve melhor essa situação?', 'Delegação excessiva', FALSE, 2),
      ('Um projeto está atrasado porque uma única pessoa precisa aprovar todas as etapas. Qual conceito descreve melhor essa situação?', 'Pausa produtiva', FALSE, 3),
      ('Para eliminar um gargalo, uma equipa simplesmente adiciona mais tarefas à etapa já sobrecarregada. Qual é o problema dessa estratégia?', 'Pode agravar a limitação existente', TRUE, 0),
      ('Para eliminar um gargalo, uma equipa simplesmente adiciona mais tarefas à etapa já sobrecarregada. Qual é o problema dessa estratégia?', 'Aumenta a capacidade da etapa', FALSE, 1),
      ('Para eliminar um gargalo, uma equipa simplesmente adiciona mais tarefas à etapa já sobrecarregada. Qual é o problema dessa estratégia?', 'Reduz automaticamente o tempo de execução', FALSE, 2),
      ('Para eliminar um gargalo, uma equipa simplesmente adiciona mais tarefas à etapa já sobrecarregada. Qual é o problema dessa estratégia?', 'Elimina a dependência', FALSE, 3),
      ('Uma empresa quer descobrir por que um processo demora muito. Qual abordagem é mais adequada?', 'Aumentar todos os prazos', FALSE, 0),
      ('Uma empresa quer descobrir por que um processo demora muito. Qual abordagem é mais adequada?', 'Medir apenas o número de funcionários', FALSE, 1),
      ('Uma empresa quer descobrir por que um processo demora muito. Qual abordagem é mais adequada?', 'Mapear as etapas e identificar onde ocorre maior espera', TRUE, 2),
      ('Uma empresa quer descobrir por que um processo demora muito. Qual abordagem é mais adequada?', 'Eliminar os indicadores', FALSE, 3),
      ('Um funcionário termina 30 tarefas de baixa importância enquanto deixa duas tarefas críticas pendentes. O que isso demonstra?', 'Falha de priorização', TRUE, 0),
      ('Um funcionário termina 30 tarefas de baixa importância enquanto deixa duas tarefas críticas pendentes. O que isso demonstra?', 'Planeamento reverso correto', FALSE, 1),
      ('Um funcionário termina 30 tarefas de baixa importância enquanto deixa duas tarefas críticas pendentes. O que isso demonstra?', 'Alta produtividade necessariamente', FALSE, 2),
      ('Um funcionário termina 30 tarefas de baixa importância enquanto deixa duas tarefas críticas pendentes. O que isso demonstra?', 'Excelente gestão de energia', FALSE, 3),
      ('Qual combinação representa melhor produtividade sustentável?', 'Resultados relevantes com uso eficiente dos recursos', TRUE, 0),
      ('Qual combinação representa melhor produtividade sustentável?', 'Alta velocidade sem qualidade', FALSE, 1),
      ('Qual combinação representa melhor produtividade sustentável?', 'Alta ocupação sem resultados', FALSE, 2),
      ('Qual combinação representa melhor produtividade sustentável?', 'Trabalho contínuo sem descanso', FALSE, 3),
      ('Uma tarefa apresenta grande impacto, mas não é urgente. Outra é urgente, mas possui pouco impacto. Qual abordagem evita uma decisão simplista?', 'Avaliar impacto e urgência em conjunto', TRUE, 0),
      ('Uma tarefa apresenta grande impacto, mas não é urgente. Outra é urgente, mas possui pouco impacto. Qual abordagem evita uma decisão simplista?', 'Escolher sempre a urgente', FALSE, 1),
      ('Uma tarefa apresenta grande impacto, mas não é urgente. Outra é urgente, mas possui pouco impacto. Qual abordagem evita uma decisão simplista?', 'Avaliar apenas o prazo', FALSE, 2),
      ('Uma tarefa apresenta grande impacto, mas não é urgente. Outra é urgente, mas possui pouco impacto. Qual abordagem evita uma decisão simplista?', 'Escolher sempre a importante', FALSE, 3),
      ('Um profissional possui energia elevada pela manhã e baixa concentração no final do dia. Como pode adaptar o planejamento?', 'Fazer todas as tarefas difíceis à noite', FALSE, 0),
      ('Um profissional possui energia elevada pela manhã e baixa concentração no final do dia. Como pode adaptar o planejamento?', 'Colocar tarefas cognitivamente exigentes no período de maior energia', TRUE, 1),
      ('Um profissional possui energia elevada pela manhã e baixa concentração no final do dia. Como pode adaptar o planejamento?', 'Evitar qualquer horário definido', FALSE, 2),
      ('Um profissional possui energia elevada pela manhã e baixa concentração no final do dia. Como pode adaptar o planejamento?', 'Distribuir todas as tarefas aleatoriamente', FALSE, 3),
      ('O que significa alinhar tarefas com níveis de energia?', 'Eliminar tarefas difíceis', FALSE, 0),
      ('O que significa alinhar tarefas com níveis de energia?', 'Trabalhar apenas quando houver motivação', FALSE, 1),
      ('O que significa alinhar tarefas com níveis de energia?', 'Executar todas as tarefas no mesmo horário', FALSE, 2),
      ('O que significa alinhar tarefas com níveis de energia?', 'Relacionar tipos de atividade aos períodos de maior capacidade de desempenho', TRUE, 3),
      ('Uma equipa mede produtividade apenas pelo número de tarefas concluídas. Qual limitação existe?', 'Mede demasiados fatores', FALSE, 0),
      ('Uma equipa mede produtividade apenas pelo número de tarefas concluídas. Qual limitação existe?', 'Avalia necessariamente resultados estratégicos', FALSE, 1),
      ('Uma equipa mede produtividade apenas pelo número de tarefas concluídas. Qual limitação existe?', 'Não considera qualidade nem impacto', TRUE, 2),
      ('Uma equipa mede produtividade apenas pelo número de tarefas concluídas. Qual limitação existe?', 'Elimina qualquer comparação', FALSE, 3),
      ('Qual indicador seria mais completo para avaliar a execução de um projeto?', 'Quantidade de mensagens enviadas', FALSE, 0),
      ('Qual indicador seria mais completo para avaliar a execução de um projeto?', 'Resultados alcançados em relação aos objetivos e recursos utilizados', TRUE, 1),
      ('Qual indicador seria mais completo para avaliar a execução de um projeto?', 'Número de horas trabalhadas', FALSE, 2),
      ('Qual indicador seria mais completo para avaliar a execução de um projeto?', 'Número de tarefas realizadas', FALSE, 3),
      ('Um projeto possui prazo fixo e várias atividades dependentes umas das outras. Qual ferramenta pode ajudar a visualizar a sequência temporal?', 'Lista de contactos', FALSE, 0),
      ('Um projeto possui prazo fixo e várias atividades dependentes umas das outras. Qual ferramenta pode ajudar a visualizar a sequência temporal?', 'Caixa de entrada', FALSE, 1),
      ('Um projeto possui prazo fixo e várias atividades dependentes umas das outras. Qual ferramenta pode ajudar a visualizar a sequência temporal?', 'Galeria', FALSE, 2),
      ('Um projeto possui prazo fixo e várias atividades dependentes umas das outras. Qual ferramenta pode ajudar a visualizar a sequência temporal?', 'Cronograma', TRUE, 3),
      ('Se a tarefa B só pode começar depois que A termina, existe uma:', 'Pausa', FALSE, 0),
      ('Se a tarefa B só pode começar depois que A termina, existe uma:', 'Automação', FALSE, 1),
      ('Se a tarefa B só pode começar depois que A termina, existe uma:', 'Interrupção', FALSE, 2),
      ('Se a tarefa B só pode começar depois que A termina, existe uma:', 'Dependência', TRUE, 3),
      ('Uma tarefa crítica depende de outra que frequentemente atrasa. Qual é o primeiro passo mais adequado?', 'Identificar e gerir a dependência crítica', TRUE, 0),
      ('Uma tarefa crítica depende de outra que frequentemente atrasa. Qual é o primeiro passo mais adequado?', 'Ignorar a dependência', FALSE, 1),
      ('Uma tarefa crítica depende de outra que frequentemente atrasa. Qual é o primeiro passo mais adequado?', 'Eliminar o prazo', FALSE, 2),
      ('Uma tarefa crítica depende de outra que frequentemente atrasa. Qual é o primeiro passo mais adequado?', 'Adicionar tarefas paralelas sem análise', FALSE, 3),
      ('Uma equipa possui muitas tarefas classificadas como "urgentes". Qual problema isso pode indicar?', 'Automação perfeita', FALSE, 0),
      ('Uma equipa possui muitas tarefas classificadas como "urgentes". Qual problema isso pode indicar?', 'Falta de critérios claros de prioridade', TRUE, 1),
      ('Uma equipa possui muitas tarefas classificadas como "urgentes". Qual problema isso pode indicar?', 'Excelente priorização', FALSE, 2),
      ('Uma equipa possui muitas tarefas classificadas como "urgentes". Qual problema isso pode indicar?', 'Excesso de tempo disponível', FALSE, 3),
      ('Se tudo é considerado prioridade, qual é a consequência mais provável?', 'A distinção entre prioridades desaparece', TRUE, 0),
      ('Se tudo é considerado prioridade, qual é a consequência mais provável?', 'O trabalho torna-se automaticamente mais rápido', FALSE, 1),
      ('Se tudo é considerado prioridade, qual é a consequência mais provável?', 'Os prazos deixam de existir', FALSE, 2),
      ('Se tudo é considerado prioridade, qual é a consequência mais provável?', 'Todas as tarefas recebem atenção máxima', FALSE, 3),
      ('Uma pessoa estabelece uma meta de "trabalhar mais". Por que essa meta é fraca?', 'Porque possui métricas demais', FALSE, 0),
      ('Uma pessoa estabelece uma meta de "trabalhar mais". Por que essa meta é fraca?', 'Porque não define claramente o resultado desejado', TRUE, 1),
      ('Uma pessoa estabelece uma meta de "trabalhar mais". Por que essa meta é fraca?', 'Porque possui prazo curto', FALSE, 2),
      ('Uma pessoa estabelece uma meta de "trabalhar mais". Por que essa meta é fraca?', 'Porque é demasiado específica', FALSE, 3),
      ('Qual característica torna uma meta mais mensurável?', 'Eliminar prazos', FALSE, 0),
      ('Qual característica torna uma meta mais mensurável?', 'Utilizar apenas palavras genéricas', FALSE, 1),
      ('Qual característica torna uma meta mais mensurável?', 'Definir um resultado que possa ser verificado', TRUE, 2),
      ('Qual característica torna uma meta mais mensurável?', 'Evitar números', FALSE, 3),
      ('Um profissional quer reduzir o tempo gasto numa atividade repetitiva. Qual sequência é mais racional?', 'Ignorar o processo', FALSE, 0),
      ('Um profissional quer reduzir o tempo gasto numa atividade repetitiva. Qual sequência é mais racional?', 'Automatizar imediatamente sem analisar', FALSE, 1),
      ('Um profissional quer reduzir o tempo gasto numa atividade repetitiva. Qual sequência é mais racional?', 'Medir o processo, identificar desperdícios e depois automatizar quando apropriado', TRUE, 2),
      ('Um profissional quer reduzir o tempo gasto numa atividade repetitiva. Qual sequência é mais racional?', 'Adicionar etapas manuais', FALSE, 3),
      ('Por que automatizar um processo mal estruturado pode ser problemático?', 'Sempre elimina erros', FALSE, 0),
      ('Por que automatizar um processo mal estruturado pode ser problemático?', 'Impede qualquer repetição', FALSE, 1),
      ('Por que automatizar um processo mal estruturado pode ser problemático?', 'Pode tornar um processo ineficiente mais rápido sem resolver sua causa', TRUE, 2),
      ('Por que automatizar um processo mal estruturado pode ser problemático?', 'Sempre reduz custos', FALSE, 3),
      ('Uma equipa automatizou uma tarefa, mas agora erros são replicados em grande escala. Qual princípio foi negligenciado?', 'Aumentar o número de tarefas', FALSE, 0),
      ('Uma equipa automatizou uma tarefa, mas agora erros são replicados em grande escala. Qual princípio foi negligenciado?', 'Validar o processo antes de automatizá-lo', TRUE, 1),
      ('Uma equipa automatizou uma tarefa, mas agora erros são replicados em grande escala. Qual princípio foi negligenciado?', 'Eliminar a revisão', FALSE, 2),
      ('Uma equipa automatizou uma tarefa, mas agora erros são replicados em grande escala. Qual princípio foi negligenciado?', 'Reduzir o controlo', FALSE, 3),
      ('Qual situação representa melhor uma melhoria de processo?', 'Aumentar o número de aprovações', FALSE, 0),
      ('Qual situação representa melhor uma melhoria de processo?', 'Eliminar uma etapa desnecessária sem prejudicar o resultado', TRUE, 1),
      ('Qual situação representa melhor uma melhoria de processo?', 'Fazer a mesma tarefa com mais etapas', FALSE, 2),
      ('Qual situação representa melhor uma melhoria de processo?', 'Adicionar mais relatórios sem finalidade', FALSE, 3),
      ('Uma equipa realiza uma reunião semanal de duas horas, mas grande parte dos participantes não precisa participar de todos os assuntos. Qual melhoria é mais adequada?', 'Aumentar a reunião para três horas', FALSE, 0),
      ('Uma equipa realiza uma reunião semanal de duas horas, mas grande parte dos participantes não precisa participar de todos os assuntos. Qual melhoria é mais adequada?', 'Convidar apenas participantes relevantes para cada assunto', TRUE, 1),
      ('Uma equipa realiza uma reunião semanal de duas horas, mas grande parte dos participantes não precisa participar de todos os assuntos. Qual melhoria é mais adequada?', 'Adicionar mais tópicos', FALSE, 2),
      ('Uma equipa realiza uma reunião semanal de duas horas, mas grande parte dos participantes não precisa participar de todos os assuntos. Qual melhoria é mais adequada?', 'Eliminar a pauta', FALSE, 3),
      ('Uma reunião termina sem decisões, responsáveis ou prazos. Qual é uma das principais falhas?', 'Excesso de prioridades', FALSE, 0),
      ('Uma reunião termina sem decisões, responsáveis ou prazos. Qual é uma das principais falhas?', 'Excesso de documentação', FALSE, 1),
      ('Uma reunião termina sem decisões, responsáveis ou prazos. Qual é uma das principais falhas?', 'Automação inadequada', FALSE, 2),
      ('Uma reunião termina sem decisões, responsáveis ou prazos. Qual é uma das principais falhas?', 'Falta de encaminhamentos concretos', TRUE, 3),
      ('Qual elemento transforma uma decisão de reunião em uma ação acompanhável?', 'Criar novas perguntas', FALSE, 0),
      ('Qual elemento transforma uma decisão de reunião em uma ação acompanhável?', 'Definir responsável e prazo', TRUE, 1),
      ('Qual elemento transforma uma decisão de reunião em uma ação acompanhável?', 'Aumentar o número de participantes', FALSE, 2),
      ('Qual elemento transforma uma decisão de reunião em uma ação acompanhável?', 'Repetir a discussão', FALSE, 3),
      ('Uma pessoa recebe uma tarefa vaga: "Melhorar o relatório". Qual pergunta ajudaria a transformar a tarefa em algo executável?', '"Quando teremos outra reunião?"', FALSE, 0),
      ('Uma pessoa recebe uma tarefa vaga: "Melhorar o relatório". Qual pergunta ajudaria a transformar a tarefa em algo executável?', '"Quantas mensagens recebeste?"', FALSE, 1),
      ('Uma pessoa recebe uma tarefa vaga: "Melhorar o relatório". Qual pergunta ajudaria a transformar a tarefa em algo executável?', '"Qual aplicação utilizas?"', FALSE, 2),
      ('Uma pessoa recebe uma tarefa vaga: "Melhorar o relatório". Qual pergunta ajudaria a transformar a tarefa em algo executável?', '"Qual resultado específico deve ser melhorado?"', TRUE, 3),
      ('O que é ambiguidade de tarefa?', 'Quando uma tarefa é automatizada', FALSE, 0),
      ('O que é ambiguidade de tarefa?', 'Quando a tarefa possui prazo', FALSE, 1),
      ('O que é ambiguidade de tarefa?', 'Quando existem recursos disponíveis', FALSE, 2),
      ('O que é ambiguidade de tarefa?', 'Quando o resultado esperado ou os critérios de execução não estão suficientemente claros', TRUE, 3),
      ('Uma tarefa continua sendo refeita porque o responsável recebe instruções diferentes de várias pessoas. Qual problema existe?', 'Baixa quantidade de tarefas', FALSE, 0),
      ('Uma tarefa continua sendo refeita porque o responsável recebe instruções diferentes de várias pessoas. Qual problema existe?', 'Excesso de descanso', FALSE, 1),
      ('Uma tarefa continua sendo refeita porque o responsável recebe instruções diferentes de várias pessoas. Qual problema existe?', 'Falta de uma definição clara de responsabilidade e critérios', TRUE, 2),
      ('Uma tarefa continua sendo refeita porque o responsável recebe instruções diferentes de várias pessoas. Qual problema existe?', 'Excesso de clareza', FALSE, 3),
      ('Qual é uma vantagem de definir um "responsável final" por uma atividade?', 'Elimina a necessidade de colaboração', FALSE, 0),
      ('Qual é uma vantagem de definir um "responsável final" por uma atividade?', 'Evita que todos assumam responsabilidade simultaneamente', TRUE, 1),
      ('Qual é uma vantagem de definir um "responsável final" por uma atividade?', 'Impede revisões', FALSE, 2),
      ('Qual é uma vantagem de definir um "responsável final" por uma atividade?', 'Garante que nenhum erro ocorrerá', FALSE, 3),
      ('Uma equipa começa novos projetos continuamente sem terminar os anteriores. Qual problema de gestão pode estar presente?', 'Excesso de trabalho em andamento', TRUE, 0),
      ('Uma equipa começa novos projetos continuamente sem terminar os anteriores. Qual problema de gestão pode estar presente?', 'Baixa quantidade de objetivos', FALSE, 1),
      ('Uma equipa começa novos projetos continuamente sem terminar os anteriores. Qual problema de gestão pode estar presente?', 'Excesso de descanso', FALSE, 2),
      ('Uma equipa começa novos projetos continuamente sem terminar os anteriores. Qual problema de gestão pode estar presente?', 'Falta de tarefas', FALSE, 3),
      ('Reduzir o número de tarefas iniciadas simultaneamente pode melhorar o fluxo porque:', 'Impede a conclusão', FALSE, 0),
      ('Reduzir o número de tarefas iniciadas simultaneamente pode melhorar o fluxo porque:', 'Elimina todos os prazos', FALSE, 1),
      ('Reduzir o número de tarefas iniciadas simultaneamente pode melhorar o fluxo porque:', 'Diminui a dispersão de recursos e atenção', TRUE, 2),
      ('Reduzir o número de tarefas iniciadas simultaneamente pode melhorar o fluxo porque:', 'Aumenta necessariamente o número de reuniões', FALSE, 3),
      ('Um funcionário inicia cinco tarefas e termina nenhuma. Qual métrica pode ajudar a identificar esse padrão?', 'Trabalho em andamento', TRUE, 0),
      ('Um funcionário inicia cinco tarefas e termina nenhuma. Qual métrica pode ajudar a identificar esse padrão?', 'Tempo de almoço', FALSE, 1),
      ('Um funcionário inicia cinco tarefas e termina nenhuma. Qual métrica pode ajudar a identificar esse padrão?', 'Número de feriados', FALSE, 2),
      ('Um funcionário inicia cinco tarefas e termina nenhuma. Qual métrica pode ajudar a identificar esse padrão?', 'Número de contactos', FALSE, 3),
      ('O que significa limitar o trabalho em andamento?', 'Aumentar todas as prioridades', FALSE, 0),
      ('O que significa limitar o trabalho em andamento?', 'Trabalhar somente numa tarefa durante toda a vida', FALSE, 1),
      ('O que significa limitar o trabalho em andamento?', 'Controlar quantas tarefas podem estar simultaneamente em execução', TRUE, 2),
      ('O que significa limitar o trabalho em andamento?', 'Impedir qualquer atividade', FALSE, 3),
      ('Uma equipa mantém dez tarefas abertas porque "talvez sejam necessárias", embora apenas três sejam relevantes. Qual ação é mais produtiva?', 'Evitar decisões', FALSE, 0),
      ('Uma equipa mantém dez tarefas abertas porque "talvez sejam necessárias", embora apenas três sejam relevantes. Qual ação é mais produtiva?', 'Aumentar os prazos', FALSE, 1),
      ('Uma equipa mantém dez tarefas abertas porque "talvez sejam necessárias", embora apenas três sejam relevantes. Qual ação é mais produtiva?', 'Adicionar mais sete', FALSE, 2),
      ('Uma equipa mantém dez tarefas abertas porque "talvez sejam necessárias", embora apenas três sejam relevantes. Qual ação é mais produtiva?', 'Revisar e reduzir o trabalho em andamento', TRUE, 3),
      ('Um profissional planeia uma tarefa para duas horas, mas ela geralmente leva quatro. O que deve fazer antes de alterar todo o calendário?', 'Ignorar os dados', FALSE, 0),
      ('Um profissional planeia uma tarefa para duas horas, mas ela geralmente leva quatro. O que deve fazer antes de alterar todo o calendário?', 'Analisar as causas das estimativas incorretas', TRUE, 1),
      ('Um profissional planeia uma tarefa para duas horas, mas ela geralmente leva quatro. O que deve fazer antes de alterar todo o calendário?', 'Reduzir a qualidade', FALSE, 2),
      ('Um profissional planeia uma tarefa para duas horas, mas ela geralmente leva quatro. O que deve fazer antes de alterar todo o calendário?', 'Duplicar todas as tarefas', FALSE, 3),
      ('Por que registar o tempo real de execução pode melhorar o planejamento futuro?', 'Elimina todos os imprevistos', FALSE, 0),
      ('Por que registar o tempo real de execução pode melhorar o planejamento futuro?', 'Garante velocidade constante', FALSE, 1),
      ('Por que registar o tempo real de execução pode melhorar o planejamento futuro?', 'Torna os prazos desnecessários', FALSE, 2),
      ('Por que registar o tempo real de execução pode melhorar o planejamento futuro?', 'Permite comparar estimativas com resultados reais', TRUE, 3),
      ('Uma pessoa sempre subestima pequenas tarefas que, somadas, ocupam várias horas. Qual conceito explica melhor o problema?', 'Pausa programada', FALSE, 0),
      ('Uma pessoa sempre subestima pequenas tarefas que, somadas, ocupam várias horas. Qual conceito explica melhor o problema?', 'Efeito acumulativo de pequenas atividades', TRUE, 1),
      ('Uma pessoa sempre subestima pequenas tarefas que, somadas, ocupam várias horas. Qual conceito explica melhor o problema?', 'Delegação perfeita', FALSE, 2),
      ('Uma pessoa sempre subestima pequenas tarefas que, somadas, ocupam várias horas. Qual conceito explica melhor o problema?', 'Automação completa', FALSE, 3),
      ('Qual estratégia ajuda a revelar atividades que consomem tempo sem contribuir muito para os objetivos?', 'Eliminação dos registros', FALSE, 0),
      ('Qual estratégia ajuda a revelar atividades que consomem tempo sem contribuir muito para os objetivos?', 'Trabalho sem horários', FALSE, 1),
      ('Qual estratégia ajuda a revelar atividades que consomem tempo sem contribuir muito para os objetivos?', 'Auditoria do uso do tempo', TRUE, 2),
      ('Qual estratégia ajuda a revelar atividades que consomem tempo sem contribuir muito para os objetivos?', 'Aumento das notificações', FALSE, 3),
      ('Uma pessoa passa duas horas por dia em atividades administrativas que poderiam ser automatizadas. Qual análise deve ser feita primeiro?', 'Eliminar a atividade sem substituição', FALSE, 0),
      ('Uma pessoa passa duas horas por dia em atividades administrativas que poderiam ser automatizadas. Qual análise deve ser feita primeiro?', 'Verificar frequência, custo e possibilidade de automação', TRUE, 1),
      ('Uma pessoa passa duas horas por dia em atividades administrativas que poderiam ser automatizadas. Qual análise deve ser feita primeiro?', 'Automatizar tudo imediatamente', FALSE, 2),
      ('Uma pessoa passa duas horas por dia em atividades administrativas que poderiam ser automatizadas. Qual análise deve ser feita primeiro?', 'Aumentar o tempo administrativo', FALSE, 3),
      ('Qual é o risco de otimizar uma tarefa isoladamente sem analisar o processo completo?', 'Elimina gargalos automaticamente', FALSE, 0),
      ('Qual é o risco de otimizar uma tarefa isoladamente sem analisar o processo completo?', 'Sempre aumenta a qualidade', FALSE, 1),
      ('Qual é o risco de otimizar uma tarefa isoladamente sem analisar o processo completo?', 'Sempre reduz o tempo total', FALSE, 2),
      ('Qual é o risco de otimizar uma tarefa isoladamente sem analisar o processo completo?', 'Pode melhorar uma etapa e piorar o fluxo geral', TRUE, 3),
      ('Uma equipa reduz o tempo de produção de um produto, mas aumenta o tempo de espera antes da entrega. Qual conclusão é mais adequada?', 'A etapa de produção deixou de ser importante', FALSE, 0),
      ('Uma equipa reduz o tempo de produção de um produto, mas aumenta o tempo de espera antes da entrega. Qual conclusão é mais adequada?', 'A produtividade global necessariamente melhorou', FALSE, 1),
      ('Uma equipa reduz o tempo de produção de um produto, mas aumenta o tempo de espera antes da entrega. Qual conclusão é mais adequada?', 'O tempo de espera não possui relevância', FALSE, 2),
      ('Uma equipa reduz o tempo de produção de um produto, mas aumenta o tempo de espera antes da entrega. Qual conclusão é mais adequada?', 'É necessário analisar o fluxo completo, não apenas uma etapa', TRUE, 3),
      ('O que caracteriza uma otimização local?', 'Automatizar toda a organização', FALSE, 0),
      ('O que caracteriza uma otimização local?', 'Eliminar todas as etapas', FALSE, 1),
      ('O que caracteriza uma otimização local?', 'Melhorar uma parte do processo sem necessariamente melhorar o resultado global', TRUE, 2),
      ('O que caracteriza uma otimização local?', 'Melhorar todo o sistema simultaneamente', FALSE, 3),
      ('Uma equipa utiliza uma ferramenta sofisticada, mas ninguém sabe claramente quais são as prioridades. Qual conclusão é mais razoável?', 'Mais ferramentas resolverão necessariamente o problema', FALSE, 0),
      ('Uma equipa utiliza uma ferramenta sofisticada, mas ninguém sabe claramente quais são as prioridades. Qual conclusão é mais razoável?', 'A ferramenta substitui a necessidade de planejamento', FALSE, 1),
      ('Uma equipa utiliza uma ferramenta sofisticada, mas ninguém sabe claramente quais são as prioridades. Qual conclusão é mais razoável?', 'O problema é exclusivamente técnico', FALSE, 2),
      ('Uma equipa utiliza uma ferramenta sofisticada, mas ninguém sabe claramente quais são as prioridades. Qual conclusão é mais razoável?', 'Tecnologia não resolve sozinha problemas de organização', TRUE, 3),
      ('Qual princípio deve orientar a escolha de uma ferramenta de produtividade?', 'Trocar de ferramenta semanalmente', FALSE, 0),
      ('Qual princípio deve orientar a escolha de uma ferramenta de produtividade?', 'Utilizar o maior número possível de ferramentas', FALSE, 1),
      ('Qual princípio deve orientar a escolha de uma ferramenta de produtividade?', 'Escolher a ferramenta que melhor atende à necessidade real', TRUE, 2),
      ('Qual princípio deve orientar a escolha de uma ferramenta de produtividade?', 'Escolher a ferramenta mais complexa', FALSE, 3),
      ('Uma equipa utiliza três aplicações diferentes para armazenar a mesma informação. Qual risco aumenta?', 'Clareza automática', FALSE, 0),
      ('Uma equipa utiliza três aplicações diferentes para armazenar a mesma informação. Qual risco aumenta?', 'Fragmentação da informação', TRUE, 1),
      ('Uma equipa utiliza três aplicações diferentes para armazenar a mesma informação. Qual risco aumenta?', 'Redução de duplicação', FALSE, 2),
      ('Uma equipa utiliza três aplicações diferentes para armazenar a mesma informação. Qual risco aumenta?', 'Centralização', FALSE, 3),
      ('O que significa centralizar informações relevantes?', 'Manter informações importantes acessíveis num sistema ou estrutura coerente', TRUE, 0),
      ('O que significa centralizar informações relevantes?', 'Eliminar qualquer documentação', FALSE, 1),
      ('O que significa centralizar informações relevantes?', 'Copiar tudo para vários locais', FALSE, 2),
      ('O que significa centralizar informações relevantes?', 'Usar apenas mensagens instantâneas', FALSE, 3),
      ('Uma pessoa tem um objetivo para seis meses, mas nunca verifica seu progresso. Qual problema existe?', 'Falta de acompanhamento', TRUE, 0),
      ('Uma pessoa tem um objetivo para seis meses, mas nunca verifica seu progresso. Qual problema existe?', 'Excesso de medição', FALSE, 1),
      ('Uma pessoa tem um objetivo para seis meses, mas nunca verifica seu progresso. Qual problema existe?', 'Excesso de revisão', FALSE, 2),
      ('Uma pessoa tem um objetivo para seis meses, mas nunca verifica seu progresso. Qual problema existe?', 'Planejamento excessivamente curto', FALSE, 3),
      ('Qual frequência de revisão é mais adequada para uma meta de longo prazo?', 'A cada minuto', FALSE, 0),
      ('Qual frequência de revisão é mais adequada para uma meta de longo prazo?', 'Periodicamente, de acordo com a natureza da meta', TRUE, 1),
      ('Qual frequência de revisão é mais adequada para uma meta de longo prazo?', 'Apenas no último dia', FALSE, 2),
      ('Qual frequência de revisão é mais adequada para uma meta de longo prazo?', 'Nunca', FALSE, 3),
      ('Uma meta está atrasada porque as condições externas mudaram significativamente. Qual comportamento demonstra boa gestão?', 'Reavaliar premissas e ajustar o plano', TRUE, 0),
      ('Uma meta está atrasada porque as condições externas mudaram significativamente. Qual comportamento demonstra boa gestão?', 'Abandonar todos os objetivos', FALSE, 1),
      ('Uma meta está atrasada porque as condições externas mudaram significativamente. Qual comportamento demonstra boa gestão?', 'Ignorar os dados', FALSE, 2),
      ('Uma meta está atrasada porque as condições externas mudaram significativamente. Qual comportamento demonstra boa gestão?', 'Manter o plano original independentemente das novas condições', FALSE, 3),
      ('O que é uma premissa de planejamento?', 'Um resultado garantido', FALSE, 0),
      ('O que é uma premissa de planejamento?', 'Uma pausa', FALSE, 1),
      ('O que é uma premissa de planejamento?', 'Uma condição considerada verdadeira ao construir um plano', TRUE, 2),
      ('O que é uma premissa de planejamento?', 'Uma tarefa concluída', FALSE, 3),
      ('Por que rever premissas pode ser importante?', 'Porque todo plano deve ser abandonado semanalmente', FALSE, 0),
      ('Por que rever premissas pode ser importante?', 'Porque dados não são importantes', FALSE, 1),
      ('Por que rever premissas pode ser importante?', 'Porque metas não precisam de estabilidade', FALSE, 2),
      ('Por que rever premissas pode ser importante?', 'Porque mudanças nas condições podem tornar o plano inadequado', TRUE, 3),
      ('Uma equipa estabelece um prazo sem considerar a duração das dependências anteriores. Qual falha ocorreu?', 'A tarefa ficou simples demais', FALSE, 0),
      ('Uma equipa estabelece um prazo sem considerar a duração das dependências anteriores. Qual falha ocorreu?', 'O prazo foi definido sem analisar o caminho necessário até a entrega', TRUE, 1),
      ('Uma equipa estabelece um prazo sem considerar a duração das dependências anteriores. Qual falha ocorreu?', 'Houve excesso de automação', FALSE, 2),
      ('Uma equipa estabelece um prazo sem considerar a duração das dependências anteriores. Qual falha ocorreu?', 'A equipa possui demasiados recursos', FALSE, 3),
      ('O que significa identificar o caminho crítico de um projeto?', 'Escolher as tarefas mais fáceis', FALSE, 0),
      ('O que significa identificar o caminho crítico de um projeto?', 'Escolher o maior número de participantes', FALSE, 1),
      ('O que significa identificar o caminho crítico de um projeto?', 'Eliminar atividades independentes', FALSE, 2),
      ('O que significa identificar o caminho crítico de um projeto?', 'Identificar a sequência de atividades que determina a duração mínima possível do projeto', TRUE, 3),
      ('Se uma atividade do caminho crítico atrasar e não houver margem, o que pode acontecer?', 'A atividade deixa de ser necessária', FALSE, 0),
      ('Se uma atividade do caminho crítico atrasar e não houver margem, o que pode acontecer?', 'O atraso desaparece', FALSE, 1),
      ('Se uma atividade do caminho crítico atrasar e não houver margem, o que pode acontecer?', 'O projeto necessariamente termina antes', FALSE, 2),
      ('Se uma atividade do caminho crítico atrasar e não houver margem, o que pode acontecer?', 'O prazo final do projeto pode atrasar', TRUE, 3),
      ('Qual é a finalidade de uma retrospectiva de projeto?', 'Evitar documentação', FALSE, 0),
      ('Qual é a finalidade de uma retrospectiva de projeto?', 'Eliminar indicadores', FALSE, 1),
      ('Qual é a finalidade de uma retrospectiva de projeto?', 'Repetir todas as decisões', FALSE, 2),
      ('Qual é a finalidade de uma retrospectiva de projeto?', 'Aprender com o processo e identificar melhorias para futuros projetos', TRUE, 3),
      ('Uma retrospectiva identifica que reuniões longas foram responsáveis por atrasos recorrentes. Qual seria uma resposta baseada em evidências?', 'Ignorar a descoberta', FALSE, 0),
      ('Uma retrospectiva identifica que reuniões longas foram responsáveis por atrasos recorrentes. Qual seria uma resposta baseada em evidências?', 'Adicionar mais reuniões', FALSE, 1),
      ('Uma retrospectiva identifica que reuniões longas foram responsáveis por atrasos recorrentes. Qual seria uma resposta baseada em evidências?', 'Testar reuniões mais curtas e medir o impacto', TRUE, 2),
      ('Uma retrospectiva identifica que reuniões longas foram responsáveis por atrasos recorrentes. Qual seria uma resposta baseada em evidências?', 'Aumentar a duração das reuniões', FALSE, 3),
      ('Por que testar uma melhoria antes de aplicá-la em toda a organização pode ser útil?', 'Impede aprendizagem', FALSE, 0),
      ('Por que testar uma melhoria antes de aplicá-la em toda a organização pode ser útil?', 'Permite avaliar resultados e riscos em escala controlada', TRUE, 1),
      ('Por que testar uma melhoria antes de aplicá-la em toda a organização pode ser útil?', 'Elimina qualquer necessidade de medição', FALSE, 2),
      ('Por que testar uma melhoria antes de aplicá-la em toda a organização pode ser útil?', 'Garante que a melhoria funcionará', FALSE, 3),
      ('Uma equipa implementa uma nova rotina e, após um mês, verifica que o desempenho piorou. Qual atitude é mais adequada?', 'Analisar os dados e ajustar ou abandonar a abordagem conforme os resultados', TRUE, 0),
      ('Uma equipa implementa uma nova rotina e, após um mês, verifica que o desempenho piorou. Qual atitude é mais adequada?', 'Manter a rotina obrigatoriamente', FALSE, 1),
      ('Uma equipa implementa uma nova rotina e, após um mês, verifica que o desempenho piorou. Qual atitude é mais adequada?', 'Ignorar os resultados', FALSE, 2),
      ('Uma equipa implementa uma nova rotina e, após um mês, verifica que o desempenho piorou. Qual atitude é mais adequada?', 'Aumentar a complexidade', FALSE, 3),
      ('O que caracteriza uma cultura de melhoria contínua?', 'Evitar qualquer mudança', FALSE, 0),
      ('O que caracteriza uma cultura de melhoria contínua?', 'Procurar regularmente formas baseadas em evidências para melhorar processos', TRUE, 1),
      ('O que caracteriza uma cultura de melhoria contínua?', 'Alterar processos constantemente sem medir resultados', FALSE, 2),
      ('O que caracteriza uma cultura de melhoria contínua?', 'Utilizar sempre ferramentas novas', FALSE, 3),
      ('Uma pessoa trabalha melhor quando possui um objetivo claramente definido, mas recebe tarefas inesperadas constantemente. Qual solução pode equilibrar flexibilidade e foco?', 'Cancelar todos os objetivos', FALSE, 0),
      ('Uma pessoa trabalha melhor quando possui um objetivo claramente definido, mas recebe tarefas inesperadas constantemente. Qual solução pode equilibrar flexibilidade e foco?', 'Preencher cada minuto do calendário', FALSE, 1),
      ('Uma pessoa trabalha melhor quando possui um objetivo claramente definido, mas recebe tarefas inesperadas constantemente. Qual solução pode equilibrar flexibilidade e foco?', 'Reservar uma margem de tempo para imprevistos', TRUE, 2),
      ('Uma pessoa trabalha melhor quando possui um objetivo claramente definido, mas recebe tarefas inesperadas constantemente. Qual solução pode equilibrar flexibilidade e foco?', 'Ignorar todas as novas tarefas', FALSE, 3),
      ('Qual é a principal função de uma margem de capacidade no planejamento?', 'Permitir absorver variações sem comprometer imediatamente o plano', TRUE, 0),
      ('Qual é a principal função de uma margem de capacidade no planejamento?', 'Garantir que o calendário fique completamente cheio', FALSE, 1),
      ('Qual é a principal função de uma margem de capacidade no planejamento?', 'Aumentar interrupções', FALSE, 2),
      ('Qual é a principal função de uma margem de capacidade no planejamento?', 'Eliminar prioridades', FALSE, 3),
      ('Uma equipa está sempre ocupada, mas os resultados estratégicos não melhoram. Qual diagnóstico deve ser considerado primeiro?', 'Falta de tarefas', FALSE, 0),
      ('Uma equipa está sempre ocupada, mas os resultados estratégicos não melhoram. Qual diagnóstico deve ser considerado primeiro?', 'Falta de reuniões', FALSE, 1),
      ('Uma equipa está sempre ocupada, mas os resultados estratégicos não melhoram. Qual diagnóstico deve ser considerado primeiro?', 'Excesso de ferramentas', FALSE, 2),
      ('Uma equipa está sempre ocupada, mas os resultados estratégicos não melhoram. Qual diagnóstico deve ser considerado primeiro?', 'Possível desalinhamento entre atividades e objetivos', TRUE, 3),
      ('Qual pergunta melhor ajuda a identificar atividades de baixo valor?', '"Esta atividade contribui significativamente para algum objetivo?"', TRUE, 0),
      ('Qual pergunta melhor ajuda a identificar atividades de baixo valor?', '"Quantas aplicações uso?"', FALSE, 1),
      ('Qual pergunta melhor ajuda a identificar atividades de baixo valor?', '"Quantas mensagens recebi?"', FALSE, 2),
      ('Qual pergunta melhor ajuda a identificar atividades de baixo valor?', '"Quanto tempo estou ocupado?"', FALSE, 3),
      ('Uma pessoa continua executando manualmente uma tarefa porque "sempre foi assim". Qual princípio de produtividade deve ser aplicado?', 'Adicionar etapas', FALSE, 0),
      ('Uma pessoa continua executando manualmente uma tarefa porque "sempre foi assim". Qual princípio de produtividade deve ser aplicado?', 'Aumentar o trabalho manual', FALSE, 1),
      ('Uma pessoa continua executando manualmente uma tarefa porque "sempre foi assim". Qual princípio de produtividade deve ser aplicado?', 'Questionar processos existentes e procurar oportunidades de melhoria', TRUE, 2),
      ('Uma pessoa continua executando manualmente uma tarefa porque "sempre foi assim". Qual princípio de produtividade deve ser aplicado?', 'Nunca mudar processos', FALSE, 3),
      ('Qual situação representa desperdício de capacidade?', 'Reservar tempo para descanso', FALSE, 0),
      ('Qual situação representa desperdício de capacidade?', 'Revisar resultados', FALSE, 1),
      ('Qual situação representa desperdício de capacidade?', 'Utilizar tempo e recursos em atividades sem contribuição relevante para os objetivos', TRUE, 2),
      ('Qual situação representa desperdício de capacidade?', 'Planejar tarefas críticas', FALSE, 3),
      ('Uma organização possui excelentes planos, mas baixa execução. Qual fator pode explicar essa diferença?', 'Excesso de clareza', FALSE, 0),
      ('Uma organização possui excelentes planos, mas baixa execução. Qual fator pode explicar essa diferença?', 'Planejamento demasiado simples', FALSE, 1),
      ('Uma organização possui excelentes planos, mas baixa execução. Qual fator pode explicar essa diferença?', 'Excesso de objetivos mensuráveis', FALSE, 2),
      ('Uma organização possui excelentes planos, mas baixa execução. Qual fator pode explicar essa diferença?', 'Falta de definição clara de responsabilidades e acompanhamento', TRUE, 3),
      ('O que transforma um plano em um sistema de execução mais robusto?', 'Responsáveis, prazos, prioridades e acompanhamento', TRUE, 0),
      ('O que transforma um plano em um sistema de execução mais robusto?', 'Apenas uma lista de desejos', FALSE, 1),
      ('O que transforma um plano em um sistema de execução mais robusto?', 'Mais tarefas', FALSE, 2),
      ('O que transforma um plano em um sistema de execução mais robusto?', 'Menos informação', FALSE, 3),
      ('Uma pessoa termina uma tarefa e imediatamente começa outra sem verificar se o resultado atende aos critérios definidos. Qual risco aumenta?', 'Entregas incompletas ou de baixa qualidade', TRUE, 0),
      ('Uma pessoa termina uma tarefa e imediatamente começa outra sem verificar se o resultado atende aos critérios definidos. Qual risco aumenta?', 'Maior clareza', FALSE, 1),
      ('Uma pessoa termina uma tarefa e imediatamente começa outra sem verificar se o resultado atende aos critérios definidos. Qual risco aumenta?', 'Melhor validação', FALSE, 2),
      ('Uma pessoa termina uma tarefa e imediatamente começa outra sem verificar se o resultado atende aos critérios definidos. Qual risco aumenta?', 'Redução de retrabalho', FALSE, 3),
      ('Qual etapa deve ocorrer antes de considerar uma entrega concluída em um processo que exige qualidade?', 'Início de outra tarefa', FALSE, 0),
      ('Qual etapa deve ocorrer antes de considerar uma entrega concluída em um processo que exige qualidade?', 'Criação de uma nova prioridade', FALSE, 1),
      ('Qual etapa deve ocorrer antes de considerar uma entrega concluída em um processo que exige qualidade?', 'Verificação contra os critérios definidos', TRUE, 2),
      ('Qual etapa deve ocorrer antes de considerar uma entrega concluída em um processo que exige qualidade?', 'Eliminação dos registros', FALSE, 3),
      ('Um projeto apresenta muitas revisões porque os requisitos mudam constantemente. Qual medida pode reduzir retrabalho?', 'Evitar comunicação', FALSE, 0),
      ('Um projeto apresenta muitas revisões porque os requisitos mudam constantemente. Qual medida pode reduzir retrabalho?', 'Aumentar o número de versões sem controle', FALSE, 1),
      ('Um projeto apresenta muitas revisões porque os requisitos mudam constantemente. Qual medida pode reduzir retrabalho?', 'Fazer mais trabalho sem requisitos', FALSE, 2),
      ('Um projeto apresenta muitas revisões porque os requisitos mudam constantemente. Qual medida pode reduzir retrabalho?', 'Clarificar requisitos e estabelecer critérios de aceitação antes da execução', TRUE, 3),
      ('Qual é uma consequência direta de requisitos pouco claros?', 'Aumento da probabilidade de retrabalho', TRUE, 0),
      ('Qual é uma consequência direta de requisitos pouco claros?', 'Maior previsibilidade', FALSE, 1),
      ('Qual é uma consequência direta de requisitos pouco claros?', 'Redução automática dos custos', FALSE, 2),
      ('Qual é uma consequência direta de requisitos pouco claros?', 'Menor necessidade de comunicação', FALSE, 3)
    ) AS a(statement, label, is_correct, display_order)
    ON q.statement = a.statement;

    DROP TABLE tmp_new_questions_prod_dificil_v2;

    RAISE NOTICE '75 perguntas inseridas com sucesso (source=seed_produtividade_dificil_v2).';
  END IF;
END $$;

COMMIT;
