-- Migration/seed: conteúdo Tecnologia, nível Difícil (50 perguntas)
-- Fonte: lote de perguntas fornecido pelo proprietário do projeto (mesmo padrão
-- dos lotes anteriores: 003_tecnologia_facil.sql, 004_tecnologia_medio.sql e
-- 005_tecnologia_facil_2.sql).
--
-- CORREÇÃO DE QUALIDADE APLICADA (mesma higiene de dado dos lotes anteriores,
-- não é decisão de negócio): no lote original, as 50 respostas corretas eram
-- TODAS a alternativa "A" — decorável sem conhecimento real. A posição da
-- alternativa correta foi redistribuída por pergunta com seed fixa (45 —
-- distinta das seeds 42/43/44 já usadas, para não repetir o mesmo padrão de
-- posições) e distribuição controlada (13/13/12/12 entre A/B/C/D),
-- reprodutível — o conteúdo pedagógico (perguntas, alternativas) permanece
-- exatamente como enviado, só a ORDEM de exibição de cada alternativa mudou.
--
-- Verificado: nenhuma das 50 perguntas deste lote colide (mesmo enunciado) com
-- as já existentes em 003/004/005 na categoria Tecnologia.
--
-- Idempotente: usa a coluna `source` (migration 022) como marcador — rodar
-- este arquivo mais de uma vez não duplica as perguntas.

BEGIN;

DO $$
DECLARE
  v_category_id UUID;
BEGIN
  SELECT id INTO v_category_id FROM categories WHERE slug = 'tecnologia';
  IF v_category_id IS NULL THEN
    RAISE EXCEPTION 'Categoria "tecnologia" não encontrada — rode a migration 021 primeiro.';
  END IF;

  IF EXISTS (SELECT 1 FROM questions WHERE source = 'seed_tecnologia_dificil_v1') THEN
    RAISE NOTICE 'Perguntas já foram inseridas anteriormente (source=seed_tecnologia_dificil_v1) — nada a fazer.';
  ELSE

    CREATE TEMP TABLE tmp_new_questions_tec_dificil AS
    WITH inserted AS (
    INSERT INTO questions (category_id, difficulty, statement, time_limit_seconds, xp_reward, source)
    SELECT v_category_id, 'hard', v.statement, 15, 10, 'seed_tecnologia_dificil_v1'
    FROM (VALUES
      ('O que é computação em nuvem?'),
      ('Qual é uma característica da computação em nuvem?'),
      ('O que significa SaaS em tecnologia?'),
      ('Qual exemplo representa um modelo SaaS?'),
      ('O que é IaaS?'),
      ('O que é PaaS?'),
      ('O que é virtualização?'),
      ('O que é uma máquina virtual?'),
      ('Qual é a função de um hipervisor?'),
      ('O que é contêiner em tecnologia?'),
      ('Qual tecnologia é muito utilizada para gerenciamento de contêineres?'),
      ('O que é DevOps?'),
      ('O que significa CI/CD?'),
      ('O que é uma API REST?'),
      ('O que significa HTTP?'),
      ('Qual é a função do HTTPS?'),
      ('O que é DNS?'),
      ('O que acontece quando um usuário acessa um site pelo domínio?'),
      ('O que é firewall?'),
      ('Qual é a função principal de um firewall?'),
      ('O que é criptografia assimétrica?'),
      ('O que é uma chave pública em criptografia assimétrica?'),
      ('O que é engenharia social?'),
      ('Qual é um exemplo de engenharia social?'),
      ('O que é autenticação biométrica?'),
      ('O que é machine learning supervisionado?'),
      ('O que é uma rede neural artificial?'),
      ('O que é deep learning?'),
      ('O que é processamento de linguagem natural (PLN)?'),
      ('O que é visão computacional?'),
      ('O que é Big Data?'),
      ('O que significa análise de dados?'),
      ('O que é mineração de dados?'),
      ('O que é blockchain em termos tecnológicos?'),
      ('O que é um contrato inteligente (smart contract)?'),
      ('O que é edge computing?'),
      ('Qual é uma vantagem do edge computing?'),
      ('O que é baixa latência?'),
      ('O que é arquitetura de microsserviços?'),
      ('Qual é uma vantagem dos microsserviços?'),
      ('O que é escalabilidade em sistemas?'),
      ('O que é escalabilidade horizontal?'),
      ('O que é escalabilidade vertical?'),
      ('O que é observabilidade em sistemas?'),
      ('O que são logs em sistemas?'),
      ('O que é uma vulnerabilidade de software?'),
      ('O que é teste de penetração (pentest)?'),
      ('O que é Zero Trust em segurança?'),
      ('O que é API Gateway?'),
      ('Por que a segurança da informação é importante?')
    ) AS v(statement)
    RETURNING id, statement
    )
    SELECT * FROM inserted;

    INSERT INTO question_alternatives (question_id, label, is_correct, display_order)
    SELECT q.id, a.label, a.is_correct, a.display_order
    FROM tmp_new_questions_tec_dificil q
    JOIN (VALUES
      ('O que é computação em nuvem?', 'Programa instalado apenas em computadores antigos', FALSE, 0),
      ('O que é computação em nuvem?', 'Sistema exclusivo para armazenamento físico', FALSE, 1),
      ('O que é computação em nuvem?', 'Modelo que permite acesso remoto a recursos computacionais através da internet', TRUE, 2),
      ('O que é computação em nuvem?', 'Método para aumentar o tamanho do monitor', FALSE, 3),
      ('Qual é uma característica da computação em nuvem?', 'Funcionamento somente offline', FALSE, 0),
      ('Qual é uma característica da computação em nuvem?', 'Ausência total de segurança', FALSE, 1),
      ('Qual é uma característica da computação em nuvem?', 'Escalabilidade conforme a necessidade do usuário ou empresa', TRUE, 2),
      ('Qual é uma característica da computação em nuvem?', 'Dependência obrigatória de um único computador físico', FALSE, 3),
      ('O que significa SaaS em tecnologia?', 'Sistema operacional de servidores', FALSE, 0),
      ('O que significa SaaS em tecnologia?', 'Software como Serviço, onde aplicações são disponibilizadas pela internet', TRUE, 1),
      ('O que significa SaaS em tecnologia?', 'Serviço de antivírus físico', FALSE, 2),
      ('O que significa SaaS em tecnologia?', 'Sistema automático de armazenamento seguro', FALSE, 3),
      ('Qual exemplo representa um modelo SaaS?', 'Uma ferramenta de email acessada pelo navegador', TRUE, 0),
      ('Qual exemplo representa um modelo SaaS?', 'Um cabo de rede', FALSE, 1),
      ('Qual exemplo representa um modelo SaaS?', 'Um processador', FALSE, 2),
      ('Qual exemplo representa um modelo SaaS?', 'Uma placa gráfica', FALSE, 3),
      ('O que é IaaS?', 'Linguagem de programação', FALSE, 0),
      ('O que é IaaS?', 'Modelo que fornece infraestrutura computacional como servidores, armazenamento e redes através da nuvem', TRUE, 1),
      ('O que é IaaS?', 'Sistema de edição de imagens', FALSE, 2),
      ('O que é IaaS?', 'Aplicativo de mensagens', FALSE, 3),
      ('O que é PaaS?', 'Programa de proteção contra vírus', FALSE, 0),
      ('O que é PaaS?', 'Dispositivo de armazenamento físico', FALSE, 1),
      ('O que é PaaS?', 'Rede social', FALSE, 2),
      ('O que é PaaS?', 'Plataforma que oferece ambiente para desenvolvimento e execução de aplicações', TRUE, 3),
      ('O que é virtualização?', 'Criação de senhas', FALSE, 0),
      ('O que é virtualização?', 'Processo de apagar dados', FALSE, 1),
      ('O que é virtualização?', 'Instalação de aplicativos móveis', FALSE, 2),
      ('O que é virtualização?', 'Tecnologia que permite criar versões virtuais de recursos físicos, como máquinas ou servidores', TRUE, 3),
      ('O que é uma máquina virtual?', 'Ambiente computacional criado por software que funciona como um computador independente', TRUE, 0),
      ('O que é uma máquina virtual?', 'Um computador sem sistema operacional', FALSE, 1),
      ('O que é uma máquina virtual?', 'Um tipo de cabo', FALSE, 2),
      ('O que é uma máquina virtual?', 'Um arquivo de imagem', FALSE, 3),
      ('Qual é a função de um hipervisor?', 'Proteger apenas emails', FALSE, 0),
      ('Qual é a função de um hipervisor?', 'Criar páginas web', FALSE, 1),
      ('Qual é a função de um hipervisor?', 'Editar vídeos', FALSE, 2),
      ('Qual é a função de um hipervisor?', 'Gerenciar máquinas virtuais em um ambiente virtualizado', TRUE, 3),
      ('O que é contêiner em tecnologia?', 'Um dispositivo físico de armazenamento', FALSE, 0),
      ('O que é contêiner em tecnologia?', 'Um navegador', FALSE, 1),
      ('O que é contêiner em tecnologia?', 'Uma rede social', FALSE, 2),
      ('O que é contêiner em tecnologia?', 'Ambiente isolado que permite executar aplicações com suas dependências', TRUE, 3),
      ('Qual tecnologia é muito utilizada para gerenciamento de contêineres?', 'Bluetooth', FALSE, 0),
      ('Qual tecnologia é muito utilizada para gerenciamento de contêineres?', 'Kubernetes', TRUE, 1),
      ('Qual tecnologia é muito utilizada para gerenciamento de contêineres?', 'Photoshop', FALSE, 2),
      ('Qual tecnologia é muito utilizada para gerenciamento de contêineres?', 'Excel', FALSE, 3),
      ('O que é DevOps?', 'Cultura e conjunto de práticas que aproximam desenvolvimento de software e operações', TRUE, 0),
      ('O que é DevOps?', 'Programa de edição gráfica', FALSE, 1),
      ('O que é DevOps?', 'Tipo de hardware', FALSE, 2),
      ('O que é DevOps?', 'Sistema bancário', FALSE, 3),
      ('O que significa CI/CD?', 'Práticas de integração contínua e entrega ou implantação contínua de software', TRUE, 0),
      ('O que significa CI/CD?', 'Método de criptografia', FALSE, 1),
      ('O que significa CI/CD?', 'Linguagem de programação', FALSE, 2),
      ('O que significa CI/CD?', 'Sistema de armazenamento físico', FALSE, 3),
      ('O que é uma API REST?', 'Um antivírus', FALSE, 0),
      ('O que é uma API REST?', 'Um tipo de memória', FALSE, 1),
      ('O que é uma API REST?', 'Um cabo de rede', FALSE, 2),
      ('O que é uma API REST?', 'Interface que permite comunicação entre sistemas usando princípios da arquitetura REST', TRUE, 3),
      ('O que significa HTTP?', 'Sistema operacional', FALSE, 0),
      ('O que significa HTTP?', 'Linguagem de programação', FALSE, 1),
      ('O que significa HTTP?', 'Banco de dados', FALSE, 2),
      ('O que significa HTTP?', 'Protocolo utilizado para comunicação e transferência de informações na web', TRUE, 3),
      ('Qual é a função do HTTPS?', 'Adicionar uma camada de segurança através de criptografia na comunicação web', TRUE, 0),
      ('Qual é a função do HTTPS?', 'Melhorar a câmera do dispositivo', FALSE, 1),
      ('Qual é a função do HTTPS?', 'Criar aplicativos automaticamente', FALSE, 2),
      ('Qual é a função do HTTPS?', 'Aumentar a memória RAM', FALSE, 3),
      ('O que é DNS?', 'Processador gráfico', FALSE, 0),
      ('O que é DNS?', 'Programa antivírus', FALSE, 1),
      ('O que é DNS?', 'Sistema de armazenamento de fotos', FALSE, 2),
      ('O que é DNS?', 'Sistema responsável por traduzir nomes de domínio em endereços IP', TRUE, 3),
      ('O que acontece quando um usuário acessa um site pelo domínio?', 'O site é instalado no dispositivo', FALSE, 0),
      ('O que acontece quando um usuário acessa um site pelo domínio?', 'A memória RAM é substituída', FALSE, 1),
      ('O que acontece quando um usuário acessa um site pelo domínio?', 'O DNS ajuda a localizar o servidor associado ao domínio', TRUE, 2),
      ('O que acontece quando um usuário acessa um site pelo domínio?', 'O computador troca automaticamente de sistema operacional', FALSE, 3),
      ('O que é firewall?', 'Um navegador', FALSE, 0),
      ('O que é firewall?', 'Um processador', FALSE, 1),
      ('O que é firewall?', 'Um cabo de internet', FALSE, 2),
      ('O que é firewall?', 'Sistema que controla e filtra conexões de rede baseado em regras definidas', TRUE, 3),
      ('Qual é a função principal de um firewall?', 'Aumentar a capacidade do armazenamento', FALSE, 0),
      ('Qual é a função principal de um firewall?', 'Criar aplicativos', FALSE, 1),
      ('Qual é a função principal de um firewall?', 'Ajudar a proteger redes contra acessos não autorizados', TRUE, 2),
      ('Qual é a função principal de um firewall?', 'Melhorar a resolução da tela', FALSE, 3),
      ('O que é criptografia assimétrica?', 'Método sem uso de chaves', FALSE, 0),
      ('O que é criptografia assimétrica?', 'Sistema de compressão de arquivos', FALSE, 1),
      ('O que é criptografia assimétrica?', 'Método que utiliza chaves diferentes para cifrar e decifrar informações', TRUE, 2),
      ('O que é criptografia assimétrica?', 'Técnica de aumentar velocidade da internet', FALSE, 3),
      ('O que é uma chave pública em criptografia assimétrica?', 'Senha pessoal obrigatoriamente secreta', FALSE, 0),
      ('O que é uma chave pública em criptografia assimétrica?', 'Tipo de memória', FALSE, 1),
      ('O que é uma chave pública em criptografia assimétrica?', 'Chave que pode ser compartilhada para permitir determinadas operações criptográficas', TRUE, 2),
      ('O que é uma chave pública em criptografia assimétrica?', 'Arquivo de vídeo', FALSE, 3),
      ('O que é engenharia social?', 'Desenvolvimento de jogos', FALSE, 0),
      ('O que é engenharia social?', 'Criação de redes físicas', FALSE, 1),
      ('O que é engenharia social?', 'Manipulação psicológica para obter informações ou realizar ações indevidas', TRUE, 2),
      ('O que é engenharia social?', 'Construção de computadores', FALSE, 3),
      ('Qual é um exemplo de engenharia social?', 'Instalar uma atualização de segurança', FALSE, 0),
      ('Qual é um exemplo de engenharia social?', 'Alguém fingir ser uma instituição para solicitar dados confidenciais', TRUE, 1),
      ('Qual é um exemplo de engenharia social?', 'Atualizar um aplicativo oficial', FALSE, 2),
      ('Qual é um exemplo de engenharia social?', 'Criar um backup', FALSE, 3),
      ('O que é autenticação biométrica?', 'Uso de endereço IP', FALSE, 0),
      ('O que é autenticação biométrica?', 'Verificação de identidade usando características físicas ou comportamentais', TRUE, 1),
      ('O que é autenticação biométrica?', 'Uso apenas de nome de usuário', FALSE, 2),
      ('O que é autenticação biométrica?', 'Uso de cabo USB', FALSE, 3),
      ('O que é machine learning supervisionado?', 'Programa de edição', FALSE, 0),
      ('O que é machine learning supervisionado?', 'Modelo treinado utilizando dados previamente classificados ou identificados', TRUE, 1),
      ('O que é machine learning supervisionado?', 'Modelo sem qualquer dado', FALSE, 2),
      ('O que é machine learning supervisionado?', 'Sistema exclusivamente manual', FALSE, 3),
      ('O que é uma rede neural artificial?', 'Modelo computacional inspirado em estruturas do cérebro para reconhecer padrões', TRUE, 0),
      ('O que é uma rede neural artificial?', 'Sistema operacional', FALSE, 1),
      ('O que é uma rede neural artificial?', 'Banco de dados simples', FALSE, 2),
      ('O que é uma rede neural artificial?', 'Rede física de cabos', FALSE, 3),
      ('O que é deep learning?', 'Método de compactação de arquivos', FALSE, 0),
      ('O que é deep learning?', 'Tipo de memória RAM', FALSE, 1),
      ('O que é deep learning?', 'Subárea de machine learning baseada em redes neurais profundas', TRUE, 2),
      ('O que é deep learning?', 'Sistema de pagamento', FALSE, 3),
      ('O que é processamento de linguagem natural (PLN)?', 'Método de impressão', FALSE, 0),
      ('O que é processamento de linguagem natural (PLN)?', 'Área da IA que permite computadores compreenderem e gerarem linguagem humana', TRUE, 1),
      ('O que é processamento de linguagem natural (PLN)?', 'Sistema de armazenamento', FALSE, 2),
      ('O que é processamento de linguagem natural (PLN)?', 'Tecnologia de bateria', FALSE, 3),
      ('O que é visão computacional?', 'Tipo de monitor', FALSE, 0),
      ('O que é visão computacional?', 'Sistema operacional', FALSE, 1),
      ('O que é visão computacional?', 'Área da IA que permite sistemas interpretarem informações visuais de imagens e vídeos', TRUE, 2),
      ('O que é visão computacional?', 'Melhoria física da visão humana', FALSE, 3),
      ('O que é Big Data?', 'Um aplicativo de mensagens', FALSE, 0),
      ('O que é Big Data?', 'Grande volume de dados que exige tecnologias específicas para processamento e análise', TRUE, 1),
      ('O que é Big Data?', 'Um antivírus', FALSE, 2),
      ('O que é Big Data?', 'Um disco rígido maior', FALSE, 3),
      ('O que significa análise de dados?', 'Criação de vírus', FALSE, 0),
      ('O que significa análise de dados?', 'Instalação de hardware', FALSE, 1),
      ('O que significa análise de dados?', 'Exclusão de arquivos', FALSE, 2),
      ('O que significa análise de dados?', 'Processo de examinar dados para obter informações úteis e apoiar decisões', TRUE, 3),
      ('O que é mineração de dados?', 'Processo de descobrir padrões e informações relevantes em grandes conjuntos de dados', TRUE, 0),
      ('O que é mineração de dados?', 'Criar redes Wi-Fi', FALSE, 1),
      ('O que é mineração de dados?', 'Extrair metais de computadores', FALSE, 2),
      ('O que é mineração de dados?', 'Apagar bancos de dados', FALSE, 3),
      ('O que é blockchain em termos tecnológicos?', 'Uma memória externa', FALSE, 0),
      ('O que é blockchain em termos tecnológicos?', 'Um navegador', FALSE, 1),
      ('O que é blockchain em termos tecnológicos?', 'Um antivírus', FALSE, 2),
      ('O que é blockchain em termos tecnológicos?', 'Estrutura distribuída de registros organizados em blocos conectados e protegidos por criptografia', TRUE, 3),
      ('O que é um contrato inteligente (smart contract)?', 'Programa executado em uma blockchain que realiza ações conforme regras definidas', TRUE, 0),
      ('O que é um contrato inteligente (smart contract)?', 'Contrato impresso em papel', FALSE, 1),
      ('O que é um contrato inteligente (smart contract)?', 'Senha digital', FALSE, 2),
      ('O que é um contrato inteligente (smart contract)?', 'Documento enviado por email', FALSE, 3),
      ('O que é edge computing?', 'Armazenamento apenas em servidores distantes', FALSE, 0),
      ('O que é edge computing?', 'Sistema operacional móvel', FALSE, 1),
      ('O que é edge computing?', 'Exclusão automática de dados', FALSE, 2),
      ('O que é edge computing?', 'Processamento de dados próximo ao local onde eles são gerados', TRUE, 3),
      ('Qual é uma vantagem do edge computing?', 'Impede análise de dados', FALSE, 0),
      ('Qual é uma vantagem do edge computing?', 'Elimina toda necessidade de internet', FALSE, 1),
      ('Qual é uma vantagem do edge computing?', 'Remove todos os servidores', FALSE, 2),
      ('Qual é uma vantagem do edge computing?', 'Pode reduzir latência ao processar dados mais próximos do usuário ou dispositivo', TRUE, 3),
      ('O que é baixa latência?', 'Baixa qualidade de imagem', FALSE, 0),
      ('O que é baixa latência?', 'Pequeno atraso na comunicação ou processamento de dados', TRUE, 1),
      ('O que é baixa latência?', 'Pouco espaço de armazenamento', FALSE, 2),
      ('O que é baixa latência?', 'Pouca memória RAM', FALSE, 3),
      ('O que é arquitetura de microsserviços?', 'Modelo onde uma aplicação é dividida em pequenos serviços independentes que comunicam entre si', TRUE, 0),
      ('O que é arquitetura de microsserviços?', 'Sistema de impressão', FALSE, 1),
      ('O que é arquitetura de microsserviços?', 'Tipo de teclado', FALSE, 2),
      ('O que é arquitetura de microsserviços?', 'Programa instalado em um único arquivo', FALSE, 3),
      ('Qual é uma vantagem dos microsserviços?', 'Permitir desenvolvimento e atualização independente de diferentes partes de uma aplicação', TRUE, 0),
      ('Qual é uma vantagem dos microsserviços?', 'Impedir alterações', FALSE, 1),
      ('Qual é uma vantagem dos microsserviços?', 'Eliminar servidores', FALSE, 2),
      ('Qual é uma vantagem dos microsserviços?', 'Remover bancos de dados', FALSE, 3),
      ('O que é escalabilidade em sistemas?', 'Exclusão de dados', FALSE, 0),
      ('O que é escalabilidade em sistemas?', 'Redução obrigatória de funções', FALSE, 1),
      ('O que é escalabilidade em sistemas?', 'Capacidade de um sistema lidar com aumento de usuários ou demanda', TRUE, 2),
      ('O que é escalabilidade em sistemas?', 'Capacidade de desligar servidores', FALSE, 3),
      ('O que é escalabilidade horizontal?', 'Adicionar mais máquinas ou instâncias para aumentar capacidade', TRUE, 0),
      ('O que é escalabilidade horizontal?', 'Aumentar apenas a memória de uma máquina', FALSE, 1),
      ('O que é escalabilidade horizontal?', 'Apagar serviços', FALSE, 2),
      ('O que é escalabilidade horizontal?', 'Reduzir usuários', FALSE, 3),
      ('O que é escalabilidade vertical?', 'Aumentar recursos de uma máquina existente, como CPU ou memória', TRUE, 0),
      ('O que é escalabilidade vertical?', 'Criar novos domínios', FALSE, 1),
      ('O que é escalabilidade vertical?', 'Adicionar novos usuários', FALSE, 2),
      ('O que é escalabilidade vertical?', 'Remover servidores', FALSE, 3),
      ('O que é observabilidade em sistemas?', 'Velocidade do teclado', FALSE, 0),
      ('O que é observabilidade em sistemas?', 'Capacidade de entender o estado interno de um sistema através de dados como logs, métricas e rastreamentos', TRUE, 1),
      ('O que é observabilidade em sistemas?', 'Visualização da tela', FALSE, 2),
      ('O que é observabilidade em sistemas?', 'Qualidade da câmera', FALSE, 3),
      ('O que são logs em sistemas?', 'Arquivos de imagem', FALSE, 0),
      ('O que são logs em sistemas?', 'Registros de eventos e atividades realizados por aplicações ou sistemas', TRUE, 1),
      ('O que são logs em sistemas?', 'Senhas públicas', FALSE, 2),
      ('O que são logs em sistemas?', 'Componentes físicos', FALSE, 3),
      ('O que é uma vulnerabilidade de software?', 'Falha que pode permitir comportamentos inesperados ou exploração por atacantes', TRUE, 0),
      ('O que é uma vulnerabilidade de software?', 'Uma melhoria de desempenho', FALSE, 1),
      ('O que é uma vulnerabilidade de software?', 'Uma atualização normal', FALSE, 2),
      ('O que é uma vulnerabilidade de software?', 'Um novo recurso', FALSE, 3),
      ('O que é teste de penetração (pentest)?', 'Instalação de jogos', FALSE, 0),
      ('O que é teste de penetração (pentest)?', 'Avaliação de segurança simulando ataques controlados para identificar vulnerabilidades', TRUE, 1),
      ('O que é teste de penetração (pentest)?', 'Teste de velocidade da internet', FALSE, 2),
      ('O que é teste de penetração (pentest)?', 'Formatação de computador', FALSE, 3),
      ('O que é Zero Trust em segurança?', 'Rede totalmente aberta', FALSE, 0),
      ('O que é Zero Trust em segurança?', 'Sistema sem autenticação', FALSE, 1),
      ('O que é Zero Trust em segurança?', 'Modelo que assume que nenhuma entidade deve ser automaticamente confiável sem verificação', TRUE, 2),
      ('O que é Zero Trust em segurança?', 'Método de armazenamento', FALSE, 3),
      ('O que é API Gateway?', 'Um banco de dados físico', FALSE, 0),
      ('O que é API Gateway?', 'Um processador', FALSE, 1),
      ('O que é API Gateway?', 'Componente que gerencia e controla acesso a APIs em uma arquitetura de sistemas', TRUE, 2),
      ('O que é API Gateway?', 'Um antivírus', FALSE, 3),
      ('Por que a segurança da informação é importante?', 'Apenas para aumentar armazenamento', FALSE, 0),
      ('Por que a segurança da informação é importante?', 'Para proteger dados, sistemas e usuários contra acessos indevidos, perdas ou ataques', TRUE, 1),
      ('Por que a segurança da informação é importante?', 'Apenas para criar aplicativos', FALSE, 2),
      ('Por que a segurança da informação é importante?', 'Apenas para melhorar gráficos', FALSE, 3)
    ) AS a(statement, label, is_correct, display_order)
    ON q.statement = a.statement;

    DROP TABLE tmp_new_questions_tec_dificil;

    RAISE NOTICE '50 perguntas inseridas com sucesso (source=seed_tecnologia_dificil_v1).';
  END IF;
END $$;

COMMIT;
