-- Migration/seed: conteúdo Finanças, nível Fácil — lote 2 (63 de 67 perguntas)
-- Fonte: novo lote de 67 perguntas de Finanças/Fácil fornecido pelo
-- proprietário do projeto (numeradas 1–67, em 3 mensagens separadas).
--
-- DEDUPLICAÇÃO APLICADA: comparei texto a texto contra as 33 perguntas já
-- existentes em 015_financas_facil.sql e encontrei 4 repetidas, que foram
-- REMOVIDAS deste arquivo (não inseridas de novo):
--   - "O que é dinheiro?"
--   - "O que é renda?"
--   - "O que é consumo?"
--   - "O que é uma compra planejada?"
-- Sobraram 63 perguntas novas e únicas, inseridas aqui.
--
-- CORREÇÃO DE QUALIDADE APLICADA (mesma higiene de dado dos lotes
-- anteriores, não é decisão de negócio): no lote original, as respostas
-- corretas eram TODAS a alternativa "A" — decorável sem conhecimento real.
-- A posição da alternativa correta foi redistribuída por pergunta com seed
-- fixa (73 — distinta das seeds 42 a 72 já usadas) e distribuição
-- controlada entre A/B/C/D, reprodutível — o conteúdo pedagógico permanece
-- exatamente como enviado, só a ORDEM de exibição mudou.
--
-- Idempotente: usa a coluna `source` (migration 022) como marcador — rodar
-- este arquivo mais de uma vez não duplica as perguntas.
--
-- CORREÇÃO DE DUPLICATA CRUZADA (rodada de consolidação): 4 perguntas deste
-- arquivo já existiam em outros arquivos de Finanças/Marketing — "O que é
-- crédito?", "O que é inflação?", "O que é juros?" (já em
-- 016_financas_medio.sql) e "O que é desconto?" (já em
-- 018_marketing_digital_facil_2.sql). Removidas daqui. 63 → 59 perguntas.

BEGIN;

DO $$
DECLARE
  v_category_id UUID;
BEGIN
  SELECT id INTO v_category_id FROM categories WHERE slug = 'financas';
  IF v_category_id IS NULL THEN
    RAISE EXCEPTION 'Categoria "financas" não encontrada — rode a migration 021 primeiro.';
  END IF;

  IF EXISTS (SELECT 1 FROM questions WHERE source = 'seed_financas_facil_v2') THEN
    RAISE NOTICE 'Perguntas já foram inseridas anteriormente (source=seed_financas_facil_v2) — nada a fazer.';
  ELSE

    CREATE TEMP TABLE tmp_new_questions_fin_facil_v2 AS
    WITH inserted AS (
    INSERT INTO questions (category_id, difficulty, statement, time_limit_seconds, xp_reward, source)
    SELECT v_category_id, 'easy', v.statement, 15, 10, 'seed_financas_facil_v2'
    FROM (VALUES
      ('O que são finanças?'),
      ('O que é uma receita financeira?'),
      ('O que é uma despesa?'),
      ('O que significa economizar dinheiro?'),
      ('O que é orçamento pessoal?'),
      ('Por que criar um orçamento?'),
      ('O que é poupança?'),
      ('O que é um banco?'),
      ('O que é uma conta bancária?'),
      ('O que é cartão de débito?'),
      ('O que é cartão de crédito?'),
      ('O que é dívida?'),
      ('O que é lucro?'),
      ('O que é prejuízo?'),
      ('O que é investimento?'),
      ('O que é salário?'),
      ('O que é consumo consciente?'),
      ('O que é planejamento financeiro?'),
      ('O que é uma meta financeira?'),
      ('O que é emergência financeira?'),
      ('O que é reserva de emergência?'),
      ('O que é uma necessidade financeira?'),
      ('O que é um desejo financeiro?'),
      ('Qual é a diferença entre necessidade e desejo?'),
      ('Como a inflação pode afetar o dinheiro?'),
      ('O que é poder de compra?'),
      ('O que acontece quando alguém atrasa um pagamento?'),
      ('O que é uma despesa fixa?'),
      ('Qual exemplo representa uma despesa fixa?'),
      ('O que é uma despesa variável?'),
      ('Qual exemplo representa uma despesa variável?'),
      ('O que é saldo bancário?'),
      ('O que é extrato bancário?'),
      ('O que é transferência bancária?'),
      ('O que é pagamento digital?'),
      ('Qual é um exemplo de pagamento digital?'),
      ('O que é carteira digital?'),
      ('O que é M-Pesa?'),
      ('O que é uma transação financeira?'),
      ('O que é compra por impulso?'),
      ('Por que comparar preços é importante?'),
      ('O que é promoção financeira?'),
      ('O que é um objetivo financeiro de curto prazo?'),
      ('O que é um objetivo financeiro de longo prazo?'),
      ('Por que é importante definir metas financeiras?'),
      ('O que é disciplina financeira?'),
      ('O que é educação financeira?'),
      ('Por que a educação financeira é importante?'),
      ('O que é um hábito financeiro?'),
      ('Qual hábito ajuda na organização financeira?'),
      ('O que é controle financeiro?'),
      ('O que é planejamento de gastos?'),
      ('O que é uma fonte de renda?'),
      ('Qual exemplo representa uma fonte de renda?'),
      ('O que é renda extra?'),
      ('Qual é uma forma de aumentar a renda?'),
      ('O que é responsabilidade financeira?'),
      ('O que é segurança financeira?'),
      ('Qual é o primeiro passo para melhorar a vida financeira?')
    ) AS v(statement)
    RETURNING id, statement
    )
    SELECT * FROM inserted;

    INSERT INTO question_alternatives (question_id, label, is_correct, display_order)
    SELECT q.id, a.label, a.is_correct, a.display_order
    FROM tmp_new_questions_fin_facil_v2 q
    JOIN (VALUES
      ('O que são finanças?', 'Gestão do dinheiro e dos recursos financeiros', TRUE, 0),
      ('O que são finanças?', 'Apenas guardar documentos', FALSE, 1),
      ('O que são finanças?', 'Criar aplicativos', FALSE, 2),
      ('O que são finanças?', 'Consertar computadores', FALSE, 3),
      ('O que é uma receita financeira?', 'Valor que uma pessoa ou empresa recebe', TRUE, 0),
      ('O que é uma receita financeira?', 'Uma despesa', FALSE, 1),
      ('O que é uma receita financeira?', 'Valor que uma pessoa perde', FALSE, 2),
      ('O que é uma receita financeira?', 'Um empréstimo obrigatório', FALSE, 3),
      ('O que é uma despesa?', 'Dinheiro recebido', FALSE, 0),
      ('O que é uma despesa?', 'Dinheiro utilizado para pagar algo', TRUE, 1),
      ('O que é uma despesa?', 'Lucro de uma empresa', FALSE, 2),
      ('O que é uma despesa?', 'Investimento sempre lucrativo', FALSE, 3),
      ('O que significa economizar dinheiro?', 'Fazer dívidas', FALSE, 0),
      ('O que significa economizar dinheiro?', 'Guardar parte do dinheiro para uso futuro', TRUE, 1),
      ('O que significa economizar dinheiro?', 'Evitar qualquer compra', FALSE, 2),
      ('O que significa economizar dinheiro?', 'Gastar tudo imediatamente', FALSE, 3),
      ('O que é orçamento pessoal?', 'Programa de computador', FALSE, 0),
      ('O que é orçamento pessoal?', 'Planejamento das receitas e despesas de uma pessoa', TRUE, 1),
      ('O que é orçamento pessoal?', 'Lista de amigos', FALSE, 2),
      ('O que é orçamento pessoal?', 'Documento de identidade', FALSE, 3),
      ('Por que criar um orçamento?', 'Para controlar melhor o dinheiro', TRUE, 0),
      ('Por que criar um orçamento?', 'Para aumentar despesas', FALSE, 1),
      ('Por que criar um orçamento?', 'Para perder dinheiro', FALSE, 2),
      ('Por que criar um orçamento?', 'Para evitar qualquer rendimento', FALSE, 3),
      ('O que é poupança?', 'Uma dívida', FALSE, 0),
      ('O que é poupança?', 'Um imposto', FALSE, 1),
      ('O que é poupança?', 'Dinheiro perdido', FALSE, 2),
      ('O que é poupança?', 'Dinheiro guardado para objetivos futuros', TRUE, 3),
      ('O que é um banco?', 'Instituição que oferece serviços financeiros', TRUE, 0),
      ('O que é um banco?', 'Loja de computadores', FALSE, 1),
      ('O que é um banco?', 'Empresa de jogos', FALSE, 2),
      ('O que é um banco?', 'Rede social', FALSE, 3),
      ('O que é uma conta bancária?', 'Um documento escolar', FALSE, 0),
      ('O que é uma conta bancária?', 'Serviço usado para guardar e movimentar dinheiro', TRUE, 1),
      ('O que é uma conta bancária?', 'Um aplicativo de edição', FALSE, 2),
      ('O que é uma conta bancária?', 'Um cartão de memória', FALSE, 3),
      ('O que é cartão de débito?', 'Cartão de internet', FALSE, 0),
      ('O que é cartão de débito?', 'Cartão que utiliza dinheiro disponível na conta', TRUE, 1),
      ('O que é cartão de débito?', 'Cartão que cria dinheiro', FALSE, 2),
      ('O que é cartão de débito?', 'Cartão sem ligação bancária', FALSE, 3),
      ('O que é cartão de crédito?', 'Conta de poupança', FALSE, 0),
      ('O que é cartão de crédito?', 'Um investimento', FALSE, 1),
      ('O que é cartão de crédito?', 'Meio de pagamento que permite comprar usando limite concedido pelo banco', TRUE, 2),
      ('O que é cartão de crédito?', 'Dinheiro gratuito', FALSE, 3),
      ('O que é dívida?', 'Dinheiro recebido gratuitamente', FALSE, 0),
      ('O que é dívida?', 'Um lucro', FALSE, 1),
      ('O que é dívida?', 'Um investimento', FALSE, 2),
      ('O que é dívida?', 'Valor que uma pessoa deve pagar', TRUE, 3),
      ('O que é lucro?', 'Toda despesa realizada', FALSE, 0),
      ('O que é lucro?', 'Uma perda', FALSE, 1),
      ('O que é lucro?', 'Um empréstimo', FALSE, 2),
      ('O que é lucro?', 'Resultado positivo quando receitas são maiores que despesas', TRUE, 3),
      ('O que é prejuízo?', 'Economia mensal', FALSE, 0),
      ('O que é prejuízo?', 'Investimento seguro', FALSE, 1),
      ('O que é prejuízo?', 'Aumento de dinheiro', FALSE, 2),
      ('O que é prejuízo?', 'Resultado negativo quando despesas superam receitas', TRUE, 3),
      ('O que é investimento?', 'Perder dinheiro propositalmente', FALSE, 0),
      ('O que é investimento?', 'Fazer compras diárias', FALSE, 1),
      ('O que é investimento?', 'Aplicação de dinheiro buscando retorno futuro', TRUE, 2),
      ('O que é investimento?', 'Gastar sem objetivo', FALSE, 3),
      ('O que é salário?', 'Um empréstimo', FALSE, 0),
      ('O que é salário?', 'Um imposto', FALSE, 1),
      ('O que é salário?', 'Uma dívida', FALSE, 2),
      ('O que é salário?', 'Pagamento recebido pelo trabalho realizado', TRUE, 3),
      ('O que é consumo consciente?', 'Comprar considerando necessidade e capacidade financeira', TRUE, 0),
      ('O que é consumo consciente?', 'Comprar tudo sem planejamento', FALSE, 1),
      ('O que é consumo consciente?', 'Fazer dívidas sempre', FALSE, 2),
      ('O que é consumo consciente?', 'Gastar todo dinheiro', FALSE, 3),
      ('O que é planejamento financeiro?', 'Organização das decisões relacionadas ao dinheiro', TRUE, 0),
      ('O que é planejamento financeiro?', 'Evitar qualquer controle', FALSE, 1),
      ('O que é planejamento financeiro?', 'Gastar sem pensar', FALSE, 2),
      ('O que é planejamento financeiro?', 'Fazer apenas empréstimos', FALSE, 3),
      ('O que é uma meta financeira?', 'Objetivo relacionado ao uso do dinheiro', TRUE, 0),
      ('O que é uma meta financeira?', 'Um cartão bancário', FALSE, 1),
      ('O que é uma meta financeira?', 'Uma dívida obrigatória', FALSE, 2),
      ('O que é uma meta financeira?', 'Uma despesa', FALSE, 3),
      ('O que é emergência financeira?', 'Investimento', FALSE, 0),
      ('O que é emergência financeira?', 'Compra planejada', FALSE, 1),
      ('O que é emergência financeira?', 'Situação inesperada que exige dinheiro', TRUE, 2),
      ('O que é emergência financeira?', 'Salário mensal', FALSE, 3),
      ('O que é reserva de emergência?', 'Dívida bancária', FALSE, 0),
      ('O que é reserva de emergência?', 'Imposto', FALSE, 1),
      ('O que é reserva de emergência?', 'Dinheiro para gastar rapidamente', FALSE, 2),
      ('O que é reserva de emergência?', 'Dinheiro guardado para situações inesperadas', TRUE, 3),
      ('O que é uma necessidade financeira?', 'Algo essencial para a vida ou funcionamento de uma pessoa', TRUE, 0),
      ('O que é uma necessidade financeira?', 'Um luxo obrigatório', FALSE, 1),
      ('O que é uma necessidade financeira?', 'Um gasto sem importância', FALSE, 2),
      ('O que é uma necessidade financeira?', 'Uma compra por impulso', FALSE, 3),
      ('O que é um desejo financeiro?', 'Uma dívida bancária', FALSE, 0),
      ('O que é um desejo financeiro?', 'Uma receita mensal', FALSE, 1),
      ('O que é um desejo financeiro?', 'Algo que queremos, mas não é essencial', TRUE, 2),
      ('O que é um desejo financeiro?', 'Uma obrigação de pagamento', FALSE, 3),
      ('Qual é a diferença entre necessidade e desejo?', 'Necessidade sempre custa mais', FALSE, 0),
      ('Qual é a diferença entre necessidade e desejo?', 'Desejo sempre é mais importante', FALSE, 1),
      ('Qual é a diferença entre necessidade e desejo?', 'Não existe diferença', FALSE, 2),
      ('Qual é a diferença entre necessidade e desejo?', 'Necessidade é essencial; desejo é algo opcional', TRUE, 3),
      ('Como a inflação pode afetar o dinheiro?', 'Pode reduzir o poder de compra', TRUE, 0),
      ('Como a inflação pode afetar o dinheiro?', 'Elimina despesas', FALSE, 1),
      ('Como a inflação pode afetar o dinheiro?', 'Sempre aumenta o valor do dinheiro', FALSE, 2),
      ('Como a inflação pode afetar o dinheiro?', 'Faz produtos ficarem gratuitos', FALSE, 3),
      ('O que é poder de compra?', 'Número de cartões bancários', FALSE, 0),
      ('O que é poder de compra?', 'Valor de uma dívida', FALSE, 1),
      ('O que é poder de compra?', 'Quantidade de dinheiro guardado', FALSE, 2),
      ('O que é poder de compra?', 'Capacidade de adquirir produtos e serviços com determinado valor', TRUE, 3),
      ('O que acontece quando alguém atrasa um pagamento?', 'Recebe sempre desconto', FALSE, 0),
      ('O que acontece quando alguém atrasa um pagamento?', 'A dívida desaparece', FALSE, 1),
      ('O que acontece quando alguém atrasa um pagamento?', 'Pode pagar juros ou multas', TRUE, 2),
      ('O que acontece quando alguém atrasa um pagamento?', 'Ganha investimento', FALSE, 3),
      ('O que é uma despesa fixa?', 'Investimento', FALSE, 0),
      ('O que é uma despesa fixa?', 'Receita extra', FALSE, 1),
      ('O que é uma despesa fixa?', 'Despesa que nunca existe', FALSE, 2),
      ('O que é uma despesa fixa?', 'Despesa que acontece regularmente com valor semelhante', TRUE, 3),
      ('Qual exemplo representa uma despesa fixa?', 'Presente ocasional', FALSE, 0),
      ('Qual exemplo representa uma despesa fixa?', 'Viagem aleatória', FALSE, 1),
      ('Qual exemplo representa uma despesa fixa?', 'Compra inesperada', FALSE, 2),
      ('Qual exemplo representa uma despesa fixa?', 'Aluguel mensal', TRUE, 3),
      ('O que é uma despesa variável?', 'Salário fixo', FALSE, 0),
      ('O que é uma despesa variável?', 'Investimento garantido', FALSE, 1),
      ('O que é uma despesa variável?', 'Gasto que pode mudar de valor conforme o período', TRUE, 2),
      ('O que é uma despesa variável?', 'Conta bancária', FALSE, 3),
      ('Qual exemplo representa uma despesa variável?', 'Alimentação e lazer', TRUE, 0),
      ('Qual exemplo representa uma despesa variável?', 'Salário', FALSE, 1),
      ('Qual exemplo representa uma despesa variável?', 'Mensalidade igual', FALSE, 2),
      ('Qual exemplo representa uma despesa variável?', 'Contrato fixo', FALSE, 3),
      ('O que é saldo bancário?', 'Um imposto', FALSE, 0),
      ('O que é saldo bancário?', 'Uma dívida', FALSE, 1),
      ('O que é saldo bancário?', 'Um investimento obrigatório', FALSE, 2),
      ('O que é saldo bancário?', 'Valor disponível em uma conta', TRUE, 3),
      ('O que é extrato bancário?', 'Cartão de crédito', FALSE, 0),
      ('O que é extrato bancário?', 'Documento escolar', FALSE, 1),
      ('O que é extrato bancário?', 'Documento que mostra movimentações de uma conta', TRUE, 2),
      ('O que é extrato bancário?', 'Contrato de trabalho', FALSE, 3),
      ('O que é transferência bancária?', 'Empréstimo automático', FALSE, 0),
      ('O que é transferência bancária?', 'Criação de dinheiro', FALSE, 1),
      ('O que é transferência bancária?', 'Envio de dinheiro de uma conta para outra', TRUE, 2),
      ('O que é transferência bancária?', 'Cancelamento de conta', FALSE, 3),
      ('O que é pagamento digital?', 'Pagamento apenas em dinheiro físico', FALSE, 0),
      ('O que é pagamento digital?', 'Uma dívida', FALSE, 1),
      ('O que é pagamento digital?', 'Troca de produtos', FALSE, 2),
      ('O que é pagamento digital?', 'Pagamento realizado usando meios eletrônicos', TRUE, 3),
      ('Qual é um exemplo de pagamento digital?', 'Troca de moedas antigas', FALSE, 0),
      ('Qual é um exemplo de pagamento digital?', 'Pagamento por aplicativo bancário', TRUE, 1),
      ('Qual é um exemplo de pagamento digital?', 'Documento impresso', FALSE, 2),
      ('Qual é um exemplo de pagamento digital?', 'Pagamento sem valor', FALSE, 3),
      ('O que é carteira digital?', 'Cartão de memória', FALSE, 0),
      ('O que é carteira digital?', 'Banco tradicional somente', FALSE, 1),
      ('O que é carteira digital?', 'Aplicativo que permite armazenar e movimentar valores', TRUE, 2),
      ('O que é carteira digital?', 'Carteira física de documentos', FALSE, 3),
      ('O que é M-Pesa?', 'Um cartão de computador', FALSE, 0),
      ('O que é M-Pesa?', 'Serviço de dinheiro móvel para realizar pagamentos e transferências', TRUE, 1),
      ('O que é M-Pesa?', 'Uma rede social', FALSE, 2),
      ('O que é M-Pesa?', 'Um investimento', FALSE, 3),
      ('O que é uma transação financeira?', 'Instalação de programas', FALSE, 0),
      ('O que é uma transação financeira?', 'Apenas guardar documentos', FALSE, 1),
      ('O que é uma transação financeira?', 'Operação envolvendo movimentação de dinheiro', TRUE, 2),
      ('O que é uma transação financeira?', 'Criação de contas falsas', FALSE, 3),
      ('O que é compra por impulso?', 'Compra com orçamento definido', FALSE, 0),
      ('O que é compra por impulso?', 'Pagamento de dívida', FALSE, 1),
      ('O que é compra por impulso?', 'Compra realizada sem planejamento prévio', TRUE, 2),
      ('O que é compra por impulso?', 'Investimento seguro', FALSE, 3),
      ('Por que comparar preços é importante?', 'Para evitar planejamento', FALSE, 0),
      ('Por que comparar preços é importante?', 'Para encontrar melhores opções e economizar', TRUE, 1),
      ('Por que comparar preços é importante?', 'Para aumentar gastos', FALSE, 2),
      ('Por que comparar preços é importante?', 'Para criar dívidas', FALSE, 3),
      ('O que é promoção financeira?', 'Oferta temporária que reduz o preço ou oferece vantagem', TRUE, 0),
      ('O que é promoção financeira?', 'Um empréstimo obrigatório', FALSE, 1),
      ('O que é promoção financeira?', 'Uma conta bancária', FALSE, 2),
      ('O que é promoção financeira?', 'Um investimento de risco', FALSE, 3),
      ('O que é um objetivo financeiro de curto prazo?', 'Uma dívida permanente', FALSE, 0),
      ('O que é um objetivo financeiro de curto prazo?', 'Meta para muitos anos obrigatoriamente', FALSE, 1),
      ('O que é um objetivo financeiro de curto prazo?', 'Um gasto sem planejamento', FALSE, 2),
      ('O que é um objetivo financeiro de curto prazo?', 'Meta que pode ser alcançada em pouco tempo', TRUE, 3),
      ('O que é um objetivo financeiro de longo prazo?', 'Compra imediata sem análise', FALSE, 0),
      ('O que é um objetivo financeiro de longo prazo?', 'Meta que exige mais tempo e planejamento para alcançar', TRUE, 1),
      ('O que é um objetivo financeiro de longo prazo?', 'Pequeno gasto diário', FALSE, 2),
      ('O que é um objetivo financeiro de longo prazo?', 'Pagamento de uma conta simples', FALSE, 3),
      ('Por que é importante definir metas financeiras?', 'Para orientar o uso do dinheiro e facilitar decisões', TRUE, 0),
      ('Por que é importante definir metas financeiras?', 'Para aumentar dívidas', FALSE, 1),
      ('Por que é importante definir metas financeiras?', 'Para gastar sem controle', FALSE, 2),
      ('Por que é importante definir metas financeiras?', 'Para evitar economizar', FALSE, 3),
      ('O que é disciplina financeira?', 'Gastar todos os recursos disponíveis', FALSE, 0),
      ('O que é disciplina financeira?', 'Evitar qualquer controle', FALSE, 1),
      ('O que é disciplina financeira?', 'Fazer compras constantes', FALSE, 2),
      ('O que é disciplina financeira?', 'Capacidade de seguir um planejamento relacionado ao dinheiro', TRUE, 3),
      ('O que é educação financeira?', 'Aprender apenas matemática', FALSE, 0),
      ('O que é educação financeira?', 'Criar contas bancárias', FALSE, 1),
      ('O que é educação financeira?', 'Conhecimento para administrar melhor o dinheiro', TRUE, 2),
      ('O que é educação financeira?', 'Guardar documentos', FALSE, 3),
      ('Por que a educação financeira é importante?', 'Elimina todos os riscos', FALSE, 0),
      ('Por que a educação financeira é importante?', 'Ajuda a tomar melhores decisões sobre dinheiro', TRUE, 1),
      ('Por que a educação financeira é importante?', 'Impede qualquer gasto', FALSE, 2),
      ('Por que a educação financeira é importante?', 'Faz todas as compras gratuitas', FALSE, 3),
      ('O que é um hábito financeiro?', 'Um cartão físico', FALSE, 0),
      ('O que é um hábito financeiro?', 'Comportamento repetido relacionado ao uso do dinheiro', TRUE, 1),
      ('O que é um hábito financeiro?', 'Um investimento obrigatório', FALSE, 2),
      ('O que é um hábito financeiro?', 'Uma dívida bancária', FALSE, 3),
      ('Qual hábito ajuda na organização financeira?', 'Registrar receitas e despesas', TRUE, 0),
      ('Qual hábito ajuda na organização financeira?', 'Fazer dívidas sem análise', FALSE, 1),
      ('Qual hábito ajuda na organização financeira?', 'Ignorar contas', FALSE, 2),
      ('Qual hábito ajuda na organização financeira?', 'Gastar sem acompanhar', FALSE, 3),
      ('O que é controle financeiro?', 'Guardar apenas cartões', FALSE, 0),
      ('O que é controle financeiro?', 'Evitar qualquer pagamento', FALSE, 1),
      ('O que é controle financeiro?', 'Acompanhamento da entrada e saída de dinheiro', TRUE, 2),
      ('O que é controle financeiro?', 'Gastar sem limites', FALSE, 3),
      ('O que é planejamento de gastos?', 'Gastar sem pensar', FALSE, 0),
      ('O que é planejamento de gastos?', 'Definir antecipadamente como o dinheiro será utilizado', TRUE, 1),
      ('O que é planejamento de gastos?', 'Criar dívidas', FALSE, 2),
      ('O que é planejamento de gastos?', 'Evitar qualquer compra', FALSE, 3),
      ('O que é uma fonte de renda?', 'Uma dívida', FALSE, 0),
      ('O que é uma fonte de renda?', 'Origem de onde uma pessoa recebe dinheiro', TRUE, 1),
      ('O que é uma fonte de renda?', 'Um imposto', FALSE, 2),
      ('O que é uma fonte de renda?', 'Uma despesa', FALSE, 3),
      ('Qual exemplo representa uma fonte de renda?', 'Salário ou negócio próprio', TRUE, 0),
      ('Qual exemplo representa uma fonte de renda?', 'Conta de energia', FALSE, 1),
      ('Qual exemplo representa uma fonte de renda?', 'Compra de roupa', FALSE, 2),
      ('Qual exemplo representa uma fonte de renda?', 'Pagamento de dívida', FALSE, 3),
      ('O que é renda extra?', 'Uma dívida adicional', FALSE, 0),
      ('O que é renda extra?', 'Uma despesa fixa', FALSE, 1),
      ('O que é renda extra?', 'Dinheiro recebido além da renda principal', TRUE, 2),
      ('O que é renda extra?', 'Um imposto', FALSE, 3),
      ('Qual é uma forma de aumentar a renda?', 'Gastar mais dinheiro', FALSE, 0),
      ('Qual é uma forma de aumentar a renda?', 'Criar novas fontes de ganhos', TRUE, 1),
      ('Qual é uma forma de aumentar a renda?', 'Ignorar oportunidades', FALSE, 2),
      ('Qual é uma forma de aumentar a renda?', 'Fazer dívidas', FALSE, 3),
      ('O que é responsabilidade financeira?', 'Evitar qualquer controle', FALSE, 0),
      ('O que é responsabilidade financeira?', 'Comprar sempre por impulso', FALSE, 1),
      ('O que é responsabilidade financeira?', 'Usar o dinheiro de forma consciente e planejada', TRUE, 2),
      ('O que é responsabilidade financeira?', 'Gastar sem limites', FALSE, 3),
      ('O que é segurança financeira?', 'Situação em que uma pessoa possui maior controle e estabilidade financeira', TRUE, 0),
      ('O que é segurança financeira?', 'Não possuir planejamento', FALSE, 1),
      ('O que é segurança financeira?', 'Ter muitas dívidas', FALSE, 2),
      ('O que é segurança financeira?', 'Gastar todo dinheiro', FALSE, 3),
      ('Qual é o primeiro passo para melhorar a vida financeira?', 'Ignorar receitas e despesas', FALSE, 0),
      ('Qual é o primeiro passo para melhorar a vida financeira?', 'Conhecer sua situação financeira atual', TRUE, 1),
      ('Qual é o primeiro passo para melhorar a vida financeira?', 'Gastar sem analisar', FALSE, 2),
      ('Qual é o primeiro passo para melhorar a vida financeira?', 'Fazer muitas dívidas', FALSE, 3)
    ) AS a(statement, label, is_correct, display_order)
    ON q.statement = a.statement;

    DROP TABLE tmp_new_questions_fin_facil_v2;

    RAISE NOTICE '59 perguntas inseridas com sucesso (source=seed_financas_facil_v2).';
  END IF;
END $$;

COMMIT;
