-- Migration/seed: conteúdo Inteligência Artificial, nível Médio — lote 3 (63 de 65 perguntas)
-- Fonte: novo lote de 65 perguntas de Inteligência Artificial/Médio
-- fornecido pelo proprietário do projeto.
--
-- DEDUPLICAÇÃO APLICADA: "O que caracteriza o aprendizado não
-- supervisionado?" e "O que é uma rede neural artificial?" já existiam no
-- banco e foram removidas deste arquivo. Sobraram 63 perguntas novas.
--
-- CORREÇÃO DE QUALIDADE APLICADA (mesma higiene de dado dos lotes
-- anteriores): este lote já vem com respostas mais variadas entre A/B/C/D.
-- Ainda assim, para manter consistência com o resto do banco, a posição da
-- alternativa correta (preservando o texto correto do documento original)
-- foi redistribuída por pergunta com seed fixa (85 — distinta das seeds 42
-- a 84 já usadas) e distribuição controlada entre A/B/C/D. Conteúdo
-- pedagógico inalterado, só a ORDEM de exibição mudou.
--
-- Idempotente: usa a coluna `source` (migration 022) como marcador — rodar
-- este arquivo mais de uma vez não duplica as perguntas.

BEGIN;

DO $$
DECLARE
  v_category_id UUID;
BEGIN
  SELECT id INTO v_category_id FROM categories WHERE slug = 'inteligencia-artificial';
  IF v_category_id IS NULL THEN
    RAISE EXCEPTION 'Categoria "inteligencia-artificial" não encontrada — rode a migration 021 primeiro.';
  END IF;

  IF EXISTS (SELECT 1 FROM questions WHERE source = 'seed_ia_medio_v3') THEN
    RAISE NOTICE 'Perguntas já foram inseridas anteriormente (source=seed_ia_medio_v3) — nada a fazer.';
  ELSE

    CREATE TEMP TABLE tmp_new_questions_ia_medio_v3 AS
    WITH inserted AS (
    INSERT INTO questions (category_id, difficulty, statement, time_limit_seconds, xp_reward, source)
    SELECT v_category_id, 'medium', v.statement, 15, 10, 'seed_ia_medio_v3'
    FROM (VALUES
      ('Qual é a principal diferença entre um sistema baseado em regras e um sistema de aprendizado de máquina?'),
      ('Durante o treinamento de um modelo, para que serve o conjunto de validação?'),
      ('O que caracteriza o overfitting?'),
      ('Qual situação representa melhor underfitting?'),
      ('Por que separar dados de treinamento e teste é importante?'),
      ('O que significa generalização em aprendizado de máquina?'),
      ('Um modelo apresenta 99% de precisão no treinamento e 65% em dados novos. Qual hipótese deve ser investigada primeiro?'),
      ('O que é uma variável ou característica utilizada por um modelo para fazer uma previsão?'),
      ('Num sistema que prevê o preço de uma casa usando área, localização e número de quartos, esses elementos são exemplos de:'),
      ('Em um problema de classificação, o que normalmente se pretende prever?'),
      ('Qual exemplo representa um problema de regressão?'),
      ('Qual exemplo representa classificação binária?'),
      ('O que é aprendizado supervisionado?'),
      ('Qual tarefa é típica do aprendizado não supervisionado?'),
      ('O que é clustering?'),
      ('Uma empresa divide seus clientes em grupos com comportamentos semelhantes sem definir previamente os grupos. Qual técnica pode ser adequada?'),
      ('O que é aprendizado por reforço?'),
      ('Num sistema de aprendizado por reforço, o que representa uma recompensa?'),
      ('Um agente escolhe uma ação, recebe uma recompensa e ajusta seu comportamento. Esse processo está associado a:'),
      ('Qual é a função geral de uma camada em uma rede neural?'),
      ('O que são pesos em uma rede neural?'),
      ('Durante o treinamento, os pesos de uma rede neural normalmente:'),
      ('O que é uma função de ativação?'),
      ('Por que a não linearidade é importante em redes neurais?'),
      ('O que significa época (epoch) no treinamento de um modelo?'),
      ('Se um modelo for treinado durante muitas épocas sem controle adequado, qual risco pode aumentar?'),
      ('O que é taxa de aprendizagem (learning rate)?'),
      ('Se a taxa de aprendizagem for excessivamente alta, qual problema pode ocorrer?'),
      ('O que é uma função de perda?'),
      ('Durante o treinamento, o objetivo comum de um algoritmo de otimização é:'),
      ('O que é uma matriz de confusão?'),
      ('Em classificação, o que representa um verdadeiro positivo?'),
      ('O que representa um falso positivo?'),
      ('O que representa um falso negativo?'),
      ('Por que precisão (precision) e recall podem ser importantes?'),
      ('Em um sistema de detecção de doenças, deixar passar muitos casos positivos pode ser especialmente preocupante. Qual métrica pode receber atenção especial?'),
      ('O que significa balancear um conjunto de dados?'),
      ('Por que classes muito desequilibradas podem dificultar o treinamento?'),
      ('O que é normalização de dados?'),
      ('Por que a normalização pode ajudar determinados modelos?'),
      ('O que é engenharia de características (feature engineering)?'),
      ('Um modelo apresenta resultados ruins porque recebe informações irrelevantes e redundantes. Qual etapa pode ajudar?'),
      ('O que é redução de dimensionalidade?'),
      ('Qual pode ser uma vantagem da redução de dimensionalidade?'),
      ('O que é inferência em inteligência artificial?'),
      ('Qual é a principal diferença entre treinamento e inferência?'),
      ('O que significa latência em uma aplicação de IA?'),
      ('Por que a latência é importante num chatbot?'),
      ('O que são parâmetros de um modelo?'),
      ('Qual é uma diferença entre parâmetros e hiperparâmetros?'),
      ('Qual dos seguintes é um exemplo de hiperparâmetro?'),
      ('O que é um modelo pré-treinado?'),
      ('Qual é uma vantagem potencial de utilizar um modelo pré-treinado?'),
      ('O que é fine-tuning?'),
      ('Uma empresa adapta um modelo de linguagem geral com exemplos específicos do seu setor. Isso pode ser considerado:'),
      ('O que é um token em modelos de linguagem?'),
      ('Por que a tokenização é importante em modelos de linguagem?'),
      ('O que significa contexto em uma interação com um modelo de linguagem?'),
      ('Um utilizador fornece objetivo, público-alvo, formato e restrições numa instrução para IA. Qual é o principal benefício?'),
      ('O que é uma alucinação em um modelo generativo?'),
      ('Qual estratégia pode reduzir o risco de utilizar uma informação incorreta produzida por IA?'),
      ('O que é explicabilidade em IA?'),
      ('Por que a explicabilidade pode ser importante em sistemas de IA usados em decisões sensíveis?')
    ) AS v(statement)
    RETURNING id, statement
    )
    SELECT * FROM inserted;

    INSERT INTO question_alternatives (question_id, label, is_correct, display_order)
    SELECT q.id, a.label, a.is_correct, a.display_order
    FROM tmp_new_questions_ia_medio_v3 q
    JOIN (VALUES
      ('Qual é a principal diferença entre um sistema baseado em regras e um sistema de aprendizado de máquina?', 'Sistemas baseados em regras funcionam apenas sem computadores', FALSE, 0),
      ('Qual é a principal diferença entre um sistema baseado em regras e um sistema de aprendizado de máquina?', 'O aprendizado de máquina não utiliza dados', FALSE, 1),
      ('Qual é a principal diferença entre um sistema baseado em regras e um sistema de aprendizado de máquina?', 'Os dois sistemas são obrigatoriamente idênticos', FALSE, 2),
      ('Qual é a principal diferença entre um sistema baseado em regras e um sistema de aprendizado de máquina?', 'O sistema baseado em regras depende de regras explicitamente definidas, enquanto o aprendizado de máquina pode aprender padrões a partir de dados', TRUE, 3),
      ('Durante o treinamento de um modelo, para que serve o conjunto de validação?', 'Avaliar e orientar ajustes do modelo durante o desenvolvimento', TRUE, 0),
      ('Durante o treinamento de um modelo, para que serve o conjunto de validação?', 'Armazenar exclusivamente dados pessoais', FALSE, 1),
      ('Durante o treinamento de um modelo, para que serve o conjunto de validação?', 'Executar o modelo apenas depois da publicação', FALSE, 2),
      ('Durante o treinamento de um modelo, para que serve o conjunto de validação?', 'Substituir completamente os dados de treinamento', FALSE, 3),
      ('O que caracteriza o overfitting?', 'O modelo aprende excessivamente os padrões específicos dos dados de treinamento e perde capacidade de generalização', TRUE, 0),
      ('O que caracteriza o overfitting?', 'O modelo não possui parâmetros', FALSE, 1),
      ('O que caracteriza o overfitting?', 'O modelo não consegue processar nenhuma informação', FALSE, 2),
      ('O que caracteriza o overfitting?', 'O modelo apresenta resultados ruins tanto no treino quanto em novos dados', FALSE, 3),
      ('Qual situação representa melhor underfitting?', 'O modelo apresenta excelente desempenho em qualquer conjunto', FALSE, 0),
      ('Qual situação representa melhor underfitting?', 'O modelo é demasiado simples para capturar os padrões relevantes dos dados', TRUE, 1),
      ('Qual situação representa melhor underfitting?', 'O modelo memoriza perfeitamente os exemplos de treino', FALSE, 2),
      ('Qual situação representa melhor underfitting?', 'O modelo é complexo demais para os dados', FALSE, 3),
      ('Por que separar dados de treinamento e teste é importante?', 'Para avaliar o desempenho em dados que não foram usados para treinar o modelo', TRUE, 0),
      ('Por que separar dados de treinamento e teste é importante?', 'Para aumentar artificialmente a quantidade de dados', FALSE, 1),
      ('Por que separar dados de treinamento e teste é importante?', 'Para impedir qualquer aprendizagem', FALSE, 2),
      ('Por que separar dados de treinamento e teste é importante?', 'Para eliminar a necessidade de validação', FALSE, 3),
      ('O que significa generalização em aprendizado de máquina?', 'Capacidade de aumentar o tamanho dos arquivos', FALSE, 0),
      ('O que significa generalização em aprendizado de máquina?', 'Capacidade de executar somente uma tarefa específica', FALSE, 1),
      ('O que significa generalização em aprendizado de máquina?', 'Capacidade de um modelo funcionar adequadamente em dados novos', TRUE, 2),
      ('O que significa generalização em aprendizado de máquina?', 'Capacidade de memorizar os dados de treino', FALSE, 3),
      ('Um modelo apresenta 99% de precisão no treinamento e 65% em dados novos. Qual hipótese deve ser investigada primeiro?', 'Possível overfitting', TRUE, 0),
      ('Um modelo apresenta 99% de precisão no treinamento e 65% em dados novos. Qual hipótese deve ser investigada primeiro?', 'Excesso de memória RAM', FALSE, 1),
      ('Um modelo apresenta 99% de precisão no treinamento e 65% em dados novos. Qual hipótese deve ser investigada primeiro?', 'Ausência de algoritmo', FALSE, 2),
      ('Um modelo apresenta 99% de precisão no treinamento e 65% em dados novos. Qual hipótese deve ser investigada primeiro?', 'Falta de armazenamento', FALSE, 3),
      ('O que é uma variável ou característica utilizada por um modelo para fazer uma previsão?', 'Prompt final', FALSE, 0),
      ('O que é uma variável ou característica utilizada por um modelo para fazer uma previsão?', 'Feature', TRUE, 1),
      ('O que é uma variável ou característica utilizada por um modelo para fazer uma previsão?', 'Tokenizador', FALSE, 2),
      ('O que é uma variável ou característica utilizada por um modelo para fazer uma previsão?', 'Endpoint', FALSE, 3),
      ('Num sistema que prevê o preço de uma casa usando área, localização e número de quartos, esses elementos são exemplos de:', 'Saídas', FALSE, 0),
      ('Num sistema que prevê o preço de uma casa usando área, localização e número de quartos, esses elementos são exemplos de:', 'Erros', FALSE, 1),
      ('Num sistema que prevê o preço de uma casa usando área, localização e número de quartos, esses elementos são exemplos de:', 'Rótulos', FALSE, 2),
      ('Num sistema que prevê o preço de uma casa usando área, localização e número de quartos, esses elementos são exemplos de:', 'Features', TRUE, 3),
      ('Em um problema de classificação, o que normalmente se pretende prever?', 'Uma categoria ou classe', TRUE, 0),
      ('Em um problema de classificação, o que normalmente se pretende prever?', 'Apenas um número decimal contínuo', FALSE, 1),
      ('Em um problema de classificação, o que normalmente se pretende prever?', 'O tamanho do modelo', FALSE, 2),
      ('Em um problema de classificação, o que normalmente se pretende prever?', 'A quantidade de memória disponível', FALSE, 3),
      ('Qual exemplo representa um problema de regressão?', 'Identificar se uma imagem contém um gato', FALSE, 0),
      ('Qual exemplo representa um problema de regressão?', 'Prever o preço de uma casa', TRUE, 1),
      ('Qual exemplo representa um problema de regressão?', 'Determinar se um e-mail é spam', FALSE, 2),
      ('Qual exemplo representa um problema de regressão?', 'Classificar clientes por país', FALSE, 3),
      ('Qual exemplo representa classificação binária?', 'Estimar o salário de uma pessoa', FALSE, 0),
      ('Qual exemplo representa classificação binária?', 'Determinar se uma transação é fraudulenta ou não', TRUE, 1),
      ('Qual exemplo representa classificação binária?', 'Prever o consumo mensal de energia', FALSE, 2),
      ('Qual exemplo representa classificação binária?', 'Prever a temperatura amanhã', FALSE, 3),
      ('O que é aprendizado supervisionado?', 'Aprendizado baseado apenas em regras manuais', FALSE, 0),
      ('O que é aprendizado supervisionado?', 'Treinamento utilizando exemplos que possuem respostas ou rótulos conhecidos', TRUE, 1),
      ('O que é aprendizado supervisionado?', 'Treinamento exclusivamente por tentativa física', FALSE, 2),
      ('O que é aprendizado supervisionado?', 'Aprendizado realizado sem qualquer dado', FALSE, 3),
      ('Qual tarefa é típica do aprendizado não supervisionado?', 'Previsão de uma nota conhecida', FALSE, 0),
      ('Qual tarefa é típica do aprendizado não supervisionado?', 'Identificação de spam com exemplos marcados', FALSE, 1),
      ('Qual tarefa é típica do aprendizado não supervisionado?', 'Classificação de imagens previamente rotuladas', FALSE, 2),
      ('Qual tarefa é típica do aprendizado não supervisionado?', 'Agrupamento de clientes com características semelhantes', TRUE, 3),
      ('O que é clustering?', 'Técnica para aumentar a resolução de imagens', FALSE, 0),
      ('O que é clustering?', 'Técnica que agrupa elementos semelhantes sem necessariamente possuir rótulos prévios', TRUE, 1),
      ('O que é clustering?', 'Processo de tradução automática', FALSE, 2),
      ('O que é clustering?', 'Método de criptografia', FALSE, 3),
      ('Uma empresa divide seus clientes em grupos com comportamentos semelhantes sem definir previamente os grupos. Qual técnica pode ser adequada?', 'Compilação', FALSE, 0),
      ('Uma empresa divide seus clientes em grupos com comportamentos semelhantes sem definir previamente os grupos. Qual técnica pode ser adequada?', 'Criptografia', FALSE, 1),
      ('Uma empresa divide seus clientes em grupos com comportamentos semelhantes sem definir previamente os grupos. Qual técnica pode ser adequada?', 'Clustering', TRUE, 2),
      ('Uma empresa divide seus clientes em grupos com comportamentos semelhantes sem definir previamente os grupos. Qual técnica pode ser adequada?', 'Compressão', FALSE, 3),
      ('O que é aprendizado por reforço?', 'Um sistema funciona apenas com regras fixas', FALSE, 0),
      ('O que é aprendizado por reforço?', 'Um modelo aprende através de interações e sinais de recompensa ou penalização', TRUE, 1),
      ('O que é aprendizado por reforço?', 'Um modelo recebe sempre a resposta final de cada exemplo', FALSE, 2),
      ('O que é aprendizado por reforço?', 'Um modelo não recebe qualquer retorno', FALSE, 3),
      ('Num sistema de aprendizado por reforço, o que representa uma recompensa?', 'Um arquivo de treinamento', FALSE, 0),
      ('Num sistema de aprendizado por reforço, o que representa uma recompensa?', 'Um erro de memória', FALSE, 1),
      ('Num sistema de aprendizado por reforço, o que representa uma recompensa?', 'Uma camada de rede', FALSE, 2),
      ('Num sistema de aprendizado por reforço, o que representa uma recompensa?', 'Um sinal que indica o valor ou qualidade de determinada ação', TRUE, 3),
      ('Um agente escolhe uma ação, recebe uma recompensa e ajusta seu comportamento. Esse processo está associado a:', 'Compressão de dados', FALSE, 0),
      ('Um agente escolhe uma ação, recebe uma recompensa e ajusta seu comportamento. Esse processo está associado a:', 'Reconhecimento óptico', FALSE, 1),
      ('Um agente escolhe uma ação, recebe uma recompensa e ajusta seu comportamento. Esse processo está associado a:', 'Aprendizado por reforço', TRUE, 2),
      ('Um agente escolhe uma ação, recebe uma recompensa e ajusta seu comportamento. Esse processo está associado a:', 'Armazenamento em nuvem', FALSE, 3),
      ('Qual é a função geral de uma camada em uma rede neural?', 'Transformar e processar representações dos dados', TRUE, 0),
      ('Qual é a função geral de uma camada em uma rede neural?', 'Substituir o sistema operacional', FALSE, 1),
      ('Qual é a função geral de uma camada em uma rede neural?', 'Controlar a bateria', FALSE, 2),
      ('Qual é a função geral de uma camada em uma rede neural?', 'Armazenar permanentemente todos os arquivos', FALSE, 3),
      ('O que são pesos em uma rede neural?', 'Valores ajustáveis que influenciam como as entradas são transformadas', TRUE, 0),
      ('O que são pesos em uma rede neural?', 'Arquivos de imagem', FALSE, 1),
      ('O que são pesos em uma rede neural?', 'Rótulos dos utilizadores', FALSE, 2),
      ('O que são pesos em uma rede neural?', 'Componentes físicos do computador', FALSE, 3),
      ('Durante o treinamento, os pesos de uma rede neural normalmente:', 'São ajustados para melhorar o desempenho do modelo', TRUE, 0),
      ('Durante o treinamento, os pesos de uma rede neural normalmente:', 'São substituídos por arquivos', FALSE, 1),
      ('Durante o treinamento, os pesos de uma rede neural normalmente:', 'Permanecem sempre iguais', FALSE, 2),
      ('Durante o treinamento, os pesos de uma rede neural normalmente:', 'São apagados após cada exemplo', FALSE, 3),
      ('O que é uma função de ativação?', 'Um mecanismo que introduz transformações não lineares em redes neurais', TRUE, 0),
      ('O que é uma função de ativação?', 'Um mecanismo de armazenamento', FALSE, 1),
      ('O que é uma função de ativação?', 'Um banco de dados', FALSE, 2),
      ('O que é uma função de ativação?', 'Um sistema para ligar o computador', FALSE, 3),
      ('Por que a não linearidade é importante em redes neurais?', 'Elimina todos os dados', FALSE, 0),
      ('Por que a não linearidade é importante em redes neurais?', 'Impede o aprendizado', FALSE, 1),
      ('Por que a não linearidade é importante em redes neurais?', 'Permite representar relações mais complexas nos dados', TRUE, 2),
      ('Por que a não linearidade é importante em redes neurais?', 'Reduz todas as entradas a zero', FALSE, 3),
      ('O que significa época (epoch) no treinamento de um modelo?', 'Uma camada da rede neural', FALSE, 0),
      ('O que significa época (epoch) no treinamento de um modelo?', 'Uma passagem completa pelo conjunto de treinamento', TRUE, 1),
      ('O que significa época (epoch) no treinamento de um modelo?', 'O tempo necessário para instalar o programa', FALSE, 2),
      ('O que significa época (epoch) no treinamento de um modelo?', 'Uma categoria de dados', FALSE, 3),
      ('Se um modelo for treinado durante muitas épocas sem controle adequado, qual risco pode aumentar?', 'Ausência de dados', FALSE, 0),
      ('Se um modelo for treinado durante muitas épocas sem controle adequado, qual risco pode aumentar?', 'Perda da linguagem', FALSE, 1),
      ('Se um modelo for treinado durante muitas épocas sem controle adequado, qual risco pode aumentar?', 'Desligamento automático do computador', FALSE, 2),
      ('Se um modelo for treinado durante muitas épocas sem controle adequado, qual risco pode aumentar?', 'Overfitting', TRUE, 3),
      ('O que é taxa de aprendizagem (learning rate)?', 'Número total de utilizadores', FALSE, 0),
      ('O que é taxa de aprendizagem (learning rate)?', 'Quantidade de arquivos armazenados', FALSE, 1),
      ('O que é taxa de aprendizagem (learning rate)?', 'Parâmetro que controla o tamanho dos ajustes realizados durante a otimização', TRUE, 2),
      ('O que é taxa de aprendizagem (learning rate)?', 'Velocidade da conexão de internet', FALSE, 3),
      ('Se a taxa de aprendizagem for excessivamente alta, qual problema pode ocorrer?', 'O modelo necessariamente fica perfeito', FALSE, 0),
      ('Se a taxa de aprendizagem for excessivamente alta, qual problema pode ocorrer?', 'O treinamento pode oscilar ou não encontrar uma solução adequada', TRUE, 1),
      ('Se a taxa de aprendizagem for excessivamente alta, qual problema pode ocorrer?', 'Os dados desaparecem', FALSE, 2),
      ('Se a taxa de aprendizagem for excessivamente alta, qual problema pode ocorrer?', 'O computador deixa de utilizar algoritmos', FALSE, 3),
      ('O que é uma função de perda?', 'Uma medida usada para quantificar o erro entre previsões e valores esperados', TRUE, 0),
      ('O que é uma função de perda?', 'Um método de compressão', FALSE, 1),
      ('O que é uma função de perda?', 'Um sistema de segurança física', FALSE, 2),
      ('O que é uma função de perda?', 'Uma função que apaga dados', FALSE, 3),
      ('Durante o treinamento, o objetivo comum de um algoritmo de otimização é:', 'Aumentar a função de perda', FALSE, 0),
      ('Durante o treinamento, o objetivo comum de um algoritmo de otimização é:', 'Eliminar todas as entradas', FALSE, 1),
      ('Durante o treinamento, o objetivo comum de um algoritmo de otimização é:', 'Aumentar o tamanho do conjunto de teste', FALSE, 2),
      ('Durante o treinamento, o objetivo comum de um algoritmo de otimização é:', 'Minimizar a função de perda', TRUE, 3),
      ('O que é uma matriz de confusão?', 'Uma estrutura de armazenamento físico', FALSE, 0),
      ('O que é uma matriz de confusão?', 'Uma tabela de preços', FALSE, 1),
      ('O que é uma matriz de confusão?', 'Uma tabela que resume resultados de classificação comparando classes previstas e reais', TRUE, 2),
      ('O que é uma matriz de confusão?', 'Um banco de imagens', FALSE, 3),
      ('Em classificação, o que representa um verdadeiro positivo?', 'O modelo prevê positivo e o caso é negativo', FALSE, 0),
      ('Em classificação, o que representa um verdadeiro positivo?', 'O modelo prevê positivo e o caso realmente é positivo', TRUE, 1),
      ('Em classificação, o que representa um verdadeiro positivo?', 'O modelo não produz previsão', FALSE, 2),
      ('Em classificação, o que representa um verdadeiro positivo?', 'O modelo prevê negativo e o caso é positivo', FALSE, 3),
      ('O que representa um falso positivo?', 'Uma previsão negativa correta', FALSE, 0),
      ('O que representa um falso positivo?', 'Uma previsão positiva quando o caso real é negativo', TRUE, 1),
      ('O que representa um falso positivo?', 'Ausência de previsão', FALSE, 2),
      ('O que representa um falso positivo?', 'Uma previsão positiva correta', FALSE, 3),
      ('O que representa um falso negativo?', 'O modelo não possui dados', FALSE, 0),
      ('O que representa um falso negativo?', 'O modelo prevê negativo corretamente', FALSE, 1),
      ('O que representa um falso negativo?', 'O modelo prevê negativo quando o caso real é positivo', TRUE, 2),
      ('O que representa um falso negativo?', 'O modelo prevê positivo corretamente', FALSE, 3),
      ('Por que precisão (precision) e recall podem ser importantes?', 'Permitem analisar diferentes aspectos do desempenho de um classificador', TRUE, 0),
      ('Por que precisão (precision) e recall podem ser importantes?', 'Avaliam a velocidade da internet', FALSE, 1),
      ('Por que precisão (precision) e recall podem ser importantes?', 'Substituem todos os dados de teste', FALSE, 2),
      ('Por que precisão (precision) e recall podem ser importantes?', 'Medem apenas o tamanho do modelo', FALSE, 3),
      ('Em um sistema de detecção de doenças, deixar passar muitos casos positivos pode ser especialmente preocupante. Qual métrica pode receber atenção especial?', 'Recall', TRUE, 0),
      ('Em um sistema de detecção de doenças, deixar passar muitos casos positivos pode ser especialmente preocupante. Qual métrica pode receber atenção especial?', 'Latência da rede', FALSE, 1),
      ('Em um sistema de detecção de doenças, deixar passar muitos casos positivos pode ser especialmente preocupante. Qual métrica pode receber atenção especial?', 'Tamanho do arquivo', FALSE, 2),
      ('Em um sistema de detecção de doenças, deixar passar muitos casos positivos pode ser especialmente preocupante. Qual métrica pode receber atenção especial?', 'Número de parâmetros', FALSE, 3),
      ('O que significa balancear um conjunto de dados?', 'Garantir uma distribuição adequada das classes ou exemplos para o objetivo do problema', TRUE, 0),
      ('O que significa balancear um conjunto de dados?', 'Tornar todos os arquivos do mesmo tamanho', FALSE, 1),
      ('O que significa balancear um conjunto de dados?', 'Remover todas as classes minoritárias', FALSE, 2),
      ('O que significa balancear um conjunto de dados?', 'Duplicar obrigatoriamente todos os dados', FALSE, 3),
      ('Por que classes muito desequilibradas podem dificultar o treinamento?', 'A memória RAM aumenta automaticamente', FALSE, 0),
      ('Por que classes muito desequilibradas podem dificultar o treinamento?', 'O modelo pode favorecer a classe majoritária e apresentar desempenho fraco nas minoritárias', TRUE, 1),
      ('Por que classes muito desequilibradas podem dificultar o treinamento?', 'O conjunto deixa de conter dados', FALSE, 2),
      ('Por que classes muito desequilibradas podem dificultar o treinamento?', 'O modelo deixa de possuir algoritmo', FALSE, 3),
      ('O que é normalização de dados?', 'Converter imagens em vídeos', FALSE, 0),
      ('O que é normalização de dados?', 'Eliminar todos os valores', FALSE, 1),
      ('O que é normalização de dados?', 'Transformar valores para uma escala ou distribuição mais adequada ao modelo', TRUE, 2),
      ('O que é normalização de dados?', 'Remover o algoritmo', FALSE, 3),
      ('Por que a normalização pode ajudar determinados modelos?', 'Elimina a necessidade de treinamento', FALSE, 0),
      ('Por que a normalização pode ajudar determinados modelos?', 'Garante previsões perfeitas', FALSE, 1),
      ('Por que a normalização pode ajudar determinados modelos?', 'Aumenta automaticamente o conjunto de dados', FALSE, 2),
      ('Por que a normalização pode ajudar determinados modelos?', 'Pode facilitar o processo de otimização quando as características possuem escalas muito diferentes', TRUE, 3),
      ('O que é engenharia de características (feature engineering)?', 'Construção física de computadores', FALSE, 0),
      ('O que é engenharia de características (feature engineering)?', 'Instalação de servidores', FALSE, 1),
      ('O que é engenharia de características (feature engineering)?', 'Processo de criar, transformar ou selecionar características úteis para um modelo', TRUE, 2),
      ('O que é engenharia de características (feature engineering)?', 'Criação de senhas', FALSE, 3),
      ('Um modelo apresenta resultados ruins porque recebe informações irrelevantes e redundantes. Qual etapa pode ajudar?', 'Compressão do monitor', FALSE, 0),
      ('Um modelo apresenta resultados ruins porque recebe informações irrelevantes e redundantes. Qual etapa pode ajudar?', 'Criação de mais senhas', FALSE, 1),
      ('Um modelo apresenta resultados ruins porque recebe informações irrelevantes e redundantes. Qual etapa pode ajudar?', 'Seleção de características', TRUE, 2),
      ('Um modelo apresenta resultados ruins porque recebe informações irrelevantes e redundantes. Qual etapa pode ajudar?', 'Aumento das notificações', FALSE, 3),
      ('O que é redução de dimensionalidade?', 'Aumentar o número de variáveis indefinidamente', FALSE, 0),
      ('O que é redução de dimensionalidade?', 'Transformar texto em áudio', FALSE, 1),
      ('O que é redução de dimensionalidade?', 'Eliminar todos os dados', FALSE, 2),
      ('O que é redução de dimensionalidade?', 'Reduzir o número de características ou dimensões mantendo informação relevante', TRUE, 3),
      ('Qual pode ser uma vantagem da redução de dimensionalidade?', 'Garantir 100% de precisão', FALSE, 0),
      ('Qual pode ser uma vantagem da redução de dimensionalidade?', 'Aumentar obrigatoriamente os dados disponíveis', FALSE, 1),
      ('Qual pode ser uma vantagem da redução de dimensionalidade?', 'Eliminar qualquer risco', FALSE, 2),
      ('Qual pode ser uma vantagem da redução de dimensionalidade?', 'Simplificar os dados e facilitar determinadas análises ou modelos', TRUE, 3),
      ('O que é inferência em inteligência artificial?', 'Processo de coletar exclusivamente dados de treino', FALSE, 0),
      ('O que é inferência em inteligência artificial?', 'Criação física do computador', FALSE, 1),
      ('O que é inferência em inteligência artificial?', 'Exclusão do modelo', FALSE, 2),
      ('O que é inferência em inteligência artificial?', 'Utilização de um modelo treinado para produzir resultados a partir de novos dados', TRUE, 3),
      ('Qual é a principal diferença entre treinamento e inferência?', 'Treinamento nunca utiliza dados', FALSE, 0),
      ('Qual é a principal diferença entre treinamento e inferência?', 'São exatamente a mesma etapa', FALSE, 1),
      ('Qual é a principal diferença entre treinamento e inferência?', 'Treinamento ajusta o modelo; inferência utiliza o modelo para gerar resultados', TRUE, 2),
      ('Qual é a principal diferença entre treinamento e inferência?', 'Inferência sempre modifica os pesos', FALSE, 3),
      ('O que significa latência em uma aplicação de IA?', 'Número de parâmetros', FALSE, 0),
      ('O que significa latência em uma aplicação de IA?', 'Taxa de acerto', FALSE, 1),
      ('O que significa latência em uma aplicação de IA?', 'Tempo necessário para o sistema responder ou processar uma solicitação', TRUE, 2),
      ('O que significa latência em uma aplicação de IA?', 'Quantidade de dados de treinamento', FALSE, 3),
      ('Por que a latência é importante num chatbot?', 'Latência elimina erros factuais', FALSE, 0),
      ('Por que a latência é importante num chatbot?', 'Respostas muito demoradas podem prejudicar a experiência do utilizador', TRUE, 1),
      ('Por que a latência é importante num chatbot?', 'Latência determina a cor da interface', FALSE, 2),
      ('Por que a latência é importante num chatbot?', 'Latência substitui o treinamento', FALSE, 3),
      ('O que são parâmetros de um modelo?', 'Dados obrigatoriamente pessoais', FALSE, 0),
      ('O que são parâmetros de um modelo?', 'Perguntas feitas pelos utilizadores', FALSE, 1),
      ('O que são parâmetros de um modelo?', 'Valores internos aprendidos ou ajustados durante o treinamento', TRUE, 2),
      ('O que são parâmetros de um modelo?', 'Apenas arquivos externos', FALSE, 3),
      ('Qual é uma diferença entre parâmetros e hiperparâmetros?', 'Hiperparâmetros são sempre dados de entrada', FALSE, 0),
      ('Qual é uma diferença entre parâmetros e hiperparâmetros?', 'Parâmetros são exclusivamente configurações de hardware', FALSE, 1),
      ('Qual é uma diferença entre parâmetros e hiperparâmetros?', 'Ambos são sempre aprendidos automaticamente', FALSE, 2),
      ('Qual é uma diferença entre parâmetros e hiperparâmetros?', 'Parâmetros são aprendidos durante o treinamento; hiperparâmetros são definidos para controlar o processo', TRUE, 3),
      ('Qual dos seguintes é um exemplo de hiperparâmetro?', 'Texto produzido pelo modelo', FALSE, 0),
      ('Qual dos seguintes é um exemplo de hiperparâmetro?', 'Valor de uma previsão', FALSE, 1),
      ('Qual dos seguintes é um exemplo de hiperparâmetro?', 'Taxa de aprendizagem', TRUE, 2),
      ('Qual dos seguintes é um exemplo de hiperparâmetro?', 'Peso aprendido por um neurônio', FALSE, 3),
      ('O que é um modelo pré-treinado?', 'Modelo sem parâmetros', FALSE, 0),
      ('O que é um modelo pré-treinado?', 'Modelo que já passou por treinamento em um conjunto de dados antes de ser adaptado ou utilizado numa tarefa', TRUE, 1),
      ('O que é um modelo pré-treinado?', 'Modelo que só funciona offline', FALSE, 2),
      ('O que é um modelo pré-treinado?', 'Modelo que nunca recebeu dados', FALSE, 3),
      ('Qual é uma vantagem potencial de utilizar um modelo pré-treinado?', 'Impede adaptação', FALSE, 0),
      ('Qual é uma vantagem potencial de utilizar um modelo pré-treinado?', 'Elimina toda necessidade de avaliação', FALSE, 1),
      ('Qual é uma vantagem potencial de utilizar um modelo pré-treinado?', 'Garante que o modelo será correto', FALSE, 2),
      ('Qual é uma vantagem potencial de utilizar um modelo pré-treinado?', 'Pode reduzir o custo e o tempo necessários para desenvolver uma solução específica', TRUE, 3),
      ('O que é fine-tuning?', 'Exclusão dos parâmetros', FALSE, 0),
      ('O que é fine-tuning?', 'Limpeza física do computador', FALSE, 1),
      ('O que é fine-tuning?', 'Compressão dos dados', FALSE, 2),
      ('O que é fine-tuning?', 'Adaptação adicional de um modelo pré-treinado para uma tarefa ou domínio específico', TRUE, 3),
      ('Uma empresa adapta um modelo de linguagem geral com exemplos específicos do seu setor. Isso pode ser considerado:', 'Clustering', FALSE, 0),
      ('Uma empresa adapta um modelo de linguagem geral com exemplos específicos do seu setor. Isso pode ser considerado:', 'Fine-tuning', TRUE, 1),
      ('Uma empresa adapta um modelo de linguagem geral com exemplos específicos do seu setor. Isso pode ser considerado:', 'Criptografia', FALSE, 2),
      ('Uma empresa adapta um modelo de linguagem geral com exemplos específicos do seu setor. Isso pode ser considerado:', 'Renderização', FALSE, 3),
      ('O que é um token em modelos de linguagem?', 'Uma unidade de texto utilizada pelo modelo durante o processamento', TRUE, 0),
      ('O que é um token em modelos de linguagem?', 'Um tipo de cabo', FALSE, 1),
      ('O que é um token em modelos de linguagem?', 'Um componente físico do servidor', FALSE, 2),
      ('O que é um token em modelos de linguagem?', 'Uma moeda obrigatoriamente financeira', FALSE, 3),
      ('Por que a tokenização é importante em modelos de linguagem?', 'Impede o processamento de texto', FALSE, 0),
      ('Por que a tokenização é importante em modelos de linguagem?', 'Substitui o treinamento', FALSE, 1),
      ('Por que a tokenização é importante em modelos de linguagem?', 'Elimina o significado das palavras', FALSE, 2),
      ('Por que a tokenização é importante em modelos de linguagem?', 'Converte texto em unidades que podem ser processadas pelo modelo', TRUE, 3),
      ('O que significa contexto em uma interação com um modelo de linguagem?', 'O tamanho do teclado', FALSE, 0),
      ('O que significa contexto em uma interação com um modelo de linguagem?', 'Informação disponível para orientar a interpretação e geração da resposta', TRUE, 1),
      ('O que significa contexto em uma interação com um modelo de linguagem?', 'Memória física do computador', FALSE, 2),
      ('O que significa contexto em uma interação com um modelo de linguagem?', 'Apenas a velocidade da internet', FALSE, 3),
      ('Um utilizador fornece objetivo, público-alvo, formato e restrições numa instrução para IA. Qual é o principal benefício?', 'Fornecer contexto e orientar melhor a resposta', TRUE, 0),
      ('Um utilizador fornece objetivo, público-alvo, formato e restrições numa instrução para IA. Qual é o principal benefício?', 'Eliminar qualquer possibilidade de erro', FALSE, 1),
      ('Um utilizador fornece objetivo, público-alvo, formato e restrições numa instrução para IA. Qual é o principal benefício?', 'Desativar o processamento', FALSE, 2),
      ('Um utilizador fornece objetivo, público-alvo, formato e restrições numa instrução para IA. Qual é o principal benefício?', 'Reduzir obrigatoriamente o modelo', FALSE, 3),
      ('O que é uma alucinação em um modelo generativo?', 'Falta de energia elétrica', FALSE, 0),
      ('O que é uma alucinação em um modelo generativo?', 'Falha física do computador', FALSE, 1),
      ('O que é uma alucinação em um modelo generativo?', 'Exclusão automática do modelo', FALSE, 2),
      ('O que é uma alucinação em um modelo generativo?', 'Produção de conteúdo que parece plausível, mas contém informação incorreta ou inventada', TRUE, 3),
      ('Qual estratégia pode reduzir o risco de utilizar uma informação incorreta produzida por IA?', 'Aumentar o tamanho do prompt sem verificar fontes', FALSE, 0),
      ('Qual estratégia pode reduzir o risco de utilizar uma informação incorreta produzida por IA?', 'Evitar qualquer revisão', FALSE, 1),
      ('Qual estratégia pode reduzir o risco de utilizar uma informação incorreta produzida por IA?', 'Verificar informações importantes em fontes confiáveis', TRUE, 2),
      ('Qual estratégia pode reduzir o risco de utilizar uma informação incorreta produzida por IA?', 'Aceitar sempre a primeira resposta', FALSE, 3),
      ('O que é explicabilidade em IA?', 'Capacidade de gerar senhas', FALSE, 0),
      ('O que é explicabilidade em IA?', 'Capacidade de aumentar a velocidade da internet', FALSE, 1),
      ('O que é explicabilidade em IA?', 'Capacidade de compreender ou comunicar de forma significativa como um sistema chegou a determinado resultado', TRUE, 2),
      ('O que é explicabilidade em IA?', 'Capacidade de armazenar mais arquivos', FALSE, 3),
      ('Por que a explicabilidade pode ser importante em sistemas de IA usados em decisões sensíveis?', 'Pode ajudar a identificar erros, justificar decisões e aumentar a confiança no sistema', TRUE, 0),
      ('Por que a explicabilidade pode ser importante em sistemas de IA usados em decisões sensíveis?', 'Elimina a necessidade de supervisão', FALSE, 1),
      ('Por que a explicabilidade pode ser importante em sistemas de IA usados em decisões sensíveis?', 'Garante que o modelo nunca erre', FALSE, 2),
      ('Por que a explicabilidade pode ser importante em sistemas de IA usados em decisões sensíveis?', 'Substitui completamente os dados', FALSE, 3)
    ) AS a(statement, label, is_correct, display_order)
    ON q.statement = a.statement;

    DROP TABLE tmp_new_questions_ia_medio_v3;

    RAISE NOTICE '63 perguntas inseridas com sucesso (source=seed_ia_medio_v3).';
  END IF;
END $$;

COMMIT;
