-- Migration/seed: conteúdo Inteligência Artificial, nível Difícil — lote 2 (87 de 100 perguntas)
-- Fonte: lote de 100 perguntas (2 arquivos de 50, "LOTE 1/2" e "LOTE 2/2")
-- fornecido pelo proprietário do projeto — cobre fundamentos de ML/redes
-- neurais/NLP (deep learning, RNN, CNN, embeddings, ética) e tópicos
-- avançados (Transfer Learning, regularização, RAG, GANs, MLOps).
--
-- Este é um lote DIFERENTE do já existente em 050_ia_dificil.sql (aquele
-- veio de outro envio, temática Transformers/RLHF/avaliação de modelos,
-- e havia sido enviado em duplicata no mesmo documento). Overlap real entre
-- os dois lotes: apenas 1 pergunta ("O que é RAG...") — tratada como
-- duplicata abaixo, não inserida duas vezes.
--
-- DEDUPLICAÇÃO APLICADA: comparei texto a texto contra as 1325 perguntas já
-- existentes no banco (todas as categorias/dificuldades, não só IA) e
-- encontrei 13 repetidas, removidas deste arquivo:
--   - "O que são dados de treinamento?"
--   - "O que é aprendizado supervisionado?"
--   - "O que é aprendizado por reforço?"
--   - "O que é fine-tuning?"
--   - "O que é um prompt?"
--   - "O que é multimodalidade em IA?"
--   - "O que é visão computacional?"
--   - "O que é inteligência artificial generativa?"
--   - "O que é automação inteligente?"
--   - "O que é mineração de dados?"
--   - "O que é uma matriz de confusão?"
--   - "O que é limpeza de dados?"
--   - "O que é RAG (Retrieval-Augmented Generation)?"
-- Sobraram 87 perguntas novas e únicas.
--
-- CORREÇÃO DE QUALIDADE APLICADA (mesma higiene de dado dos lotes
-- anteriores, não é decisão de negócio): no lote original, as respostas
-- corretas eram TODAS a alternativa "A". Posição redistribuída por pergunta
-- com seed fixa (89 — sequência das seeds 42 a 88 já usadas nos seeds
-- anteriores) e distribuição controlada (22/22/22/21 entre A/B/C/D),
-- reprodutível — o conteúdo pedagógico permanece exatamente como enviado
-- (para as 87 que restaram após a deduplicação), só a ORDEM de exibição de
-- cada alternativa mudou.
--
-- `xp_reward` (10) e `time_limit_seconds` (15): mesmos valores usados em
-- todos os seeds de pergunta do projeto, independente de dificuldade.
--
-- Categoria "Inteligência Artificial" já existe desde a migration 021.
--
-- Idempotente: usa a coluna `source` (migration 022) como marcador — rodar
-- este arquivo mais de uma vez não duplica as perguntas.

BEGIN;

DO $$
DECLARE
  v_category_id UUID;
BEGIN
  SELECT id INTO v_category_id FROM categories WHERE slug = 'inteligencia-artificial';
  IF v_category_id IS NULL THEN
    RAISE EXCEPTION 'Categoria "Inteligência Artificial" não encontrada — rode a migration 021 primeiro.';
  END IF;

  IF EXISTS (SELECT 1 FROM questions WHERE source = 'seed_ia_dificil_v2') THEN
    RAISE NOTICE 'Perguntas de Inteligência Artificial (difícil, lote 2) já foram inseridas anteriormente — nada a fazer.';
  ELSE

    CREATE TEMP TABLE tmp_new_questions_ia_dificil2 AS
    WITH inserted AS (
    INSERT INTO questions (category_id, difficulty, statement, time_limit_seconds, xp_reward, source)
    SELECT v_category_id, 'hard', v.statement, 15, 10, 'seed_ia_dificil_v2'
    FROM (VALUES
      ('O que é aprendizagem profunda (Deep Learning)?'),
      ('O que caracteriza uma rede neural artificial?'),
      ('O que é uma rede neural profunda?'),
      ('O que é treinamento de um modelo de IA?'),
      ('O que é aprendizado não supervisionado?'),
      ('O que é overfitting em Machine Learning?'),
      ('O que é underfitting?'),
      ('O que é generalização em IA?'),
      ('O que é um algoritmo de Machine Learning?'),
      ('O que é processamento de linguagem natural (NLP)?'),
      ('O que são modelos de linguagem grandes (LLMs)?'),
      ('O que significa GPT em modelos de IA?'),
      ('O que é um Transformer em Inteligência Artificial?'),
      ('O que é mecanismo de atenção em IA?'),
      ('O que é tokenização em modelos de linguagem?'),
      ('O que é embedding em IA?'),
      ('O que é engenharia de prompts?'),
      ('O que é reconhecimento facial baseado em IA?'),
      ('O que é detecção de objetos?'),
      ('O que é modelo discriminativo?'),
      ('O que é modelo generativo?'),
      ('O que são redes neurais convolucionais (CNNs)?'),
      ('O que são redes neurais recorrentes (RNNs)?'),
      ('O que é memória de longo prazo em redes LSTM?'),
      ('O que é um agente inteligente?'),
      ('O que é IA explicável (Explainable AI)?'),
      ('O que é viés algorítmico?'),
      ('O que é ética em Inteligência Artificial?'),
      ('O que é privacidade de dados em IA?'),
      ('O que é segurança em IA?'),
      ('O que é ataque adversarial em IA?'),
      ('O que é aprendizado contínuo?'),
      ('O que é MLOps?'),
      ('O que é inferência em IA?'),
      ('O que é dataset?'),
      ('O que é inteligência artificial forte?'),
      ('O que é inteligência artificial estreita (ANI)?'),
      ('O que é AGI?'),
      ('O que é singularidade tecnológica?'),
      ('Qual é um dos maiores desafios atuais da Inteligência Artificial?'),
      ('O que é aprendizado por transferência (Transfer Learning)?'),
      ('Qual é a principal vantagem do Transfer Learning?'),
      ('O que é regularização em Machine Learning?'),
      ('O que é Dropout em redes neurais?'),
      ('O que é função de ativação em uma rede neural?'),
      ('Qual é a função da camada de entrada em uma rede neural?'),
      ('Qual é a função da camada de saída?'),
      ('O que é backpropagation?'),
      ('O que representa o peso em uma rede neural?'),
      ('O que é uma época (epoch) no treinamento de IA?'),
      ('O que é batch size?'),
      ('O que é learning rate?'),
      ('O que acontece quando o learning rate é muito alto?'),
      ('O que mede a acurácia de um modelo?'),
      ('O que é precisão (precision) em classificação?'),
      ('O que é recall em Machine Learning?'),
      ('O que é F1-score?'),
      ('O que é validação cruzada?'),
      ('O que é conjunto de teste em Machine Learning?'),
      ('O que é engenharia de dados em IA?'),
      ('Por que dados de qualidade são importantes para IA?'),
      ('O que é alucinação em modelos de IA?'),
      ('Como reduzir alucinações em modelos de linguagem?'),
      ('Qual é a vantagem do RAG?'),
      ('O que é um modelo de difusão?'),
      ('O que são GANs (Generative Adversarial Networks)?'),
      ('O que é um chatbot inteligente?'),
      ('O que é automação robótica de processos (RPA)?'),
      ('O que diferencia RPA tradicional de IA?'),
      ('O que é IA embarcada?'),
      ('O que é Edge AI?'),
      ('O que é computação quântica aplicada à IA?'),
      ('O que é segurança de modelos de IA?'),
      ('O que é alinhamento de IA?'),
      ('O que é IA responsável?'),
      ('O que é transparência em IA?'),
      ('O que é auditoria de algoritmos?'),
      ('O que é IA generativa multimodal?'),
      ('O que é copiloto de IA?'),
      ('O que é agente autônomo de IA?'),
      ('O que é otimização de modelos de IA?'),
      ('O que é compressão de modelos?'),
      ('O que é inferência em tempo real?'),
      ('Qual é um desafio dos grandes modelos de IA?'),
      ('O que é democratização da IA?'),
      ('Qual é uma aplicação avançada da IA na medicina?'),
      ('Qual é o principal objetivo do desenvolvimento responsável de Inteligência Artificial?')
    ) AS v(statement)
    RETURNING id, statement
    )
    SELECT * FROM inserted;

    INSERT INTO question_alternatives (question_id, label, is_correct, display_order)
    SELECT q.id, a.label, a.is_correct, a.display_order
    FROM tmp_new_questions_ia_dificil2 q
    JOIN (VALUES
      ('O que é aprendizagem profunda (Deep Learning)?', 'Método usado apenas para criar documentos', FALSE, 0),
      ('O que é aprendizagem profunda (Deep Learning)?', 'Programa sem capacidade de aprendizagem', FALSE, 1),
      ('O que é aprendizagem profunda (Deep Learning)?', 'Sistema que apenas armazena informações manualmente', FALSE, 2),
      ('O que é aprendizagem profunda (Deep Learning)?', 'Área da IA que utiliza redes neurais com múltiplas camadas para aprender padrões complexos', TRUE, 3),
      ('O que caracteriza uma rede neural artificial?', 'Linguagem de programação', FALSE, 0),
      ('O que caracteriza uma rede neural artificial?', 'Sistema operacional', FALSE, 1),
      ('O que caracteriza uma rede neural artificial?', 'Modelo computacional inspirado no funcionamento dos neurônios biológicos', TRUE, 2),
      ('O que caracteriza uma rede neural artificial?', 'Banco de dados tradicional', FALSE, 3),
      ('O que é uma rede neural profunda?', 'Rede sem dados de treinamento', FALSE, 0),
      ('O que é uma rede neural profunda?', 'Programa usado somente para cálculos simples', FALSE, 1),
      ('O que é uma rede neural profunda?', 'Sistema sem parâmetros', FALSE, 2),
      ('O que é uma rede neural profunda?', 'Rede neural composta por várias camadas de processamento', TRUE, 3),
      ('O que é treinamento de um modelo de IA?', 'Instalação de um aplicativo', FALSE, 0),
      ('O que é treinamento de um modelo de IA?', 'Processo em que o modelo aprende padrões usando dados fornecidos', TRUE, 1),
      ('O que é treinamento de um modelo de IA?', 'Processo de apagar informações', FALSE, 2),
      ('O que é treinamento de um modelo de IA?', 'Criação manual de respostas', FALSE, 3),
      ('O que é aprendizado não supervisionado?', 'Sistema sem dados', FALSE, 0),
      ('O que é aprendizado não supervisionado?', 'Modelo treinado apenas com respostas prontas', FALSE, 1),
      ('O que é aprendizado não supervisionado?', 'Método onde o modelo encontra padrões em dados sem rótulos definidos', TRUE, 2),
      ('O que é aprendizado não supervisionado?', 'Algoritmo sem objetivos', FALSE, 3),
      ('O que é overfitting em Machine Learning?', 'Quando o algoritmo é removido', FALSE, 0),
      ('O que é overfitting em Machine Learning?', 'Quando o computador desliga', FALSE, 1),
      ('O que é overfitting em Machine Learning?', 'Quando o modelo aprende excessivamente os dados de treinamento e perde capacidade de generalização', TRUE, 2),
      ('O que é overfitting em Machine Learning?', 'Quando o modelo não recebe dados', FALSE, 3),
      ('O que é underfitting?', 'Quando aumenta a memória do computador', FALSE, 0),
      ('O que é underfitting?', 'Quando o modelo aprende perfeitamente', FALSE, 1),
      ('O que é underfitting?', 'Quando há excesso de dados', FALSE, 2),
      ('O que é underfitting?', 'Quando o modelo não consegue aprender suficientemente os padrões dos dados', TRUE, 3),
      ('O que é generalização em IA?', 'Exclusão de dados', FALSE, 0),
      ('O que é generalização em IA?', 'Capacidade de memorizar apenas exemplos antigos', FALSE, 1),
      ('O que é generalização em IA?', 'Capacidade do modelo de funcionar bem em dados novos', TRUE, 2),
      ('O que é generalização em IA?', 'Redução da velocidade', FALSE, 3),
      ('O que é um algoritmo de Machine Learning?', 'Uma rede social', FALSE, 0),
      ('O que é um algoritmo de Machine Learning?', 'Um equipamento físico', FALSE, 1),
      ('O que é um algoritmo de Machine Learning?', 'Conjunto de métodos usados para permitir que máquinas aprendam com dados', TRUE, 2),
      ('O que é um algoritmo de Machine Learning?', 'Um banco de dados', FALSE, 3),
      ('O que é processamento de linguagem natural (NLP)?', 'Área da IA que permite computadores compreenderem e gerarem linguagem humana', TRUE, 0),
      ('O que é processamento de linguagem natural (NLP)?', 'Sistema de armazenamento físico', FALSE, 1),
      ('O que é processamento de linguagem natural (NLP)?', 'Método de segurança bancária', FALSE, 2),
      ('O que é processamento de linguagem natural (NLP)?', 'Tecnologia de impressão', FALSE, 3),
      ('O que são modelos de linguagem grandes (LLMs)?', 'Sistemas sem dados', FALSE, 0),
      ('O que são modelos de linguagem grandes (LLMs)?', 'Programas apenas de edição', FALSE, 1),
      ('O que são modelos de linguagem grandes (LLMs)?', 'Modelos treinados com grandes volumes de texto para compreender e gerar linguagem', TRUE, 2),
      ('O que são modelos de linguagem grandes (LLMs)?', 'Sistemas operacionais', FALSE, 3),
      ('O que significa GPT em modelos de IA?', 'Generative Pre-trained Transformer', TRUE, 0),
      ('O que significa GPT em modelos de IA?', 'Generated Personal Text', FALSE, 1),
      ('O que significa GPT em modelos de IA?', 'Global Program Tool', FALSE, 2),
      ('O que significa GPT em modelos de IA?', 'General Processing Technology', FALSE, 3),
      ('O que é um Transformer em Inteligência Artificial?', 'Arquitetura neural baseada em mecanismos de atenção para processar sequências', TRUE, 0),
      ('O que é um Transformer em Inteligência Artificial?', 'Um antivírus', FALSE, 1),
      ('O que é um Transformer em Inteligência Artificial?', 'Um computador físico', FALSE, 2),
      ('O que é um Transformer em Inteligência Artificial?', 'Um banco de dados', FALSE, 3),
      ('O que é mecanismo de atenção em IA?', 'Técnica que permite ao modelo focar partes importantes dos dados de entrada', TRUE, 0),
      ('O que é mecanismo de atenção em IA?', 'Ferramenta de design', FALSE, 1),
      ('O que é mecanismo de atenção em IA?', 'Sistema de armazenamento', FALSE, 2),
      ('O que é mecanismo de atenção em IA?', 'Método de apagar informações', FALSE, 3),
      ('O que é tokenização em modelos de linguagem?', 'Processo de dividir textos em unidades menores para processamento pelo modelo', TRUE, 0),
      ('O que é tokenização em modelos de linguagem?', 'Exclusão de palavras', FALSE, 1),
      ('O que é tokenização em modelos de linguagem?', 'Criação de senhas', FALSE, 2),
      ('O que é tokenização em modelos de linguagem?', 'Tradução automática', FALSE, 3),
      ('O que é embedding em IA?', 'Arquivo de imagem', FALSE, 0),
      ('O que é embedding em IA?', 'Sistema operacional', FALSE, 1),
      ('O que é embedding em IA?', 'Representação numérica de informações para que modelos possam processá-las', TRUE, 2),
      ('O que é embedding em IA?', 'Código de segurança', FALSE, 3),
      ('O que é engenharia de prompts?', 'Técnica de criar instruções eficientes para obter melhores respostas de modelos de IA', TRUE, 0),
      ('O que é engenharia de prompts?', 'Construção de robôs', FALSE, 1),
      ('O que é engenharia de prompts?', 'Criação de redes sociais', FALSE, 2),
      ('O que é engenharia de prompts?', 'Programação de computadores físicos', FALSE, 3),
      ('O que é reconhecimento facial baseado em IA?', 'Método de armazenamento', FALSE, 0),
      ('O que é reconhecimento facial baseado em IA?', 'Tecnologia que identifica ou verifica pessoas através de características faciais', TRUE, 1),
      ('O que é reconhecimento facial baseado em IA?', 'Editor de imagens', FALSE, 2),
      ('O que é reconhecimento facial baseado em IA?', 'Sistema de impressão', FALSE, 3),
      ('O que é detecção de objetos?', 'Técnica de identificar e localizar objetos dentro de imagens ou vídeos', TRUE, 0),
      ('O que é detecção de objetos?', 'Tradução automática', FALSE, 1),
      ('O que é detecção de objetos?', 'Exclusão de arquivos', FALSE, 2),
      ('O que é detecção de objetos?', 'Criação de textos', FALSE, 3),
      ('O que é modelo discriminativo?', 'Modelo usado apenas para criar imagens', FALSE, 0),
      ('O que é modelo discriminativo?', 'Sistema sem treinamento', FALSE, 1),
      ('O que é modelo discriminativo?', 'Banco de dados', FALSE, 2),
      ('O que é modelo discriminativo?', 'Modelo que aprende a diferenciar ou classificar dados', TRUE, 3),
      ('O que é modelo generativo?', 'Modelo que aprende padrões para criar novos dados semelhantes aos originais', TRUE, 0),
      ('O que é modelo generativo?', 'Programa de armazenamento', FALSE, 1),
      ('O que é modelo generativo?', 'Modelo que apenas classifica informações', FALSE, 2),
      ('O que é modelo generativo?', 'Sistema sem parâmetros', FALSE, 3),
      ('O que são redes neurais convolucionais (CNNs)?', 'Sistemas operacionais', FALSE, 0),
      ('O que são redes neurais convolucionais (CNNs)?', 'Redes especializadas no processamento de imagens e padrões visuais', TRUE, 1),
      ('O que são redes neurais convolucionais (CNNs)?', 'Bancos de dados', FALSE, 2),
      ('O que são redes neurais convolucionais (CNNs)?', 'Redes usadas apenas para pagamentos', FALSE, 3),
      ('O que são redes neurais recorrentes (RNNs)?', 'Sistemas de arquivos', FALSE, 0),
      ('O que são redes neurais recorrentes (RNNs)?', 'Redes desenvolvidas para trabalhar com dados sequenciais', TRUE, 1),
      ('O que são redes neurais recorrentes (RNNs)?', 'Redes sem memória', FALSE, 2),
      ('O que são redes neurais recorrentes (RNNs)?', 'Programas de edição', FALSE, 3),
      ('O que é memória de longo prazo em redes LSTM?', 'Exclusão de dados antigos', FALSE, 0),
      ('O que é memória de longo prazo em redes LSTM?', 'Redução de velocidade', FALSE, 1),
      ('O que é memória de longo prazo em redes LSTM?', 'Armazenamento físico do computador', FALSE, 2),
      ('O que é memória de longo prazo em redes LSTM?', 'Capacidade de manter informações importantes durante sequências longas', TRUE, 3),
      ('O que é um agente inteligente?', 'Banco de dados', FALSE, 0),
      ('O que é um agente inteligente?', 'Arquivo digital', FALSE, 1),
      ('O que é um agente inteligente?', 'Sistema que percebe o ambiente e toma decisões para alcançar objetivos', TRUE, 2),
      ('O que é um agente inteligente?', 'Programa sem ação', FALSE, 3),
      ('O que é IA explicável (Explainable AI)?', 'IA sem treinamento', FALSE, 0),
      ('O que é IA explicável (Explainable AI)?', 'Banco de imagens', FALSE, 1),
      ('O que é IA explicável (Explainable AI)?', 'Sistema de jogos', FALSE, 2),
      ('O que é IA explicável (Explainable AI)?', 'Técnicas que tornam decisões de modelos de IA mais compreensíveis para humanos', TRUE, 3),
      ('O que é viés algorítmico?', 'Aumento da velocidade da IA', FALSE, 0),
      ('O que é viés algorítmico?', 'Resultado injusto causado por padrões inadequados nos dados ou modelos', TRUE, 1),
      ('O que é viés algorítmico?', 'Redução de custos', FALSE, 2),
      ('O que é viés algorítmico?', 'Melhoria automática do sistema', FALSE, 3),
      ('O que é ética em Inteligência Artificial?', 'Criação de computadores', FALSE, 0),
      ('O que é ética em Inteligência Artificial?', 'Armazenamento de arquivos', FALSE, 1),
      ('O que é ética em Inteligência Artificial?', 'Estudo do uso responsável e seguro das tecnologias de IA', TRUE, 2),
      ('O que é ética em Inteligência Artificial?', 'Programação básica', FALSE, 3),
      ('O que é privacidade de dados em IA?', 'Proteção das informações utilizadas por sistemas inteligentes', TRUE, 0),
      ('O que é privacidade de dados em IA?', 'Aumento de publicidade', FALSE, 1),
      ('O que é privacidade de dados em IA?', 'Exclusão da tecnologia', FALSE, 2),
      ('O que é privacidade de dados em IA?', 'Divulgação de todos os dados', FALSE, 3),
      ('O que é segurança em IA?', 'Remoção de algoritmos', FALSE, 0),
      ('O que é segurança em IA?', 'Proteção dos modelos e sistemas contra ataques e usos indevidos', TRUE, 1),
      ('O que é segurança em IA?', 'Criação de vírus', FALSE, 2),
      ('O que é segurança em IA?', 'Redução de dados', FALSE, 3),
      ('O que é ataque adversarial em IA?', 'Treinamento normal', FALSE, 0),
      ('O que é ataque adversarial em IA?', 'Armazenamento seguro', FALSE, 1),
      ('O que é ataque adversarial em IA?', 'Técnica que tenta enganar modelos usando entradas manipuladas', TRUE, 2),
      ('O que é ataque adversarial em IA?', 'Atualização automática', FALSE, 3),
      ('O que é aprendizado contínuo?', 'Exclusão de informações', FALSE, 0),
      ('O que é aprendizado contínuo?', 'Sistema sem atualização', FALSE, 1),
      ('O que é aprendizado contínuo?', 'Capacidade de um sistema melhorar com novos dados ao longo do tempo', TRUE, 2),
      ('O que é aprendizado contínuo?', 'Modelo sem treinamento', FALSE, 3),
      ('O que é MLOps?', 'Linguagem de programação', FALSE, 0),
      ('O que é MLOps?', 'Sistema de pagamentos', FALSE, 1),
      ('O que é MLOps?', 'Práticas para desenvolver, implementar e manter modelos de Machine Learning em produção', TRUE, 2),
      ('O que é MLOps?', 'Hardware específico', FALSE, 3),
      ('O que é inferência em IA?', 'Criação de dados', FALSE, 0),
      ('O que é inferência em IA?', 'Processo de treinamento inicial', FALSE, 1),
      ('O que é inferência em IA?', 'Exclusão do modelo', FALSE, 2),
      ('O que é inferência em IA?', 'Processo em que um modelo treinado gera previsões ou respostas', TRUE, 3),
      ('O que é dataset?', 'Rede social', FALSE, 0),
      ('O que é dataset?', 'Conjunto organizado de dados utilizado para análise ou treinamento', TRUE, 1),
      ('O que é dataset?', 'Hardware', FALSE, 2),
      ('O que é dataset?', 'Programa de edição', FALSE, 3),
      ('O que é inteligência artificial forte?', 'Sistema sem aprendizagem', FALSE, 0),
      ('O que é inteligência artificial forte?', 'Conceito de IA com capacidade semelhante à inteligência humana geral', TRUE, 1),
      ('O que é inteligência artificial forte?', 'Calculadora automática', FALSE, 2),
      ('O que é inteligência artificial forte?', 'Programa simples', FALSE, 3),
      ('O que é inteligência artificial estreita (ANI)?', 'Sistema sem programação', FALSE, 0),
      ('O que é inteligência artificial estreita (ANI)?', 'Robô totalmente independente', FALSE, 1),
      ('O que é inteligência artificial estreita (ANI)?', 'IA especializada em tarefas específicas', TRUE, 2),
      ('O que é inteligência artificial estreita (ANI)?', 'IA com consciência humana', FALSE, 3),
      ('O que é AGI?', 'Banco de dados', FALSE, 0),
      ('O que é AGI?', 'Inteligência Artificial Geral capaz de realizar diversas tarefas intelectuais humanas', TRUE, 1),
      ('O que é AGI?', 'Sistema operacional', FALSE, 2),
      ('O que é AGI?', 'Aplicativo móvel', FALSE, 3),
      ('O que é singularidade tecnológica?', 'Atualização de software comum', FALSE, 0),
      ('O que é singularidade tecnológica?', 'Instalação de aplicativo', FALSE, 1),
      ('O que é singularidade tecnológica?', 'Criação de banco de dados', FALSE, 2),
      ('O que é singularidade tecnológica?', 'Hipótese de um futuro onde a IA supera amplamente a inteligência humana', TRUE, 3),
      ('Qual é um dos maiores desafios atuais da Inteligência Artificial?', 'Eliminar todos os computadores', FALSE, 0),
      ('Qual é um dos maiores desafios atuais da Inteligência Artificial?', 'Impedir qualquer inovação', FALSE, 1),
      ('Qual é um dos maiores desafios atuais da Inteligência Artificial?', 'Remover todos os dados', FALSE, 2),
      ('Qual é um dos maiores desafios atuais da Inteligência Artificial?', 'Garantir segurança, ética, transparência e uso responsável', TRUE, 3),
      ('O que é aprendizado por transferência (Transfer Learning)?', 'Processo de copiar arquivos', FALSE, 0),
      ('O que é aprendizado por transferência (Transfer Learning)?', 'Uso de um modelo previamente treinado para resolver uma nova tarefa relacionada', TRUE, 1),
      ('O que é aprendizado por transferência (Transfer Learning)?', 'Criação de um computador novo', FALSE, 2),
      ('O que é aprendizado por transferência (Transfer Learning)?', 'Exclusão de conhecimento de um modelo', FALSE, 3),
      ('Qual é a principal vantagem do Transfer Learning?', 'Remover a necessidade de dados', FALSE, 0),
      ('Qual é a principal vantagem do Transfer Learning?', 'Reduzir tempo e quantidade de dados necessários para treinar novos modelos', TRUE, 1),
      ('Qual é a principal vantagem do Transfer Learning?', 'Eliminar todos os erros da IA', FALSE, 2),
      ('Qual é a principal vantagem do Transfer Learning?', 'Substituir todos os programadores', FALSE, 3),
      ('O que é regularização em Machine Learning?', 'Aumento automático dos dados', FALSE, 0),
      ('O que é regularização em Machine Learning?', 'Técnica usada para reduzir overfitting e melhorar a generalização do modelo', TRUE, 1),
      ('O que é regularização em Machine Learning?', 'Processo para aumentar erros', FALSE, 2),
      ('O que é regularização em Machine Learning?', 'Exclusão do treinamento', FALSE, 3),
      ('O que é Dropout em redes neurais?', 'Processo de tradução', FALSE, 0),
      ('O que é Dropout em redes neurais?', 'Técnica que desativa aleatoriamente alguns neurônios durante o treinamento para evitar overfitting', TRUE, 1),
      ('O que é Dropout em redes neurais?', 'Método de apagar todo o modelo', FALSE, 2),
      ('O que é Dropout em redes neurais?', 'Sistema de armazenamento', FALSE, 3),
      ('O que é função de ativação em uma rede neural?', 'Sistema operacional', FALSE, 0),
      ('O que é função de ativação em uma rede neural?', 'Programa de instalação', FALSE, 1),
      ('O que é função de ativação em uma rede neural?', 'Função que determina a saída de um neurônio e permite aprendizado de padrões complexos', TRUE, 2),
      ('O que é função de ativação em uma rede neural?', 'Banco de dados', FALSE, 3),
      ('Qual é a função da camada de entrada em uma rede neural?', 'Gerar o resultado final', FALSE, 0),
      ('Qual é a função da camada de entrada em uma rede neural?', 'Armazenar arquivos', FALSE, 1),
      ('Qual é a função da camada de entrada em uma rede neural?', 'Receber os dados que serão processados pelo modelo', TRUE, 2),
      ('Qual é a função da camada de entrada em uma rede neural?', 'Controlar a internet', FALSE, 3),
      ('Qual é a função da camada de saída?', 'Receber dados externos', FALSE, 0),
      ('Qual é a função da camada de saída?', 'Treinar o computador físico', FALSE, 1),
      ('Qual é a função da camada de saída?', 'Produzir a previsão ou resultado final do modelo', TRUE, 2),
      ('Qual é a função da camada de saída?', 'Criar banco de dados', FALSE, 3),
      ('O que é backpropagation?', 'Processo de apagar dados', FALSE, 0),
      ('O que é backpropagation?', 'Método de segurança', FALSE, 1),
      ('O que é backpropagation?', 'Algoritmo usado para ajustar pesos de uma rede neural durante o treinamento', TRUE, 2),
      ('O que é backpropagation?', 'Tipo de hardware', FALSE, 3),
      ('O que representa o peso em uma rede neural?', 'Quantidade de arquivos', FALSE, 0),
      ('O que representa o peso em uma rede neural?', 'Tamanho físico do computador', FALSE, 1),
      ('O que representa o peso em uma rede neural?', 'Número de usuários', FALSE, 2),
      ('O que representa o peso em uma rede neural?', 'Valor que influencia a importância de uma conexão entre neurônios artificiais', TRUE, 3),
      ('O que é uma época (epoch) no treinamento de IA?', 'Uma passagem completa do conjunto de dados de treinamento pelo modelo', TRUE, 0),
      ('O que é uma época (epoch) no treinamento de IA?', 'Tipo de algoritmo', FALSE, 1),
      ('O que é uma época (epoch) no treinamento de IA?', 'Tempo de desligamento do computador', FALSE, 2),
      ('O que é uma época (epoch) no treinamento de IA?', 'Quantidade de usuários', FALSE, 3),
      ('O que é batch size?', 'Quantidade de aplicativos instalados', FALSE, 0),
      ('O que é batch size?', 'Quantidade de exemplos processados antes de atualizar os parâmetros do modelo', TRUE, 1),
      ('O que é batch size?', 'Número de computadores conectados', FALSE, 2),
      ('O que é batch size?', 'Tamanho do arquivo final', FALSE, 3),
      ('O que é learning rate?', 'Capacidade de armazenamento', FALSE, 0),
      ('O que é learning rate?', 'Número de usuários', FALSE, 1),
      ('O que é learning rate?', 'Taxa que controla o tamanho das atualizações dos parâmetros durante o treinamento', TRUE, 2),
      ('O que é learning rate?', 'Velocidade da internet', FALSE, 3),
      ('O que acontece quando o learning rate é muito alto?', 'O modelo pode ultrapassar a melhor solução e não aprender corretamente', TRUE, 0),
      ('O que acontece quando o learning rate é muito alto?', 'O modelo sempre fica perfeito', FALSE, 1),
      ('O que acontece quando o learning rate é muito alto?', 'Os dados são apagados', FALSE, 2),
      ('O que acontece quando o learning rate é muito alto?', 'O treinamento nunca acontece', FALSE, 3),
      ('O que mede a acurácia de um modelo?', 'Velocidade do computador', FALSE, 0),
      ('O que mede a acurácia de um modelo?', 'Quantidade de dados armazenados', FALSE, 1),
      ('O que mede a acurácia de um modelo?', 'Número de usuários', FALSE, 2),
      ('O que mede a acurácia de um modelo?', 'Percentual de previsões corretas realizadas pelo modelo', TRUE, 3),
      ('O que é precisão (precision) em classificação?', 'Velocidade do algoritmo', FALSE, 0),
      ('O que é precisão (precision) em classificação?', 'Total de dados usados', FALSE, 1),
      ('O que é precisão (precision) em classificação?', 'Quantidade de erros', FALSE, 2),
      ('O que é precisão (precision) em classificação?', 'Proporção de previsões positivas corretas entre todas as previsões positivas', TRUE, 3),
      ('O que é recall em Machine Learning?', 'Tempo de processamento', FALSE, 0),
      ('O que é recall em Machine Learning?', 'Número de arquivos recuperados', FALSE, 1),
      ('O que é recall em Machine Learning?', 'Capacidade de armazenamento', FALSE, 2),
      ('O que é recall em Machine Learning?', 'Capacidade do modelo de identificar corretamente casos positivos existentes', TRUE, 3),
      ('O que é F1-score?', 'Linguagem de programação', FALSE, 0),
      ('O que é F1-score?', 'Banco de dados', FALSE, 1),
      ('O que é F1-score?', 'Métrica que combina precisão e recall em uma única medida', TRUE, 2),
      ('O que é F1-score?', 'Tipo de rede neural', FALSE, 3),
      ('O que é validação cruzada?', 'Processo de compra', FALSE, 0),
      ('O que é validação cruzada?', 'Sistema de segurança física', FALSE, 1),
      ('O que é validação cruzada?', 'Método de apagar informações', FALSE, 2),
      ('O que é validação cruzada?', 'Técnica para avaliar o desempenho de um modelo usando diferentes divisões dos dados', TRUE, 3),
      ('O que é conjunto de teste em Machine Learning?', 'Arquivos temporários', FALSE, 0),
      ('O que é conjunto de teste em Machine Learning?', 'Dados usados apenas para criar o modelo', FALSE, 1),
      ('O que é conjunto de teste em Machine Learning?', 'Dados sem importância', FALSE, 2),
      ('O que é conjunto de teste em Machine Learning?', 'Dados usados para avaliar o desempenho final de um modelo treinado', TRUE, 3),
      ('O que é engenharia de dados em IA?', 'Criação de computadores', FALSE, 0),
      ('O que é engenharia de dados em IA?', 'Processo de coletar, organizar e preparar dados para análise e modelos', TRUE, 1),
      ('O que é engenharia de dados em IA?', 'Desenvolvimento de jogos', FALSE, 2),
      ('O que é engenharia de dados em IA?', 'Design gráfico', FALSE, 3),
      ('Por que dados de qualidade são importantes para IA?', 'Porque modelos dependem dos dados para aprender padrões corretos', TRUE, 0),
      ('Por que dados de qualidade são importantes para IA?', 'Porque substituem computadores', FALSE, 1),
      ('Por que dados de qualidade são importantes para IA?', 'Porque eliminam toda programação', FALSE, 2),
      ('Por que dados de qualidade são importantes para IA?', 'Porque impedem treinamento', FALSE, 3),
      ('O que é alucinação em modelos de IA?', 'Quando o computador desliga', FALSE, 0),
      ('O que é alucinação em modelos de IA?', 'Quando um modelo gera informações falsas ou incorretas apresentadas como verdadeiras', TRUE, 1),
      ('O que é alucinação em modelos de IA?', 'Quando dados são apagados', FALSE, 2),
      ('O que é alucinação em modelos de IA?', 'Quando o modelo fica mais rápido', FALSE, 3),
      ('Como reduzir alucinações em modelos de linguagem?', 'Desligando o modelo', FALSE, 0),
      ('Como reduzir alucinações em modelos de linguagem?', 'Impedindo qualquer pergunta', FALSE, 1),
      ('Como reduzir alucinações em modelos de linguagem?', 'Removendo todos os dados', FALSE, 2),
      ('Como reduzir alucinações em modelos de linguagem?', 'Usando melhores dados, instruções claras e sistemas de verificação', TRUE, 3),
      ('Qual é a vantagem do RAG?', 'Elimina todos os dados', FALSE, 0),
      ('Qual é a vantagem do RAG?', 'Reduz capacidade da IA', FALSE, 1),
      ('Qual é a vantagem do RAG?', 'Impede treinamento', FALSE, 2),
      ('Qual é a vantagem do RAG?', 'Permite respostas mais atualizadas e baseadas em fontes específicas', TRUE, 3),
      ('O que é um modelo de difusão?', 'Modelo generativo usado principalmente para criar imagens através de processos de transformação de ruído', TRUE, 0),
      ('O que é um modelo de difusão?', 'Banco de dados', FALSE, 1),
      ('O que é um modelo de difusão?', 'Sistema financeiro', FALSE, 2),
      ('O que é um modelo de difusão?', 'Antivírus', FALSE, 3),
      ('O que são GANs (Generative Adversarial Networks)?', 'Sistemas sem treinamento', FALSE, 0),
      ('O que são GANs (Generative Adversarial Networks)?', 'Redes formadas por gerador e discriminador que competem para criar dados realistas', TRUE, 1),
      ('O que são GANs (Generative Adversarial Networks)?', 'Sistemas bancários', FALSE, 2),
      ('O que são GANs (Generative Adversarial Networks)?', 'Redes sociais', FALSE, 3),
      ('O que é um chatbot inteligente?', 'Sistema conversacional que utiliza IA para interagir com usuários', TRUE, 0),
      ('O que é um chatbot inteligente?', 'Banco de dados simples', FALSE, 1),
      ('O que é um chatbot inteligente?', 'Editor de texto', FALSE, 2),
      ('O que é um chatbot inteligente?', 'Programa sem respostas', FALSE, 3),
      ('O que é automação robótica de processos (RPA)?', 'Rede social', FALSE, 0),
      ('O que é automação robótica de processos (RPA)?', 'Sistema financeiro', FALSE, 1),
      ('O que é automação robótica de processos (RPA)?', 'Criação de robôs físicos apenas', FALSE, 2),
      ('O que é automação robótica de processos (RPA)?', 'Tecnologia que automatiza tarefas repetitivas usando software', TRUE, 3),
      ('O que diferencia RPA tradicional de IA?', 'IA permite decisões mais complexas baseadas em aprendizagem', TRUE, 0),
      ('O que diferencia RPA tradicional de IA?', 'RPA sempre aprende sozinho', FALSE, 1),
      ('O que diferencia RPA tradicional de IA?', 'Não existe diferença', FALSE, 2),
      ('O que diferencia RPA tradicional de IA?', 'IA não usa dados', FALSE, 3),
      ('O que é IA embarcada?', 'Banco de dados', FALSE, 0),
      ('O que é IA embarcada?', 'Inteligência artificial integrada diretamente em dispositivos ou equipamentos', TRUE, 1),
      ('O que é IA embarcada?', 'Programa sem hardware', FALSE, 2),
      ('O que é IA embarcada?', 'IA apenas em servidores', FALSE, 3),
      ('O que é Edge AI?', 'Processamento de IA realizado próximo ao local onde os dados são gerados', TRUE, 0),
      ('O que é Edge AI?', 'Uso exclusivo da nuvem', FALSE, 1),
      ('O que é Edge AI?', 'Sistema sem internet', FALSE, 2),
      ('O que é Edge AI?', 'Armazenamento manual', FALSE, 3),
      ('O que é computação quântica aplicada à IA?', 'Substituição de todos os dados', FALSE, 0),
      ('O que é computação quântica aplicada à IA?', 'Criação de redes sociais', FALSE, 1),
      ('O que é computação quântica aplicada à IA?', 'Uso de computadores quânticos para potencialmente acelerar determinados cálculos de IA', TRUE, 2),
      ('O que é computação quântica aplicada à IA?', 'Método de pagamento', FALSE, 3),
      ('O que é segurança de modelos de IA?', 'Proteção contra manipulação, ataques e uso indevido dos modelos', TRUE, 0),
      ('O que é segurança de modelos de IA?', 'Exclusão dos usuários', FALSE, 1),
      ('O que é segurança de modelos de IA?', 'Redução da inteligência', FALSE, 2),
      ('O que é segurança de modelos de IA?', 'Remoção do modelo', FALSE, 3),
      ('O que é alinhamento de IA?', 'Criação de hardware', FALSE, 0),
      ('O que é alinhamento de IA?', 'Aumento de velocidade', FALSE, 1),
      ('O que é alinhamento de IA?', 'Redução de dados', FALSE, 2),
      ('O que é alinhamento de IA?', 'Processo de garantir que sistemas de IA atuem de acordo com objetivos e valores humanos', TRUE, 3),
      ('O que é IA responsável?', 'Desenvolvimento e uso de IA considerando ética, segurança e impacto social', TRUE, 0),
      ('O que é IA responsável?', 'IA sem regras', FALSE, 1),
      ('O que é IA responsável?', 'Sistema sem dados', FALSE, 2),
      ('O que é IA responsável?', 'Automação sem controle', FALSE, 3),
      ('O que é transparência em IA?', 'Impedir auditoria', FALSE, 0),
      ('O que é transparência em IA?', 'Remover dados', FALSE, 1),
      ('O que é transparência em IA?', 'Ocultar funcionamento do modelo', FALSE, 2),
      ('O que é transparência em IA?', 'Capacidade de compreender como decisões do sistema são tomadas', TRUE, 3),
      ('O que é auditoria de algoritmos?', 'Instalação de computadores', FALSE, 0),
      ('O que é auditoria de algoritmos?', 'Avaliação dos modelos para identificar problemas, riscos e conformidade', TRUE, 1),
      ('O que é auditoria de algoritmos?', 'Venda de softwares', FALSE, 2),
      ('O que é auditoria de algoritmos?', 'Criação de algoritmos', FALSE, 3),
      ('O que é IA generativa multimodal?', 'IA apenas textual', FALSE, 0),
      ('O que é IA generativa multimodal?', 'IA capaz de trabalhar e criar conteúdos usando diferentes tipos de dados', TRUE, 1),
      ('O que é IA generativa multimodal?', 'Sistema sem entrada', FALSE, 2),
      ('O que é IA generativa multimodal?', 'Programa básico', FALSE, 3),
      ('O que é copiloto de IA?', 'Sistema de segurança física', FALSE, 0),
      ('O que é copiloto de IA?', 'Assistente inteligente que auxilia usuários em tarefas específicas', TRUE, 1),
      ('O que é copiloto de IA?', 'Banco de dados', FALSE, 2),
      ('O que é copiloto de IA?', 'Rede de computadores', FALSE, 3),
      ('O que é agente autônomo de IA?', 'Programa sem decisões', FALSE, 0),
      ('O que é agente autônomo de IA?', 'Editor de imagens', FALSE, 1),
      ('O que é agente autônomo de IA?', 'Sistema capaz de planejar e executar ações para atingir objetivos', TRUE, 2),
      ('O que é agente autônomo de IA?', 'Arquivo digital', FALSE, 3),
      ('O que é otimização de modelos de IA?', 'Processo de melhorar eficiência, velocidade ou desempenho do modelo', TRUE, 0),
      ('O que é otimização de modelos de IA?', 'Reduzir dados sempre', FALSE, 1),
      ('O que é otimização de modelos de IA?', 'Bloquear usuários', FALSE, 2),
      ('O que é otimização de modelos de IA?', 'Apagar o modelo', FALSE, 3),
      ('O que é compressão de modelos?', 'Técnicas para reduzir tamanho e custo computacional de modelos de IA', TRUE, 0),
      ('O que é compressão de modelos?', 'Aumento do tamanho do modelo', FALSE, 1),
      ('O que é compressão de modelos?', 'Exclusão de treinamento', FALSE, 2),
      ('O que é compressão de modelos?', 'Criação de dados', FALSE, 3),
      ('O que é inferência em tempo real?', 'Exclusão de informações', FALSE, 0),
      ('O que é inferência em tempo real?', 'Treinamento inicial', FALSE, 1),
      ('O que é inferência em tempo real?', 'Geração de respostas ou previsões rapidamente após receber uma entrada', TRUE, 2),
      ('O que é inferência em tempo real?', 'Criação de hardware', FALSE, 3),
      ('Qual é um desafio dos grandes modelos de IA?', 'Alto custo computacional e necessidade de grandes volumes de dados', TRUE, 0),
      ('Qual é um desafio dos grandes modelos de IA?', 'Ausência de algoritmos', FALSE, 1),
      ('Qual é um desafio dos grandes modelos de IA?', 'Não utilizar energia', FALSE, 2),
      ('Qual é um desafio dos grandes modelos de IA?', 'Falta completa de capacidade', FALSE, 3),
      ('O que é democratização da IA?', 'Impedir inovação', FALSE, 0),
      ('O que é democratização da IA?', 'Tornar ferramentas de IA acessíveis para mais pessoas e organizações', TRUE, 1),
      ('O que é democratização da IA?', 'Eliminar tecnologia', FALSE, 2),
      ('O que é democratização da IA?', 'Restringir totalmente o uso', FALSE, 3),
      ('Qual é uma aplicação avançada da IA na medicina?', 'Controle de pagamentos', FALSE, 0),
      ('Qual é uma aplicação avançada da IA na medicina?', 'Criação de jogos', FALSE, 1),
      ('Qual é uma aplicação avançada da IA na medicina?', 'Apenas impressão de documentos', FALSE, 2),
      ('Qual é uma aplicação avançada da IA na medicina?', 'Auxílio no diagnóstico através da análise de imagens e dados médicos', TRUE, 3),
      ('Qual é o principal objetivo do desenvolvimento responsável de Inteligência Artificial?', 'Criar sistemas úteis, seguros, éticos e confiáveis para a sociedade', TRUE, 0),
      ('Qual é o principal objetivo do desenvolvimento responsável de Inteligência Artificial?', 'Eliminar qualquer tecnologia existente', FALSE, 1),
      ('Qual é o principal objetivo do desenvolvimento responsável de Inteligência Artificial?', 'Substituir todas as pessoas imediatamente', FALSE, 2),
      ('Qual é o principal objetivo do desenvolvimento responsável de Inteligência Artificial?', 'Impedir evolução científica', FALSE, 3)
    ) AS a(statement, label, is_correct, display_order)
    ON q.statement = a.statement;

    DROP TABLE tmp_new_questions_ia_dificil2;

    RAISE NOTICE '87 perguntas de Inteligência Artificial (difícil, lote 2) inseridas com sucesso.';
  END IF;
END $$;

COMMIT;
