-- Alternativas (BE-003, regularização) — Finanças difícil lote 2: 047#26-31 e 073#1-19.
-- Segue docs/quiz-v2-alternativas-padrao.md e a regra do dono (2026-10-07): a resposta CERTA NÃO muda;
-- só o texto das alternativas ERRADAS é ajustado para ter tamanho parecido ao da certa.
-- Segurança: só altera question_alternatives.label, só de alternativas erradas (is_correct = FALSE), e só se o
-- texto atual ainda for exatamente o original (nunca sobrescreve edição posterior; idempotente). Não toca em ids,
-- is_correct, display_order nem perguntas. O runner já envolve o ficheiro numa transação.
-- Regra 9 do padrão: as explicações que citavam as alternativas erradas antigas são reescritas no segundo bloco,
-- também só se o texto atual ainda for exatamente o original.

DO $$
DECLARE
  v_updated INTEGER;
BEGIN
  UPDATE question_alternatives a
  SET label = v.new_label
  FROM questions q,
  (VALUES
    ('seed_financas_dificil_v1', 'Uma empresa aumenta suas vendas, mas seus custos crescem ainda mais rapidamente. O que pode acontecer?', 1, 'A empresa necessariamente fica mais eficiente', 'A empresa passa a ter lucro maior em todas as situações'),
    ('seed_financas_dificil_v1', 'Uma empresa aumenta suas vendas, mas seus custos crescem ainda mais rapidamente. O que pode acontecer?', 2, 'Os custos deixam de existir', 'Os custos acabam sendo cobertos automaticamente pelas vendas'),
    ('seed_financas_dificil_v1', 'Uma empresa aumenta suas vendas, mas seus custos crescem ainda mais rapidamente. O que pode acontecer?', 3, 'O lucro necessariamente dobra', 'O lucro cresce na mesma proporção do aumento das vendas'),
    ('seed_financas_dificil_v1', 'O que é ponto de equilíbrio financeiro de uma atividade?', 0, 'Quantidade de funcionários', 'Quantidade mínima de vendas que a empresa precisa de manter para pagar apenas os salários dos funcionários'),
    ('seed_financas_dificil_v1', 'O que é ponto de equilíbrio financeiro de uma atividade?', 1, 'Momento em que a empresa sempre obtém lucro máximo', 'Momento em que a empresa passa a obter o lucro máximo possível dentro do seu mercado'),
    ('seed_financas_dificil_v1', 'O que é ponto de equilíbrio financeiro de uma atividade?', 2, 'Valor máximo das vendas', 'Valor total das vendas previstas para o ano, considerando todos os custos e despesas'),
    ('seed_financas_dificil_v1', 'Por que separar despesas pessoais das despesas de um negócio é importante?', 1, 'Elimina impostos', 'Dispensa o pagamento de impostos sobre os lucros do negócio'),
    ('seed_financas_dificil_v1', 'Por que separar despesas pessoais das despesas de um negócio é importante?', 2, 'Garante lucro', 'Assegura que o negócio terá lucro todos os meses do ano'),
    ('seed_financas_dificil_v1', 'Por que separar despesas pessoais das despesas de um negócio é importante?', 3, 'Aumenta automaticamente as vendas', 'Faz com que as vendas do negócio aumentem de forma automática'),
    ('seed_financas_dificil_v1', 'O que pode acontecer quando uma pessoa toma decisões financeiras baseadas apenas em emoções?', 0, 'Garante melhores investimentos', 'Assegura investimentos melhores por reagir rápido às oportunidades'),
    ('seed_financas_dificil_v1', 'O que pode acontecer quando uma pessoa toma decisões financeiras baseadas apenas em emoções?', 2, 'Elimina riscos', 'Reduz os riscos porque a pessoa age com confiança e rapidez'),
    ('seed_financas_dificil_v1', 'O que pode acontecer quando uma pessoa toma decisões financeiras baseadas apenas em emoções?', 3, 'Garante lucro', 'Garante lucro mais rápido por aproveitar o momento do mercado'),
    ('seed_financas_dificil_v1', 'Qual é uma característica de uma decisão financeira bem fundamentada?', 0, 'Ignora riscos', 'Segue a opinião de conhecidos sem comparar as outras opções'),
    ('seed_financas_dificil_v1', 'Qual é uma característica de uma decisão financeira bem fundamentada?', 1, 'Baseia-se apenas em rumores', 'Escolhe o produto que tem a publicidade mais convincente do mercado'),
    ('seed_financas_dificil_v1', 'Qual é uma característica de uma decisão financeira bem fundamentada?', 2, 'Depende exclusivamente de publicidade', 'Deixa de lado os riscos para focar apenas no ganho esperado'),
    ('seed_financas_dificil_v1', 'O que é custo de oportunidade?', 0, 'Um tipo de salário', 'O valor pago em juros ao escolher um empréstimo no banco'),
    ('seed_financas_dificil_v1', 'O que é custo de oportunidade?', 1, 'Um imposto bancário', 'O custo total de produzir um bem ou serviço numa empresa'),
    ('seed_financas_dificil_v1', 'O que é custo de oportunidade?', 3, 'Uma conta de eletricidade', 'A taxa cobrada por um banco para manter uma conta aberta'),
    ('seed_financas_dificil_v2', 'O que é alocação estratégica de ativos?', 0, 'Guardar todo dinheiro em casa', 'Compra e venda frequente de ativos para aproveitar as oscilações de curto prazo do mercado'),
    ('seed_financas_dificil_v2', 'O que é alocação estratégica de ativos?', 1, 'Venda de todos os ativos financeiros', 'Concentração de todo o capital num único ativo escolhido por ter rendimento mais elevado'),
    ('seed_financas_dificil_v2', 'O que é alocação estratégica de ativos?', 3, 'Compra aleatória de qualquer investimento', 'Escolha de investimentos conforme as notícias do dia, sem uma divisão prévia dos recursos entre as classes de ativos disponíveis'),
    ('seed_financas_dificil_v2', 'O que é volatilidade em investimentos?', 1, 'Garantia de lucro constante', 'Valor mínimo que um ativo pode atingir durante um ano'),
    ('seed_financas_dificil_v2', 'O que é volatilidade em investimentos?', 2, 'Valor inicial investido', 'Garantia de que o rendimento do ativo será sempre constante'),
    ('seed_financas_dificil_v2', 'O que é volatilidade em investimentos?', 3, 'Taxa fixa de rendimento', 'Taxa fixa de rendimento prometida a quem investe no ativo'),
    ('seed_financas_dificil_v2', 'O que é risco sistêmico?', 0, 'Risco causado apenas por uma empresa', 'Risco ligado só ao desempenho de uma empresa em particular'),
    ('seed_financas_dificil_v2', 'O que é risco sistêmico?', 2, 'Risco de pequenos gastos pessoais', 'Risco que desaparece quando a carteira é bem diversificada'),
    ('seed_financas_dificil_v2', 'O que é risco sistêmico?', 3, 'Risco eliminado pela diversificação', 'Risco restrito a um único setor da economia do país'),
    ('seed_financas_dificil_v2', 'O que é risco não sistêmico?', 0, 'Risco que afeta todos os mercados', 'Risco que atinge todos os mercados ao mesmo tempo e não depende da carteira'),
    ('seed_financas_dificil_v2', 'O que é risco não sistêmico?', 2, 'Alteração cambial global', 'Risco ligado a alterações do câmbio ou da inflação que afetam todas as empresas'),
    ('seed_financas_dificil_v2', 'O que é risco não sistêmico?', 3, 'Inflação mundial', 'Risco que aumenta quando o investidor divide o dinheiro por vários ativos'),
    ('seed_financas_dificil_v2', 'O que representa o índice de Sharpe?', 1, 'Valor total de uma empresa', 'Relação entre o valor da empresa e o número de seus acionistas'),
    ('seed_financas_dificil_v2', 'O que representa o índice de Sharpe?', 2, 'Quantidade de investidores', 'Relação entre a taxa de inflação e o rendimento obtido no ano'),
    ('seed_financas_dificil_v2', 'O que representa o índice de Sharpe?', 3, 'Taxa de inflação', 'Relação entre o lucro de uma empresa e o total das suas dívidas registradas no balanço anual'),
    ('seed_financas_dificil_v2', 'O que é análise fundamentalista de empresas?', 0, 'Análise de publicidade', 'Observação dos gráficos de preço diários para prever a próxima oscilação'),
    ('seed_financas_dificil_v2', 'O que é análise fundamentalista de empresas?', 1, 'Escolha baseada em sorte', 'Escolha de ações baseada na campanha publicitária feita pela empresa'),
    ('seed_financas_dificil_v2', 'O que é análise fundamentalista de empresas?', 3, 'Observação apenas do preço diário', 'Decisão de compra baseada na opinião de amigos e colegas sobre o futuro da empresa no mercado'),
    ('seed_financas_dificil_v2', 'O que é análise técnica?', 0, 'Controle de despesas pessoais', 'Avaliação dos resultados e do balanço de uma empresa para estimar o valor'),
    ('seed_financas_dificil_v2', 'O que é análise técnica?', 1, 'Análise dos funcionários de uma empresa', 'Controle das despesas e das receitas de uma pessoa durante o mês'),
    ('seed_financas_dificil_v2', 'O que é análise técnica?', 3, 'Avaliação de impostos', 'Cálculo dos impostos a pagar sobre os lucros obtidos pela empresa no fim de cada período fiscal'),
    ('seed_financas_dificil_v2', 'O que é valuation?', 0, 'Controle de salário', 'Processo de reduzir os impostos pagos por uma empresa'),
    ('seed_financas_dificil_v2', 'O que é valuation?', 2, 'Processo de criação de uma dívida', 'Processo de criar uma dívida para financiar um ativo'),
    ('seed_financas_dificil_v2', 'O que é valuation?', 3, 'Redução de impostos', 'Controle do salário pago aos funcionários da empresa'),
    ('seed_financas_dificil_v2', 'O que é valor intrínseco de uma empresa?', 0, 'Total de despesas', 'Preço do ativo definido apenas pela oferta e procura do dia'),
    ('seed_financas_dificil_v2', 'O que é valor intrínseco de uma empresa?', 1, 'Preço definido apenas pelo mercado', 'Total das despesas registradas pela empresa durante o ano'),
    ('seed_financas_dificil_v2', 'O que é valor intrínseco de uma empresa?', 2, 'Valor do salário dos funcionários', 'Valor dos salários pagos aos funcionários da empresa'),
    ('seed_financas_dificil_v2', 'O que é uma bolha financeira?', 0, 'Crescimento garantido', 'Situação em que os preços dos ativos caem de forma normal por ajustes do mercado'),
    ('seed_financas_dificil_v2', 'O que é uma bolha financeira?', 2, 'Economia sem investimentos', 'Período em que o crescimento dos preços é garantido pelo governo ao mercado'),
    ('seed_financas_dificil_v2', 'O que é uma bolha financeira?', 3, 'Queda normal de preços', 'Economia em que não há investimentos e os preços ficam sempre estáveis, sem qualquer variação no mercado'),
    ('seed_financas_dificil_v2', 'O que é especulação financeira?', 0, 'Controle de orçamento pessoal', 'Controle do orçamento pessoal para guardar dinheiro todos os meses'),
    ('seed_financas_dificil_v2', 'O que é especulação financeira?', 1, 'Guardar dinheiro sem objetivo', 'Guardar dinheiro durante anos sem ter um objetivo definido'),
    ('seed_financas_dificil_v2', 'O que é especulação financeira?', 3, 'Pagamento de impostos', 'Pagamento dos impostos devidos sobre os rendimentos obtidos'),
    ('seed_financas_dificil_v2', 'O que é arbitragem financeira?', 0, 'Redução de salários', 'Redução dos salários para diminuir o custo de uma empresa no mercado'),
    ('seed_financas_dificil_v2', 'O que é arbitragem financeira?', 2, 'Criação de dinheiro', 'Criação de dinheiro novo por um banco para emprestar aos clientes'),
    ('seed_financas_dificil_v2', 'O que é arbitragem financeira?', 3, 'Cancelamento de investimentos', 'Cancelamento de investimentos quando o preço do ativo começa a cair, para evitar perdas maiores no mercado'),
    ('seed_financas_dificil_v2', 'O que é derivativo financeiro?', 0, 'Conta bancária comum', 'Conta bancária usada para guardar o dinheiro das despesas'),
    ('seed_financas_dificil_v2', 'O que é derivativo financeiro?', 2, 'Cartão de crédito', 'Cartão de crédito com limite definido pelo banco emissor, usado para comprar a prazo nas lojas'),
    ('seed_financas_dificil_v2', 'O que é derivativo financeiro?', 3, 'Salário mensal', 'Salário mensal pago pela empresa ao funcionário'),
    ('seed_financas_dificil_v2', 'O que é contrato futuro?', 1, 'Empréstimo pessoal', 'Empréstimo pessoal pago em prestações mensais com juros fixos'),
    ('seed_financas_dificil_v2', 'O que é contrato futuro?', 2, 'Conta de poupança', 'Conta de poupança com rendimento garantido ao fim do ano'),
    ('seed_financas_dificil_v2', 'O que é contrato futuro?', 3, 'Compra sem contrato', 'Compra de um ativo feita à vista, sem qualquer acordo prévio'),
    ('seed_financas_dificil_v2', 'O que é hedge financeiro?', 0, 'Estratégia para aumentar despesas', 'Estratégia usada para aumentar as despesas e reduzir os lucros'),
    ('seed_financas_dificil_v2', 'O que é hedge financeiro?', 1, 'Forma de eliminar todos os riscos', 'Forma de eliminar todos os riscos de qualquer tipo de investimento'),
    ('seed_financas_dificil_v2', 'O que é hedge financeiro?', 3, 'Tipo de imposto', 'Imposto cobrado pelo governo sobre os ganhos de capital obtidos com a venda de ativos financeiros'),
    ('seed_financas_dificil_v2', 'O que é gestão de risco financeiro?', 1, 'Evitar qualquer planejamento', 'Processo de evitar qualquer planejamento para reduzir custos'),
    ('seed_financas_dificil_v2', 'O que é gestão de risco financeiro?', 2, 'Fazer investimentos aleatórios', 'Prática de fazer investimentos aleatórios para diversificar'),
    ('seed_financas_dificil_v2', 'O que é gestão de risco financeiro?', 3, 'Ignorar riscos', 'Decisão de ignorar riscos pequenos para focar nos lucros e nos ganhos de curto prazo'),
    ('seed_financas_dificil_v2', 'O que é governança corporativa?', 0, 'Método de venda', 'Método de venda usado pelas empresas para aumentar a participação no mercado'),
    ('seed_financas_dificil_v2', 'O que é governança corporativa?', 1, 'Apenas controle de funcionários', 'Conjunto de controles aplicados apenas aos funcionários de uma empresa'),
    ('seed_financas_dificil_v2', 'O que é governança corporativa?', 2, 'Sistema bancário', 'Sistema bancário responsável por emprestar dinheiro às empresas do país'),
    ('seed_financas_dificil_v2', 'O que é compliance financeiro?', 1, 'Redução de funcionários', 'Conjunto de cortes feitos para reduzir o número de funcionários'),
    ('seed_financas_dificil_v2', 'O que é compliance financeiro?', 2, 'Aumento automático de lucro', 'Mecanismo que aumenta o lucro da empresa de forma automática'),
    ('seed_financas_dificil_v2', 'O que é compliance financeiro?', 3, 'Criação de dívidas', 'Conjunto de regras para criar dívidas com custos mais baixos para a empresa'),
    ('seed_financas_dificil_v2', 'O que é lavagem de dinheiro?', 1, 'Investimento legítimo', 'Investimento legítimo feito com recursos de origem comprovada'),
    ('seed_financas_dificil_v2', 'O que é lavagem de dinheiro?', 2, 'Economia pessoal', 'Economia pessoal feita com o dinheiro ganho do trabalho regular'),
    ('seed_financas_dificil_v2', 'O que é lavagem de dinheiro?', 3, 'Pagamento de impostos', 'Pagamento regular de impostos sobre os rendimentos obtidos')
  ) AS v(source, statement, display_order, old_label, new_label)
  WHERE q.source = v.source
    AND q.statement = v.statement
    AND a.question_id = q.id
    AND a.display_order = v.display_order
    AND a.is_correct = FALSE
    AND a.label = v.old_label;

  GET DIAGNOSTICS v_updated = ROW_COUNT;
  RAISE NOTICE 'Alternativas Finanças difícil lote 2: 047#26-31 e 073#1-19: % alternativa(s) errada(s) atualizada(s) (esperado: 75).', v_updated;
END $$;

DO $$
DECLARE
  v_updated INTEGER;
BEGIN
  UPDATE questions q
  SET explanation = v.new_explanation
  FROM (VALUES
    ('seed_financas_dificil_v1', 'Uma empresa aumenta suas vendas, mas seus custos crescem ainda mais rapidamente. O que pode acontecer?', 'Vender mais não basta: o lucro depende da diferença entre a receita e os custos. Se os custos sobem mais depressa do que as vendas, sobra menos por cada unidade vendida, e a margem de lucro pode diminuir, até virar prejuízo. A empresa não fica mais eficiente, os custos não desaparecem e o lucro não dobra.', 'Vender mais não basta: o lucro depende da diferença entre a receita e os custos. Se os custos sobem mais depressa do que as vendas, sobra menos por cada unidade vendida, e a margem de lucro pode diminuir, até virar prejuízo. Por isso nem o lucro maior nem a cobertura automática dos custos estão garantidos.'),
    ('seed_financas_dificil_v1', 'O que é ponto de equilíbrio financeiro de uma atividade?', 'Ponto de equilíbrio é o nível de vendas em que as receitas cobrem os custos e despesas considerados: nem lucro, nem prejuízo. É uma referência para saber quanto é preciso vender antes de começar a lucrar. Não é o lucro máximo, o total de funcionários nem o valor máximo das vendas.', 'Ponto de equilíbrio é o nível de vendas em que as receitas cobrem os custos e despesas considerados: nem lucro, nem prejuízo. Serve de referência para saber quanto é preciso vender antes de começar a lucrar. Não é o lucro máximo nem um valor de vendas previsto.'),
    ('seed_financas_dificil_v1', 'Por que separar despesas pessoais das despesas de um negócio é importante?', 'Misturar as contas esconde o desempenho real do negócio: não se sabe se ele dá lucro ou se está a ser sustentado pelo dinheiro pessoal. Separar facilita o controle financeiro e a análise. Não elimina impostos, não garante lucro e não aumenta vendas.', 'Misturar as contas esconde o desempenho real do negócio: não se sabe se ele dá lucro ou se está a ser sustentado pelo dinheiro pessoal. Separar facilita o controle financeiro e a análise. Isso não dispensa impostos, não assegura lucro e não aumenta as vendas.'),
    ('seed_financas_dificil_v1', 'O que pode acontecer quando uma pessoa toma decisões financeiras baseadas apenas em emoções?', 'Decisões guiadas só pela emoção, como medo ou euforia, tendem a ser impulsivas: comprar por impulso ou vender em pânico, por exemplo. Isso aumenta a chance de decisões inadequadas. A emoção não garante melhores investimentos, nem lucro, e não elimina riscos.', 'Decisões guiadas só pela emoção, como medo ou euforia, tendem a ser impulsivas: comprar por impulso ou vender em pânico, por exemplo. Isso aumenta a chance de decisões inadequadas. A emoção não assegura melhores investimentos, nem lucro, e não reduz riscos.'),
    ('seed_financas_dificil_v1', 'Qual é uma característica de uma decisão financeira bem fundamentada?', 'Uma boa decisão financeira considera os objetivos, os custos, os riscos, as alternativas e a capacidade financeira de quem decide. Ignorar riscos, seguir rumores ou depender só de publicidade são sinais de uma decisão mal fundamentada.', 'Uma boa decisão financeira considera os objetivos, os custos, os riscos, as alternativas e a capacidade financeira de quem decide. Seguir só a opinião de conhecidos, a publicidade ou o ganho esperado, deixando os riscos de lado, são sinais de uma decisão mal fundamentada.'),
    ('seed_financas_dificil_v1', 'O que é custo de oportunidade?', 'Custo de oportunidade é o benefício perdido ao escolher uma alternativa em vez de outra. Todo uso do dinheiro ou do tempo tem esse custo: gastar 1.000 MZN em algo é abrir mão do que esse dinheiro renderia aplicado, por exemplo. Não é salário, imposto nem conta de eletricidade.', 'Custo de oportunidade é o benefício perdido ao escolher uma alternativa em vez de outra. Todo uso do dinheiro ou do tempo tem esse custo: gastar 1.000 MZN em algo é abrir mão do que esse dinheiro renderia aplicado, por exemplo. Não é juro pago, custo de produção nem taxa bancária.'),
    ('seed_financas_dificil_v2', 'O que é alocação estratégica de ativos?', 'Alocação estratégica é a distribuição planejada dos investimentos entre classes de ativos para atingir objetivos de longo prazo. Define-se uma divisão-alvo e ela é revista de vez em quando, em vez de mudar a cada notícia. Não é guardar tudo em casa, vender tudo nem comprar ao acaso.', 'Alocação estratégica é a distribuição planejada dos investimentos entre classes de ativos para atingir objetivos de longo prazo. Define-se uma divisão-alvo e ela é revista de vez em quando, em vez de mudar a cada notícia. Não é negociar com frequência nem concentrar tudo num só ativo.'),
    ('seed_financas_dificil_v2', 'O que é volatilidade em investimentos?', 'Volatilidade mede quanto o preço de um ativo varia ao longo do tempo. Quanto mais varia, mais incerto é o valor no curto prazo, por isso é usada como medida de risco. Não é lucro constante, valor inicial investido nem taxa fixa de rendimento.', 'Volatilidade mede quanto o preço de um ativo varia ao longo do tempo. Quanto mais varia, mais incerto é o valor no curto prazo, por isso é usada como medida de risco. Não é um valor mínimo, um rendimento constante nem uma taxa fixa.'),
    ('seed_financas_dificil_v2', 'O que é risco sistêmico?', 'Risco sistêmico é o que afeta todo o mercado ou o sistema financeiro, como uma crise económica. Como atinge tudo ao mesmo tempo, a diversificação não o elimina. Difere do risco de uma só empresa, que se pode reduzir com diversificação.', 'Risco sistêmico é o que afeta todo o mercado ou o sistema financeiro, como uma crise económica. Como atinge tudo ao mesmo tempo, a diversificação não o elimina. Difere do risco de uma só empresa ou de um só setor, que se pode reduzir diversificando.'),
    ('seed_financas_dificil_v2', 'O que é risco não sistêmico?', 'Risco não sistêmico é o específico de uma empresa ou setor, como um problema de gestão ou a perda de um cliente importante. Pode ser reduzido pela diversificação, porque a perda numa empresa é compensada por outras. Alterações cambiais globais e inflação mundial afetam todo o sistema e são sistêmicas.', 'Risco não sistêmico é o específico de uma empresa ou setor, como um problema de gestão ou a perda de um cliente importante. Pode ser reduzido pela diversificação, porque a perda numa empresa é compensada por outras. Câmbio e inflação afetam todo o sistema e são riscos sistêmicos.'),
    ('seed_financas_dificil_v2', 'O que representa o índice de Sharpe?', 'O índice de Sharpe relaciona o retorno obtido com o risco assumido para obtê-lo. Serve para comparar investimentos: entre dois com o mesmo retorno, o de maior índice o conseguiu com menos risco. Não mede o valor de uma empresa, o número de investidores nem a inflação.', 'O índice de Sharpe relaciona o retorno obtido com o risco assumido para obtê-lo. Serve para comparar investimentos: entre dois com o mesmo retorno, o de maior índice o conseguiu com menos risco. Não mede o valor de uma empresa, o número de acionistas nem a inflação.'),
    ('seed_financas_dificil_v2', 'O que é análise fundamentalista de empresas?', 'Análise fundamentalista avalia os indicadores financeiros, os resultados e as perspectivas de uma empresa para estimar se vale o preço pedido. Olha para o negócio, e não só para o preço do dia. Não é análise de publicidade, escolha por sorte nem observação apenas do preço diário.', 'Análise fundamentalista avalia os indicadores financeiros, os resultados e as perspectivas de uma empresa para estimar se vale o preço pedido. Olha para o negócio, e não só para o preço do dia. Não é olhar gráficos, seguir publicidade nem a opinião de amigos.'),
    ('seed_financas_dificil_v2', 'O que é análise técnica?', 'Análise técnica estuda gráficos e movimentos históricos de preços para identificar tendências. Ao contrário da fundamentalista, que olha para o negócio, a técnica olha para o comportamento do preço. Não é controle de despesas, análise de funcionários nem avaliação de impostos.', 'Análise técnica estuda gráficos e movimentos históricos de preços para identificar tendências. Ao contrário da fundamentalista, que olha para o negócio, a técnica olha para o comportamento do preço. Não é avaliar balanços, controlar despesas nem calcular impostos.'),
    ('seed_financas_dificil_v2', 'O que é valuation?', 'Valuation é o processo de estimar o valor de uma empresa ou ativo, normalmente com base em seus resultados, fluxo de caixa e perspectivas. Comparar esse valor com o preço de mercado ajuda a ver se o ativo está caro ou barato. Não é controle de salário, criação de dívida nem redução de impostos.', 'Valuation é o processo de estimar o valor de uma empresa ou ativo, normalmente com base em seus resultados, fluxo de caixa e perspectivas. Comparar esse valor com o preço de mercado ajuda a ver se o ativo está caro ou barato. Não é reduzir impostos, criar dívida nem controlar salários.'),
    ('seed_financas_dificil_v2', 'O que é especulação financeira?', 'Especulação é comprar ou vender buscando lucro com as variações de preço no mercado, em geral no curto prazo. Pode render ganhos, mas tem risco alto de perdas. Não é controlar o orçamento, guardar dinheiro sem objetivo nem pagar impostos.', 'Especulação é comprar ou vender buscando lucro com as variações de preço no mercado, em geral no curto prazo. Pode render ganhos, mas tem risco alto de perdas. Não é controlar o orçamento, poupar sem objetivo nem pagar impostos.'),
    ('seed_financas_dificil_v2', 'O que é arbitragem financeira?', 'Arbitragem é aproveitar diferenças de preço do mesmo ativo em mercados diferentes: compra-se onde está mais barato e vende-se onde está mais caro, ganhando a diferença. Com o tempo, essa prática tende a igualar os preços. Não é criar dinheiro, reduzir salários nem cancelar investimentos.', 'Arbitragem é aproveitar diferenças de preço do mesmo ativo em mercados diferentes: compra-se onde está mais barato e vende-se onde está mais caro, ganhando a diferença. Com o tempo, essa prática tende a igualar os preços. Não é reduzir salários, criar dinheiro nem cancelar investimentos.'),
    ('seed_financas_dificil_v2', 'O que é derivativo financeiro?', 'Derivativo é um instrumento financeiro cujo valor depende de outro ativo de referência, como uma ação, uma moeda ou uma mercadoria. Pode servir para proteção contra variações de preço ou para especulação. Não é conta bancária comum, cartão de crédito nem salário.', 'Derivativo é um instrumento financeiro cujo valor depende de outro ativo de referência, como uma ação, uma moeda ou uma mercadoria. Pode servir para proteção contra variações de preço ou para especulação. Não é conta bancária, cartão de crédito nem salário.'),
    ('seed_financas_dificil_v2', 'O que é contrato futuro?', 'Contrato futuro é um acordo para comprar ou vender um ativo numa data futura, por um preço definido hoje. Protege quem quer travar o preço, como um produtor que fixa o valor da colheita, e também é usado para especular. É um tipo de derivativo. Não é empréstimo pessoal nem conta de poupança.', 'Contrato futuro é um acordo para comprar ou vender um ativo numa data futura, por um preço definido hoje. Protege quem quer travar o preço, como um produtor que fixa o valor da colheita, e também é usado para especular. É um tipo de derivativo. Não é empréstimo, poupança nem compra à vista.'),
    ('seed_financas_dificil_v2', 'O que é hedge financeiro?', 'Hedge é uma estratégia para proteger investimentos contra variações desfavoráveis de preço, como um exportador que fixa a taxa de câmbio para não perder se a moeda cair. Reduz o risco, mas não elimina todos os riscos e tem um custo. Não é uma forma de aumentar despesas nem um imposto.', 'Hedge é uma estratégia para proteger investimentos contra variações desfavoráveis de preço, como um exportador que fixa a taxa de câmbio para não perder se a moeda cair. Reduz o risco, mas não elimina todos os riscos e tem um custo. Não é aumentar despesas nem um imposto.'),
    ('seed_financas_dificil_v2', 'O que é governança corporativa?', 'Governança corporativa é o sistema de regras e práticas para administrar empresas com transparência e responsabilidade, protegendo sócios, investidores e outros interessados. Empresas bem governadas costumam inspirar mais confiança. Não é método de venda, só controle de funcionários nem sistema bancário.', 'Governança corporativa é o sistema de regras e práticas para administrar empresas com transparência e responsabilidade, protegendo sócios, investidores e outros interessados. Empresas bem governadas costumam inspirar mais confiança. Não é método de venda, controle só de funcionários nem sistema bancário.'),
    ('seed_financas_dificil_v2', 'O que é compliance financeiro?', 'Compliance é o conjunto de práticas que garante o cumprimento das normas e leis financeiras, evitando multas, sanções e prejuízo de reputação. Não é redução de funcionários, aumento automático de lucro nem criação de dívidas.', 'Compliance é o conjunto de práticas que garante o cumprimento das normas e leis financeiras, evitando multas, sanções e prejuízo de reputação. Não é cortar funcionários, aumentar o lucro automaticamente nem criar dívidas.')
  ) AS v(source, statement, old_explanation, new_explanation)
  WHERE q.source = v.source
    AND q.statement = v.statement
    AND q.explanation = v.old_explanation;

  GET DIAGNOSTICS v_updated = ROW_COUNT;
  RAISE NOTICE 'Explicações coerentes com as novas alternativas (Finanças difícil lote 2: 047#26-31 e 073#1-19): % atualizada(s) (previstas: 21).', v_updated;
END $$;
