-- Explicações pedagógicas (BE-004) — Produtividade difícil lote 2: 25 perguntas seguintes do seed v2 (v2#2 a v2#26, migration 078).
-- Preenche questions.explanation com o "Por quê?" de cada pergunta (linguagem simples, com o raciocínio, conforme
-- docs/quiz-v2-rodadas-e-feedback.md), já coerente com as alternativas novas da migration 262. Só atualiza perguntas
-- que ainda NÃO têm explicação, então é idempotente e nunca sobrescreve texto já escrito. Não altera perguntas nem
-- alternativas. Se alguma pergunta já não existir, é simplesmente ignorada (nunca falha, para não impedir o arranque
-- do backend: as migrations correm no deploy). O runner já envolve o ficheiro numa transação.

DO $$
DECLARE
  v_updated INTEGER;
BEGIN
  UPDATE questions q
  SET explanation = v.explanation
  FROM (VALUES
    ('seed_produtividade_dificil_v2', 'Um profissional planeia 8 horas de trabalho com tarefas que somam exatamente 8 horas, sem considerar interrupções ou imprevistos. Qual é o principal problema?', 'Planear as 8 horas inteiras com tarefas que somam exatamente 8 horas não deixa folga: qualquer interrupção ou imprevisto atrasa o resto do dia. O principal problema é a falta de margem de segurança, não o excesso de tempo livre ou de prioridades.'),
    ('seed_produtividade_dificil_v2', 'Uma tarefa importante tem prazo para amanhã, enquanto várias tarefas menores não possuem prazo definido. Qual princípio deve orientar a decisão?', 'Uma tarefa importante com prazo amanhã pede que se olhe para urgência e importância em conjunto. Escolher pela duração, pelo gosto ou deixar a tarefa principal para depois ignora o que realmente conta.'),
    ('seed_produtividade_dificil_v2', 'Um gestor percebe que a equipa passa grande parte do dia respondendo mensagens, enquanto atividades estratégicas ficam atrasadas. Qual intervenção tende a ser mais eficiente?', 'Criar períodos específicos para comunicação protege o tempo das atividades estratégicas, porque a equipa responde às mensagens em horários combinados. Verificar mais vezes ou juntar reuniões piora a interrupção constante.'),
    ('seed_produtividade_dificil_v2', 'Uma pessoa trabalha oito horas, mas passa frequentemente de uma aplicação para outra. Qual indicador seria mais útil para diagnosticar o problema?', 'Se a pessoa passa o dia a saltar de uma aplicação para outra, o indicador mais útil é a frequência das mudanças de contexto. Número de aplicações, de ficheiros ou o tamanho do monitor não mostram quantas vezes a atenção é interrompida.'),
    ('seed_produtividade_dificil_v2', 'Um projeto está atrasado porque uma única pessoa precisa aprovar todas as etapas. Qual conceito descreve melhor essa situação?', 'Quando uma única pessoa precisa de aprovar todas as etapas, o fluxo fica limitado por ela: isso é um gargalo. O trabalho só avança à velocidade da etapa mais lenta.'),
    ('seed_produtividade_dificil_v2', 'Para eliminar um gargalo, uma equipa simplesmente adiciona mais tarefas à etapa já sobrecarregada. Qual é o problema dessa estratégia?', 'Pôr mais tarefas numa etapa já sobrecarregada não aumenta a sua capacidade: só cria mais fila e pode agravar a limitação existente. O caminho é libertar ou reforçar a etapa, não carregá-la ainda mais.'),
    ('seed_produtividade_dificil_v2', 'Uma empresa quer descobrir por que um processo demora muito. Qual abordagem é mais adequada?', 'Para descobrir porque um processo demora, é preciso mapear as etapas e ver onde há mais espera, porque é aí que o tempo se perde. Alargar prazos ou contar pessoas não mostra a causa da demora.'),
    ('seed_produtividade_dificil_v2', 'Um funcionário termina 30 tarefas de baixa importância enquanto deixa duas tarefas críticas pendentes. O que isso demonstra?', 'Terminar 30 tarefas de baixa importância e deixar duas críticas por fazer mostra uma falha de priorização: o esforço foi para o que tem menos valor. Ocupar-se muito não é o mesmo que ser produtivo.'),
    ('seed_produtividade_dificil_v2', 'Qual combinação representa melhor produtividade sustentável?', 'Produtividade sustentável é obter resultados relevantes usando bem os recursos, sem desgaste que não se aguenta a longo prazo. Rapidez sem qualidade, agenda cheia sem resultados ou trabalho sem pausas não se mantêm.'),
    ('seed_produtividade_dificil_v2', 'Uma tarefa apresenta grande impacto, mas não é urgente. Outra é urgente, mas possui pouco impacto. Qual abordagem evita uma decisão simplista?', 'Com uma tarefa de grande impacto e outra urgente, a decisão deve avaliar impacto e urgência em conjunto, para não cair na regra simples de fazer só o mais urgente ou só o mais importante.'),
    ('seed_produtividade_dificil_v2', 'Um profissional possui energia elevada pela manhã e baixa concentração no final do dia. Como pode adaptar o planejamento?', 'Quem tem mais energia de manhã deve usar esse período para as tarefas que exigem mais raciocínio, e deixar as mais leves para o fim do dia, quando a concentração cai. Fazer o contrário desperdiça a melhor fase.'),
    ('seed_produtividade_dificil_v2', 'O que significa alinhar tarefas com níveis de energia?', 'Alinhar tarefas com níveis de energia é pôr cada tipo de atividade no período em que se rende mais nela. Não é evitar o difícil, esperar pela motivação nem ignorar o tipo de tarefa.'),
    ('seed_produtividade_dificil_v2', 'Uma equipa mede produtividade apenas pelo número de tarefas concluídas. Qual limitação existe?', 'Contar só tarefas concluídas não diz se foram bem feitas nem se importaram: não considera qualidade nem impacto. Uma equipa pode fechar muitas tarefas e avançar pouco no objetivo.'),
    ('seed_produtividade_dificil_v2', 'Qual indicador seria mais completo para avaliar a execução de um projeto?', 'O indicador mais completo compara os resultados alcançados com os objetivos e os recursos gastos. Mensagens, horas e tarefas realizadas medem esforço ou atividade, mas não dizem se o projeto está a atingir o que se propôs.'),
    ('seed_produtividade_dificil_v2', 'Um projeto possui prazo fixo e várias atividades dependentes umas das outras. Qual ferramenta pode ajudar a visualizar a sequência temporal?', 'O cronograma mostra as atividades ordenadas no tempo e as suas dependências, por isso ajuda a ver a sequência do projeto e o prazo. As outras opções não organizam o trabalho por datas.'),
    ('seed_produtividade_dificil_v2', 'Uma tarefa crítica depende de outra que frequentemente atrasa. Qual é o primeiro passo mais adequado?', 'Se uma tarefa crítica depende de outra que costuma atrasar, o primeiro passo é identificar e gerir essa dependência, por exemplo acompanhando-a de perto. Ignorá-la ou só mexer no prazo não resolve a causa.'),
    ('seed_produtividade_dificil_v2', 'Uma equipa possui muitas tarefas classificadas como "urgentes". Qual problema isso pode indicar?', 'Quando quase tudo é "urgente", costuma faltar critério claro de prioridade, e por isso tudo parece pedir ação imediata. Com critérios bem definidos, só poucas coisas seriam urgentes.'),
    ('seed_produtividade_dificil_v2', 'Se tudo é considerado prioridade, qual é a consequência mais provável?', 'Se tudo é prioridade, nada se destaca: a distinção entre prioridades desaparece e a equipa não sabe por onde começar. Priorizar é, por definição, escolher o que vem antes.'),
    ('seed_produtividade_dificil_v2', 'Uma pessoa estabelece uma meta de "trabalhar mais". Por que essa meta é fraca?', '"Trabalhar mais" é uma meta fraca porque não define claramente o resultado desejado: não se sabe quando foi cumprida. Uma boa meta diz o que se quer alcançar e como se verifica.'),
    ('seed_produtividade_dificil_v2', 'Qual característica torna uma meta mais mensurável?', 'Uma meta é mensurável quando define um resultado que pode ser verificado, normalmente com números e prazo. Prazos, números e palavras precisas é que tornam a verificação possível.'),
    ('seed_produtividade_dificil_v2', 'Um profissional quer reduzir o tempo gasto numa atividade repetitiva. Qual sequência é mais racional?', 'A ordem racional é medir o processo, identificar desperdícios e só depois automatizar o que fizer sentido. Automatizar logo, sem analisar, apenas torna mais rápido um processo que pode estar mal desenhado.'),
    ('seed_produtividade_dificil_v2', 'Por que automatizar um processo mal estruturado pode ser problemático?', 'Automatizar um processo mal estruturado pode torná-lo mais rápido sem resolver a causa da ineficiência, e os problemas passam a acontecer mais depressa. Primeiro arruma-se o processo; depois automatiza-se.'),
    ('seed_produtividade_dificil_v2', 'Uma equipa automatizou uma tarefa, mas agora erros são replicados em grande escala. Qual princípio foi negligenciado?', 'Se os erros são replicados em grande escala, faltou validar o processo antes de o automatizar. A automatização repete tudo, certo ou errado, por isso o processo tem de estar correto antes.'),
    ('seed_produtividade_dificil_v2', 'Qual situação representa melhor uma melhoria de processo?', 'Melhorar um processo é, por exemplo, eliminar uma etapa desnecessária sem prejudicar o resultado: faz-se o mesmo com menos esforço. Mais aprovações, etapas ou relatórios sem finalidade só acrescentam trabalho.'),
    ('seed_produtividade_dificil_v2', 'Uma equipa realiza uma reunião semanal de duas horas, mas grande parte dos participantes não precisa participar de todos os assuntos. Qual melhoria é mais adequada?', 'Se muitos participantes não precisam de estar em todos os assuntos, convidar só os relevantes para cada tema poupa tempo e mantém a reunião útil. Alargar a reunião ou tirar a pauta piora o problema.')
  ) AS v(source, statement, explanation)
  WHERE q.source = v.source
    AND q.statement = v.statement
    AND (q.explanation IS NULL OR btrim(q.explanation) = '');

  GET DIAGNOSTICS v_updated = ROW_COUNT;
  RAISE NOTICE 'Explicações Produtividade difícil lote 2: % pergunta(s) atualizada(s) (esperado: 25).', v_updated;
END $$;
