-- Explicações pedagógicas (BE-004) — Produtividade difícil lote 3: 25 perguntas seguintes do seed v2 (v2#27 a v2#51, migration 078).
-- Preenche questions.explanation com o "Por quê?" de cada pergunta (linguagem simples, com o raciocínio, conforme
-- docs/quiz-v2-rodadas-e-feedback.md), já coerente com as alternativas novas da migration 264. Só atualiza perguntas
-- que ainda NÃO têm explicação, então é idempotente e nunca sobrescreve texto já escrito. Não altera perguntas nem
-- alternativas. Se alguma pergunta já não existir, é simplesmente ignorada (nunca falha, para não impedir o arranque
-- do backend: as migrations correm no deploy). O runner já envolve o ficheiro numa transação.

DO $$
DECLARE
  v_updated INTEGER;
BEGIN
  UPDATE questions q
  SET explanation = v.explanation
  FROM (VALUES
    ('seed_produtividade_dificil_v2', 'Uma reunião termina sem decisões, responsáveis ou prazos. Qual é uma das principais falhas?', 'Uma reunião que termina sem decisões, responsáveis ou prazos não deixa encaminhamentos concretos: ninguém sabe o que fazer a seguir. É essa falta de seguimento que faz a reunião não produzir resultado.'),
    ('seed_produtividade_dificil_v2', 'Qual elemento transforma uma decisão de reunião em uma ação acompanhável?', 'Uma decisão só se torna uma ação acompanhável quando tem um responsável e um prazo: assim sabe-se quem faz e até quando. Mais perguntas, mais participantes ou repetir a discussão não dão seguimento.'),
    ('seed_produtividade_dificil_v2', 'Uma pessoa recebe uma tarefa vaga: "Melhorar o relatório". Qual pergunta ajudaria a transformar a tarefa em algo executável?', '"Melhorar o relatório" é vago. Perguntar qual resultado específico deve ser melhorado define o que significa estar pronto e torna a tarefa executável. As outras perguntas falam de reuniões, mensagens ou programas, não do resultado esperado.'),
    ('seed_produtividade_dificil_v2', 'O que é ambiguidade de tarefa?', 'Ambiguidade de tarefa é quando o resultado esperado ou os critérios de execução não estão claros, e cada pessoa entende uma coisa. Isso gera retrabalho e atrasos, porque não se sabe o que significa "pronto".'),
    ('seed_produtividade_dificil_v2', 'Uma tarefa continua sendo refeita porque o responsável recebe instruções diferentes de várias pessoas. Qual problema existe?', 'Se a tarefa é refeita porque várias pessoas dão instruções diferentes, falta uma definição clara de responsabilidade e de critérios: ninguém sabe quem decide o quê. Mais clareza resolveria o problema, não o criaria.'),
    ('seed_produtividade_dificil_v2', 'Qual é uma vantagem de definir um "responsável final" por uma atividade?', 'Definir um responsável final evita que todos assumam a responsabilidade ao mesmo tempo, o que costuma acabar com ninguém a assumi-la. Não impede a colaboração nem as revisões, e também não impede erros.'),
    ('seed_produtividade_dificil_v2', 'Uma equipa começa novos projetos continuamente sem terminar os anteriores. Qual problema de gestão pode estar presente?', 'Começar projetos novos sem terminar os anteriores gera excesso de trabalho em andamento: muita coisa aberta, pouca concluída e atenção dividida. Terminar antes de começar mantém o fluxo.'),
    ('seed_produtividade_dificil_v2', 'Um funcionário inicia cinco tarefas e termina nenhuma. Qual métrica pode ajudar a identificar esse padrão?', 'O trabalho em andamento mostra quantas tarefas estão iniciadas e não concluídas, por isso revela quem começa muito e termina pouco. Tempo de almoço, feriados ou contactos não dizem nada sobre esse padrão.'),
    ('seed_produtividade_dificil_v2', 'O que significa limitar o trabalho em andamento?', 'Limitar o trabalho em andamento é controlar quantas tarefas podem estar a ser executadas ao mesmo tempo, para terminar antes de começar mais. Não é proibir a atividade nem fazer só uma tarefa a vida inteira.'),
    ('seed_produtividade_dificil_v2', 'Uma equipa mantém dez tarefas abertas porque "talvez sejam necessárias", embora apenas três sejam relevantes. Qual ação é mais produtiva?', 'Com dez tarefas abertas e só três relevantes, o mais produtivo é revisar e reduzir o trabalho em andamento, fechando ou descartando o que não importa. Guardar tudo "por segurança" só dispersa a atenção.'),
    ('seed_produtividade_dificil_v2', 'Um profissional planeia uma tarefa para duas horas, mas ela geralmente leva quatro. O que deve fazer antes de alterar todo o calendário?', 'Antes de mexer no calendário inteiro, convém perceber porque as estimativas falham: falta de informação, interrupções, esforço subestimado. Só assim a correção atinge a causa e não apenas o sintoma.'),
    ('seed_produtividade_dificil_v2', 'Por que registar o tempo real de execução pode melhorar o planejamento futuro?', 'Registar o tempo real permite comparar estimativas com resultados e ajustar os próximos planos com dados em vez de palpites. Não elimina imprevistos, não acelera o trabalho e não dispensa prazos.'),
    ('seed_produtividade_dificil_v2', 'Uma pessoa sempre subestima pequenas tarefas que, somadas, ocupam várias horas. Qual conceito explica melhor o problema?', 'Várias pequenas tarefas, somadas, ocupam muito tempo: é o efeito acumulativo de pequenas atividades. Cada uma parece rápida, mas o total pesa e costuma ser subestimado.'),
    ('seed_produtividade_dificil_v2', 'Qual estratégia ajuda a revelar atividades que consomem tempo sem contribuir muito para os objetivos?', 'Uma auditoria do uso do tempo regista o que se faz e quanto demora, e assim revela as atividades que consomem tempo sem contribuir muito. Eliminar registos ou ter mais notificações esconde o problema ou piora-o.'),
    ('seed_produtividade_dificil_v2', 'Uma pessoa passa duas horas por dia em atividades administrativas que poderiam ser automatizadas. Qual análise deve ser feita primeiro?', 'Antes de automatizar, convém ver com que frequência a atividade acontece, quanto custa e se vale a pena automatizar. Isto evita gastar esforço a automatizar o que pouco pesa.'),
    ('seed_produtividade_dificil_v2', 'Qual é o risco de otimizar uma tarefa isoladamente sem analisar o processo completo?', 'Otimizar uma tarefa isoladamente pode melhorar uma etapa e piorar o fluxo geral, por exemplo criando fila na etapa seguinte. Por isso convém olhar para o processo completo.'),
    ('seed_produtividade_dificil_v2', 'Uma equipa reduz o tempo de produção de um produto, mas aumenta o tempo de espera antes da entrega. Qual conclusão é mais adequada?', 'Reduzir o tempo de produção mas aumentar a espera antes da entrega mostra que melhorar uma etapa não basta: é preciso analisar o fluxo completo. O cliente só recebe o produto no fim.'),
    ('seed_produtividade_dificil_v2', 'O que caracteriza uma otimização local?', 'Otimização local é melhorar uma parte do processo sem necessariamente melhorar o resultado global: a parte fica melhor, mas o conjunto pode ficar igual ou pior. O resultado final é o que conta.'),
    ('seed_produtividade_dificil_v2', 'Uma equipa utiliza uma ferramenta sofisticada, mas ninguém sabe claramente quais são as prioridades. Qual conclusão é mais razoável?', 'Uma ferramenta sofisticada não resolve sozinha a falta de prioridades: o problema é de organização. A tecnologia ajuda, mas primeiro a equipa tem de saber o que é importante.'),
    ('seed_produtividade_dificil_v2', 'Qual princípio deve orientar a escolha de uma ferramenta de produtividade?', 'A ferramenta deve ser escolhida pela necessidade real, e não pela moda, pela complexidade ou pela quantidade de funções. Uma ferramenta simples que resolve o problema vale mais do que uma sofisticada que não é usada.'),
    ('seed_produtividade_dificil_v2', 'Uma equipa utiliza três aplicações diferentes para armazenar a mesma informação. Qual risco aumenta?', 'Guardar a mesma informação em três aplicações fragmenta a informação: ninguém sabe qual versão é a certa e as cópias ficam desatualizadas. Centralizar reduz esse risco.'),
    ('seed_produtividade_dificil_v2', 'O que significa centralizar informações relevantes?', 'Centralizar informações relevantes é mantê-las acessíveis num sistema ou estrutura coerente, onde a equipa sabe encontrá-las. Copiar para vários lados ou só confiar em mensagens espalha a informação.'),
    ('seed_produtividade_dificil_v2', 'Uma pessoa tem um objetivo para seis meses, mas nunca verifica seu progresso. Qual problema existe?', 'Sem verificar o progresso, a pessoa não sabe se está perto ou longe da meta de seis meses nem a tempo de corrigir. O problema é a falta de acompanhamento, não o excesso de medição ou de revisão.'),
    ('seed_produtividade_dificil_v2', 'Qual frequência de revisão é mais adequada para uma meta de longo prazo?', 'A frequência de revisão deve ser periódica e ajustada à natureza da meta: curta demais cansa e distrai, longa demais deixa o desvio crescer. Não se trata de rever a cada minuto nem só no fim.'),
    ('seed_produtividade_dificil_v2', 'Uma meta está atrasada porque as condições externas mudaram significativamente. Qual comportamento demonstra boa gestão?', 'Quando as condições mudam bastante, boa gestão é reavaliar as premissas e ajustar o plano. Insistir no plano antigo ou abandonar a meta sem análise ignora o que mudou.')
  ) AS v(source, statement, explanation)
  WHERE q.source = v.source
    AND q.statement = v.statement
    AND (q.explanation IS NULL OR btrim(q.explanation) = '');

  GET DIAGNOSTICS v_updated = ROW_COUNT;
  RAISE NOTICE 'Explicações Produtividade difícil lote 3: % pergunta(s) atualizada(s) (esperado: 25).', v_updated;
END $$;
