-- Explicações pedagógicas (BE-004) — Tecnologia difícil lote 4: perguntas 26 a 48 do seed dificil_v2 (migration 056) e 1 e 2 do seed dificil_v3 (migration 066).
-- Preenche questions.explanation com o "Por quê?" de cada pergunta (raciocínio e relação entre conceitos, nível difícil, conforme
-- docs/quiz-v2-rodadas-e-feedback.md), já coerente com as alternativas novas da migration 324. Só atualiza perguntas
-- que ainda NÃO têm explicação, então é idempotente e nunca sobrescreve texto já escrito. Não altera perguntas nem
-- alternativas. Se alguma pergunta já não existir, é simplesmente ignorada (nunca falha, para não impedir o arranque
-- do backend: as migrations correm no deploy). O runner já envolve o ficheiro numa transação.

DO $$
DECLARE
  v_updated INTEGER;
BEGIN
  UPDATE questions q
  SET explanation = v.explanation
  FROM (VALUES
    ('seed_tecnologia_dificil_v2', 'O que é consistência eventual?', 'Na consistência eventual, as réplicas de um sistema distribuído podem divergir por um tempo, mas, sem novas escritas, acabam por convergir para o mesmo valor. Troca-se a sincronização imediata por disponibilidade e desempenho, ao contrário da consistência forte, em que todas concordam antes de confirmar.'),
    ('seed_tecnologia_dificil_v2', 'O que é cache?', 'Cache é um armazenamento temporário de dados usados com frequência, que evita repetir consultas ou cálculos lentos e acelera os acessos seguintes. Difere do backup, que guarda cópias permanentes para recuperação, e dos logs, que apenas registram eventos.'),
    ('seed_tecnologia_dificil_v2', 'Qual é um problema potencial de um cache mal configurado?', 'Se o cache não é invalidado ou atualizado quando os dados mudam, passa a devolver uma versão antiga ao usuário. Por isso a configuração do tempo de vida e da invalidação é tão importante quanto o ganho de velocidade que o cache traz.'),
    ('seed_tecnologia_dificil_v2', 'O que é uma vulnerabilidade de SQL Injection?', 'SQL Injection ocorre quando entradas do usuário não tratadas são incorporadas às consultas SQL, permitindo que um atacante altere o seu sentido e leia, modifique ou apague dados. É uma falha da aplicação, diferente de problemas de rede ou de certificados.'),
    ('seed_tecnologia_dificil_v2', 'Qual prática ajuda a prevenir SQL Injection?', 'As consultas parametrizadas (prepared statements) enviam a estrutura da consulta e os valores em separado, de modo que a entrada do usuário nunca é interpretada como comando SQL. Concatenar texto digitado nas consultas é justamente o que cria a vulnerabilidade.'),
    ('seed_tecnologia_dificil_v2', 'O que caracteriza um ataque XSS?', 'No XSS (cross-site scripting), o atacante consegue inserir código executável, normalmente JavaScript, numa página que outros usuários vão visualizar, e esse código corre no navegador deles. Por isso pode roubar sessões ou alterar o conteúdo apresentado.'),
    ('seed_tecnologia_dificil_v2', 'Qual prática ajuda a reduzir riscos de XSS?', 'Escapar ou sanitizar os dados conforme o contexto em que serão exibidos (HTML, atributo, URL) impede que o navegador os execute como código. Cifrar o tráfego com HTTPS protege a comunicação, mas não impede que um script já injetado seja executado.'),
    ('seed_tecnologia_dificil_v2', 'O que é CSRF?', 'No CSRF, o atacante aproveita que o navegador envia automaticamente as credenciais do usuário autenticado e o leva a realizar uma ação que ele não pretendia, como alterar dados ou transferir valores. O ataque explora a confiança do sistema no navegador.'),
    ('seed_tecnologia_dificil_v2', 'Qual mecanismo pode ajudar a proteger aplicações contra CSRF?', 'Os tokens anti-CSRF são valores imprevisíveis exigidos em cada requisição que altera o estado do sistema; um site malicioso não consegue obtê-los, por isso não consegue forjar a ação. Logs, balanceadores e compactação não validam a origem do pedido.'),
    ('seed_tecnologia_dificil_v2', 'Qual é uma prática recomendada para armazenamento de senhas?', 'Para guardar senhas devem usar-se funções de hash próprias para isso, lentas e adaptativas, combinadas com um salt único por usuário, de modo que a senha original não possa ser recuperada. Base64 apenas codifica e a criptografia reversível pode ser desfeita com a chave.'),
    ('seed_tecnologia_dificil_v2', 'Por que um salt é utilizado no armazenamento de senhas?', 'O salt é um valor aleatório somado à senha antes do hash. Assim, senhas iguais geram hashes diferentes e tabelas pré-computadas (como rainbow tables) deixam de servir, obrigando o atacante a atacar cada senha em separado. Não serve para recuperar senhas nem para acelerar o login.'),
    ('seed_tecnologia_dificil_v2', 'Qual é a finalidade principal de HTTPS?', 'O HTTPS é o HTTP transportado sobre TLS, o que cifra a comunicação e permite autenticar o servidor, protegendo contra escuta e adulteração. Não acelera nem comprime a comunicação, e a tradução de nomes em endereços IP é função do DNS.'),
    ('seed_tecnologia_dificil_v2', 'O que é TLS?', 'O TLS é o protocolo criptográfico que fornece confidencialidade, integridade e autenticação nas comunicações em rede, sendo a base do HTTPS. Não encaminha pacotes (função dos protocolos de roteamento), nem transfere arquivos ou resolve domínios.'),
    ('seed_tecnologia_dificil_v2', 'Em criptografia assimétrica, qual característica é correta?', 'Na criptografia assimétrica há um par de chaves matematicamente relacionadas: o que se cifra com a pública só se decifra com a privada, e a privada nunca é partilhada. A criptografia simétrica, em contraste, usa uma única chave secreta compartilhada.'),
    ('seed_tecnologia_dificil_v2', 'Qual é uma diferença fundamental entre criptografia simétrica e assimétrica?', 'A diferença está na gestão das chaves: na simétrica, quem cifra e quem decifra partilham a mesma chave secreta, o que é rápido mas exige trocá-la com segurança; na assimétrica, usa-se um par de chaves, o que resolve a troca mas é mais lento.'),
    ('seed_tecnologia_dificil_v2', 'O que é uma assinatura digital?', 'A assinatura digital usa a chave privada do remetente para gerar uma prova que qualquer pessoa pode verificar com a chave pública, garantindo autenticidade e integridade. Não oculta o conteúdo (isso é cifrar) nem é uma imagem de uma assinatura manuscrita.'),
    ('seed_tecnologia_dificil_v2', 'Em inteligência artificial, o que é overfitting?', 'No overfitting o modelo memoriza detalhes e ruído do conjunto de treinamento e, por isso, tem ótimo desempenho nele, mas erra em dados novos. É o oposto do underfitting, em que o modelo aprende pouco e vai mal até nos dados de treino.'),
    ('seed_tecnologia_dificil_v2', 'Qual técnica pode ajudar a reduzir overfitting em modelos de Machine Learning?', 'A regularização penaliza a complexidade do modelo (por exemplo, pesos muito grandes) e o obriga a aprender padrões gerais em vez de decorar o treinamento. Treinar por mais tempo ou ter menos dados tende a agravar o overfitting, não a reduzi-lo.'),
    ('seed_tecnologia_dificil_v2', 'O que é um conjunto de validação em Machine Learning?', 'O conjunto de validação serve para avaliar o modelo durante o desenvolvimento e escolher hiperparâmetros ou versões, sem tocar nos dados de teste. O conjunto de treino ajusta os parâmetros, e o de teste mede o desempenho final, só no fim do processo.'),
    ('seed_tecnologia_dificil_v2', 'O que é inferência em um modelo de Machine Learning?', 'A inferência é a fase em que um modelo já treinado recebe dados novos e produz previsões ou resultados, sem alterar os seus parâmetros. É diferente do treinamento, que ajusta o modelo com dados de exemplo, e da coleta e rotulagem dos dados.'),
    ('seed_tecnologia_dificil_v2', 'O que é containerização?', 'A containerização empacota a aplicação com as suas dependências num ambiente isolado que corre da mesma forma em qualquer máquina com o motor de contêineres. Difere da máquina virtual, que emula um computador completo com o seu próprio sistema operacional.'),
    ('seed_tecnologia_dificil_v2', 'Qual é uma vantagem importante da containerização?', 'Como o contêiner leva consigo as dependências, a aplicação corre da mesma forma no portátil, no teste e na produção, o que facilita a portabilidade e a consistência. Ele compartilha o kernel do servidor e continua a exigir testes e atualizações.'),
    ('seed_tecnologia_dificil_v2', 'O que é CI/CD no desenvolvimento de software?', 'CI/CD combina a integração contínua, em que o código é integrado e testado automaticamente a cada alteração, com a entrega contínua, que prepara e libera versões de forma frequente. A automação reduz erros manuais e encurta o ciclo entre escrever e entregar.'),
    ('seed_tecnologia_dificil_v3', 'Qual é a principal finalidade de uma arquitetura de microsserviços?', 'Na arquitetura de microsserviços a aplicação é dividida em serviços pequenos e independentes, cada um com uma responsabilidade, que se comunicam por APIs e podem ser implantados e escalados separadamente. É o oposto do monolito, em que tudo corre como um só bloco.'),
    ('seed_tecnologia_dificil_v3', 'O que é computação em nuvem híbrida?', 'A nuvem híbrida combina infraestrutura local (própria) com serviços de nuvem pública, permitindo, por exemplo, manter dados sensíveis internamente e usar a nuvem para picos de demanda. Não é só nuvem de um provedor, nem só servidores próprios, nem multi-nuvem.')
  ) AS v(source, statement, explanation)
  WHERE q.source = v.source
    AND q.statement = v.statement
    AND q.explanation IS NULL;

  GET DIAGNOSTICS v_updated = ROW_COUNT;
  RAISE NOTICE 'Explicações Tecnologia difícil lote 4: perguntas 26 a 48 do seed dificil_v2 (migration 056) e 1 e 2 do seed dificil_v3 (migration 066): % pergunta(s) atualizada(s) (esperado: 25).', v_updated;
END $$;
