-- Explicações pedagógicas (BE-004) — Marketing Digital difícil lote 1: as 24 perguntas ativas do seed dificil_v1 (migration 039) e a 1.ª do dificil_v2 (migration 050).
-- Preenche questions.explanation com o "Por quê?" de cada pergunta (raciocínio e relação entre conceitos, nível difícil, conforme
-- docs/quiz-v2-rodadas-e-feedback.md), já coerente com as alternativas novas da migration 520. Só atualiza perguntas
-- que ainda NÃO têm explicação, então é idempotente e nunca sobrescreve texto já escrito. Não altera perguntas nem
-- alternativas. Se alguma pergunta já não existir, é simplesmente ignorada (nunca falha, para não impedir o arranque
-- do backend: as migrations correm no deploy). O runner já envolve o ficheiro numa transação.

DO $$
DECLARE
  v_updated INTEGER;
BEGIN
  UPDATE questions q
  SET explanation = v.explanation
  FROM (VALUES
    ('seed_marketing_digital_dificil_v1', 'O que é LTV?', 'O LTV (lifetime value) estima o valor que um cliente pode gerar para a empresa durante todo o relacionamento, não apenas na primeira compra. Por isso se compara com o custo de adquirir o cliente (CAC). O custo de atrair um cliente, o número de leads ou o retorno de um anúncio são outras métricas.'),
    ('seed_marketing_digital_dificil_v1', 'Por que comparar LTV e CAC pode ser importante?', 'Comparar LTV e CAC mostra se o valor que o cliente gera ao longo do tempo cobre, e idealmente supera, o custo de o conquistar; uma relação LTV/CAC baixa indica que a aquisição pode não compensar. Seguidores, carregamento do site ou orçamento de mídia não respondem a essa pergunta.'),
    ('seed_marketing_digital_dificil_v1', 'O que é retenção de clientes?', 'Retenção é a capacidade de manter os clientes ativos ou ligados à empresa ao longo do tempo, e costuma sair mais barata do que adquirir novos. Atrair visitantes, subir preços ou cortar custos de anúncios são outros objetivos.'),
    ('seed_marketing_digital_dificil_v1', 'O que é churn?', 'Churn é a taxa de clientes que deixam de usar ou cancelam um serviço num período; é o inverso da retenção. Cliques, aberturas e pedidos não pagos medem outras coisas. Um churn alto corrói o LTV.'),
    ('seed_marketing_digital_dificil_v1', 'Por que churn elevado pode ser um problema?', 'Um churn elevado indica dificuldade em manter clientes e obriga a gastar mais para substituir os que saem, o que pressiona o custo de aquisição e reduz o LTV. Não é sinal de facilidade em fidelizar nem de excesso de clientes.'),
    ('seed_marketing_digital_dificil_v1', 'O que é atribuição de marketing?', 'Atribuição de marketing analisa quais canais ou pontos de contato recebem o crédito por uma conversão, segundo um modelo como último clique ou linear. Serve para decidir onde investir. Não define verbas, não mede cliques isolados nem comissões de vendedores.'),
    ('seed_marketing_digital_dificil_v1', 'O que é jornada do cliente?', 'A jornada do cliente é o conjunto de etapas e interações que uma pessoa pode percorrer, do primeiro contato ao pós-venda. Ela é mais ampla do que uma campanha ou uma visita, e por isso a atribuição olha para os vários pontos de contato dela.'),
    ('seed_marketing_digital_dificil_v1', 'O que significa omnichannel?', 'Omnichannel busca integrar diferentes canais de interação, como loja, site e aplicativo, para dar uma experiência consistente: o cliente começa num canal e continua noutro sem perder o contexto. Concentrar tudo num canal ou separar os canais é o oposto.'),
    ('seed_marketing_digital_dificil_v1', 'O que é personalização em marketing?', 'Personalização adapta conteúdos, ofertas ou experiências com base em informações relevantes sobre o usuário, para aumentar a relevância. Não é padronizar nem apenas automatizar ou segmentar, embora use esses recursos.'),
    ('seed_marketing_digital_dificil_v1', 'Qual é um risco de personalização mal aplicada?', 'Quando mal aplicada, a personalização pode gerar experiências invasivas ou inadequadas e levantar preocupações de privacidade, por usar dados demais ou de forma pouco transparente. Relevância, rapidez e menos testes não são riscos, mas supostos benefícios.'),
    ('seed_marketing_digital_dificil_v1', 'O que é automação de marketing?', 'A automação de marketing usa ferramentas para executar tarefas de marketing com base em regras ou eventos, como enviar um email quando alguém se cadastra. Isso libera a equipe para o trabalho estratégico. Execução por profissionais, relatórios e anúncios não são automação.'),
    ('seed_marketing_digital_dificil_v1', 'Qual é um exemplo de automação de marketing?', 'Enviar automaticamente uma sequência de emails depois de uma ação do usuário, como o cadastro, é automação: o evento dispara o envio por regra. Fazer o envio manualmente, publicar posts à mão ou revisar anúncios depois de uma queda não é automação.'),
    ('seed_marketing_digital_dificil_v1', 'O que é remarketing baseado em comportamento?', 'O remarketing baseado em comportamento personaliza campanhas para quem já interagiu com a marca, respeitando as regras e permissões aplicáveis, como o consentimento. Campanhas genéricas, listas compradas ou apagar campanhas antigas não são remarketing.'),
    ('seed_marketing_digital_dificil_v1', 'O que é SEO técnico?', 'O SEO técnico cuida dos aspectos técnicos do site que influenciam rastreamento, indexação, desempenho e experiência, como velocidade e estrutura de links. Aspectos visuais, anúncios pagos e textos editoriais são outras frentes.'),
    ('seed_marketing_digital_dificil_v1', 'Por que velocidade de carregamento pode influenciar uma estratégia digital?', 'Sites lentos podem prejudicar a experiência do usuário, que desiste mais, e certos resultados de desempenho, como conversões e posicionamento. Não é verdade que sites lentos melhorem a experiência nem que a simplicidade substitua o cuidado com ela.'),
    ('seed_marketing_digital_dificil_v1', 'O que é intenção de busca?', 'A intenção de busca é o objetivo ou a necessidade que o usuário quer satisfazer ao pesquisar, como comprar, aprender ou comparar. Não é o local ou o aparelho, nem a frase digitada, que é a palavra-chave, nem o resultado apresentado.'),
    ('seed_marketing_digital_dificil_v1', 'Por que compreender a intenção de busca é importante para SEO?', 'Entender a intenção de busca permite criar conteúdo alinhado com o que o usuário realmente procura, o que melhora a relevância e tende a favorecer o desempenho. Escolher palavras populares sem esse critério não garante resultados.'),
    ('seed_marketing_digital_dificil_v1', 'O que é autoridade de domínio em SEO?', 'A autoridade de domínio é um conceito usado por algumas ferramentas para estimar a força relativa de um domínio, e não é uma métrica oficial universal dos buscadores. Por isso serve como referência comparativa, não como nota divulgada pelo Google nem como valor financeiro.'),
    ('seed_marketing_digital_dificil_v1', 'O que são backlinks?', 'Backlinks são links de outros sites que apontam para uma página ou domínio. Links internos ficam no mesmo site, e links de anúncios ou de emails enviados são outra coisa. Os backlinks são a base de vários sinais de autoridade.'),
    ('seed_marketing_digital_dificil_v1', 'Por que backlinks relevantes podem ser importantes para SEO?', 'Backlinks relevantes podem contribuir para sinais de autoridade e de descoberta, dependendo da qualidade e do contexto dos links, e não do volume. Não influenciam velocidade, segurança nem a quantidade de anúncios.'),
    ('seed_marketing_digital_dificil_v1', 'O que é marketing baseado em dados?', 'Marketing baseado em dados usa dados e métricas para orientar decisões, em vez de intuição ou opinião. Isso permite testar, medir e ajustar. Copiar tendências ou apenas armazenar planilhas não é decidir com base em dados.'),
    ('seed_marketing_digital_dificil_v1', 'Por que uma campanha com muitos cliques pode ainda ser considerada ruim?', 'Muitos cliques não significam necessariamente conversões, receita ou retorno positivo: o visitante pode clicar e sair. Por isso uma campanha deve ser avaliada pelo resultado de negócio e não só pelo volume de cliques. Cliques não geram penalidades nem reduzem as impressões.'),
    ('seed_marketing_digital_dificil_v1', 'O que é otimização de conversão?', 'A otimização de conversão melhora elementos da experiência ou da jornada, como a página, o formulário ou a oferta, para aumentar a proporção de usuários que realizam a ação desejada. Mede-se pela taxa de conversão, e não pelo número de visualizações.'),
    ('seed_marketing_digital_dificil_v1', 'Qual é uma estratégia mais sustentável para crescimento digital?', 'O crescimento sustentável combina conteúdo relevante, compreensão do público, testes, análise de dados, melhoria contínua e construção de confiança, porque esses elementos se reforçam. Imitar concorrentes, comprar seguidores ou prometer resultados rápidos dá ganhos curtos e arriscados.'),
    ('seed_marketing_digital_dificil_v2', 'O que é LTV no marketing?', 'O LTV no marketing estima o valor que um cliente pode gerar durante o relacionamento com a empresa, e por isso ajuda a decidir quanto vale a pena gastar para o conquistar. Não é o número de clientes de uma campanha, o retorno de um anúncio nem o tempo de compra.')
  ) AS v(source, statement, explanation)
  WHERE q.source = v.source
    AND q.statement = v.statement
    AND q.explanation IS NULL;

  GET DIAGNOSTICS v_updated = ROW_COUNT;
  RAISE NOTICE 'Explicações Marketing Digital difícil lote 1: as 24 perguntas ativas do seed dificil_v1 (migration 039) e a 1.ª do dificil_v2 (migration 050): % pergunta(s) atualizada(s) (esperado: 25).', v_updated;
END $$;
